### ISSUE TITLE
On Accept Bid, received "You are to broke..."

### ISSUE THREAD

**Issue by HenkSwardt** [particl/particl-desktop#1036]
When a seller wants to accept the bid on an item he is selling but has no unspent transactions, we are dispayin an error that says, "You are to broke...", This needs to be adjusted to the same error handling as when placing an order where we inform the user he cant enter an escrow as he has no unspent outputs.

Please see https://github.com/particl/particl-desktop/pull/1014 for details of handling errors on placing the bid.

**Comment by zaSmilingIdiot** [comment]
This has been implemented with the splitting of unspent outputs, included in the marketplace codebase via
https://github.com/particl/particl-market/pull/308
