### ISSUE TITLE
Listings duplicated when deleted after published

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1038]
Win64, Alpha release version.

Reproduction Steps: Go to Sell tab. Click on a listing to open additional info. Click the red X for deleting it. Click yes. (you get a toast saying you can't delete, but that's not the issue I'm reporting). Then close modal by clicking off it. I now see my items shown twice in my listings list.

Severity - minor. Leaving the Sell tab and coming back returns the list to normal so it is just a display issue not a data issue.

![image](https://user-images.githubusercontent.com/38863166/40852611-96d68fbe-6590-11e8-8d65-7e0558fb1133.png)

**Comment by kewde** [comment]
Dev note: most likely a bug with `loadPage(1)`.

**Comment by HenkSwardt** [comment]
Thank you for bringing this to our attention @CryptoBeans 

PLease note, the issue with the listing showing up in duplicate are being dealt with in https://github.com/particl/particl-desktop/pull/1039#issuecomment-394154346. 

The ability to delete or edit a listing that has been published has been disabled as well. As the message has been sent to the network of a listing, we will not be able to remove it or edit it. 

Please see screen shot below:

![image](https://user-images.githubusercontent.com/28799964/40907261-89fc8938-67e3-11e8-9d49-3d2f1a3193da.png)
