### ISSUE TITLE
Fix address filtering for profile

### ISSUE THREAD

**Issue by kewde** [particl/particl-desktop#1046]
https://github.com/particl/particl-desktop/blob/market/src/app/market/buy/checkout-process/checkout-process.component.html#L138

^showing all ShippingAddresses but it should use the ones filtered for SHIPPING_OWN.

1. make a model for Profile
2. Pipe all the outputs of profile.service into the Profile model
3. Insert special filter for ShippingAddresses:
https://github.com/particl/particl-desktop/blob/market/src/app/market/buy/checkout-process/checkout-process.component.ts#L208

**Comment by vikas-cis** [comment]
#1048
