### ISSUE TITLE
Move and refactor send-confirmation-modal.component.html - https://particl.atlassian.net/browse/PD-152

### ISSUE THREAD

**Issue by kewde** [particl/particl-desktop#1053]
```
/wallet/wallet/send/send-confirmation-modal/send-confirmation-modal.component.html
```

1. Move to /modals.
2. split into market and wallet confirmation modal

**Comment by kewde** [comment]
required for #1052

**Comment by HenkSwardt** [comment]
Hey @cis-shubham-t 

As per request from @kewde , please add this change to https://github.com/particl/particl-desktop/pull/1025

This should be the last Modal related change and will also allow us to send out a new version of Current Live Desktop, excluding the MP
