### ISSUE TITLE
History: filter by type not working

### ISSUE THREAD

**Issue by AllienWorks** [particl/particl-desktop#1059]
![screenshot from 2018-06-11 18-46-35](https://user-images.githubusercontent.com/1965795/41245304-fb51f66c-6da7-11e8-9f91-c51b94cd089d.png)

Filter by type doesn't show anything, even if it should, on Blind & Anon.
All transactions are included in Public.

**Comment by zaSmilingIdiot** [comment]
This should now be corrected: core v0.18.0.11 contains the fix. Can be confirmed at least on particl-desktop releases v2.0.0-alpha1-testnet or v1.4.0
