### ISSUE TITLE
A few SMSG commands not working in debug console

### ISSUE THREAD

**Issue by LiteBit** [particl/particl-desktop#1062]
# SMSG commands returning errors

`smsglocalkeys`, `smsgscanbuckets` and `smsgbuckets` are returning a _"Method Not found"_ error when typing them in the debug console

# How to reproduce

1. Open debug console in Particl Desktop
2. type `smsglocalkeys`, `smsgscanbuckets` and `smsgbuckets`
3. Hit Enter

# Workaround

I can get these commands working in Particl Qt wallet with `-testnet` appended on Run command

- Operating system and version: Windows 10, 64 bit
- Client version: 1.2.1-alpha-RC1
- Market version: 0.0.24
- Daemon: 0.16.0.7

**Comment by vikas-cis** [comment]
Hye @LiteBit Thanks for letting us know we are already working on this and below is the PR that currently under progress #1047
