### ISSUE TITLE
Nothing happens when I try to publish a listing on particl-desktop (market alpha / linux 64bit)

### ISSUE THREAD

**Issue by djangobits** [particl/particl-desktop#1065]
I just recently downloaded particle-desktop to test the Marketplace Alpha. Tried to set up a Sell listing. When I click "Update & Publish" from the listing page or when I try it by clicking "publish" in the list of saved templates, I'll be asked for the wallet password but then nothing happens, no feedback on the UI, article stays unpublished. Also after a few minutes, I do not see it in the listings.

-------------------

Ubuntu 17 - 64bit
Client: 1.2.1-alpha-RC1
Market: 0.0.24
Daemon: 0.16.0.7
Connected to 4 peers on Testnet

**Comment by zaSmilingIdiot** [comment]
@djangobits Could you perhaps update to the latest particl-desktop version? There have been a large number of changes in both the desktop and marketplace, and its likely that this issue has been resolved in the meanwhile. If not, we can always proceed with testing with the newer codebase.

**Comment by zaSmilingIdiot** [comment]
Closing due to age and lack of feedback.
