### ISSUE TITLE
Debian Linux Desktop File Error

### ISSUE THREAD

**Issue by Aphiso** [particl/particl-desktop#1091]
# Describe bug/issue
The file structure of the /opt directory is kind of messy and it throws off the .desktop file which also contains incorrect exec and path. The exec also has the executable file named incorrectly. It points to particl instead of particl-desktop which is the name of the executable.

.desktop file
```
[Desktop Entry]
Name=Particl
Comment=Particl, P2P Privacy ecosystem
Exec=/opt/particl/particl %U
Terminal=false
Type=Application
Icon=particl
Path=/opt/particl/
StartupNotify=true
Categories=Finance;

```
This contains incorrect paths. The Particl directory in the /opt folder should be renamed Particl-Desktop instead of 'Particl Desktop'. The space messes up the .desktop file even when the paths are correct.

After renaming the folder in the /opt directory, this would be the correct .desktop file
```
[Desktop Entry]
Name=Particl
Comment=Particl, P2P Privacy ecosystem
Exec=/opt/Particl-Desktop/particl-desktop %U
Terminal=false
Type=Application
Icon=particl
Path=/opt/Particl-Desktop/
StartupNotify=true
Categories=Finance;

```

# How to reproduce

Install particl-desktop .deb file.

# More information

- Operating system and version: Pop! 18.04/Ubuntu 18.04
- Client version: Latest

**Comment by kewde** [comment]
See #306
