### ISSUE TITLE
1.2.2 instability on Win 7 x64 (while staking)

### ISSUE THREAD

**Issue by oldominion** [particl/particl-desktop#1116]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue

Particl Desktop wallet hangs after a day or two of staking. This was also happening with 1.1.0.

Exception in Application Event log when interacting with the hung GUI/trying to close it cleanly.

Faulting application name: particl-desktop.exe, version: 1.2.2.0, time stamp: 0x5aaa6f9b
Faulting module name: particl-desktop.exe, version: 1.2.2.0, time stamp: 0x5aaa6f9b
Exception code: 0xc00000fd
Fault offset: 0x0000000002592145
Faulting process id: 0x3ddc
Faulting application start time: 0x01d42c46b4187da4
Faulting application path: D:\Program Files\PARTWallet\particl-desktop.exe
Faulting module path: D:\Program Files\PARTWallet\particl-desktop.exe

Also produces some errors in debug.log. Not sure if those are related.

 # How to reproduce

Describe the steps needed to recreate the bug/issue:

1. Open wallet
2. Unlock for staking
3. Wait.

# More information

- Operating system and version: Windows 7 x64
- Client version: 1.2.2

[particl-desktop-20180809.log](https://github.com/particl/particl-desktop/files/2282843/particl-desktop-20180809.log)
![image 347](https://user-images.githubusercontent.com/8029180/44030453-bcce172c-9ef8-11e8-8336-a7e49042f9ed.png)
![image 353](https://user-images.githubusercontent.com/8029180/44030463-c54a5d3e-9ef8-11e8-8a74-0ebd79e1e52f.png)

**Comment by kewde** [comment]
This is a know issue, it doesn't do any harm because the daemon shuts down properly.
Essentially, it waits for the daemon to close and keeps the window open.
We'll look into hiding the tray icon when the window has shut down.

**Comment by kewde** [comment]
The hanging issue you describe is not related to this issue.

**Comment by AllienWorks** [comment]
@oldominion is this still happening to you with 1.3.0?

**Comment by oldominion** [comment]
Understood regarding hanging issue vs the error msgbox. Nothing in the logs? 
I moved to staking on Linux build instead, which is stable, so i'm not able to test further with the Window client.

**Comment by zaSmilingIdiot** [comment]
I'm going to close this due to age and simply because we've moved on a couple of versions since.

Lets re-open this if we run into the issue going forward.
