### ISSUE TITLE
Daemon doesn't download (Alpha) win 10 x64, returns javascript error after quiting app

### ISSUE THREAD

**Issue by kasprrr** [particl/particl-desktop#1118]
# Describe bug/issue
Testing Particl Desktop Alpha. After starting Particl Desktop, Transactions keep loading, nothing is found daemon doesn't seem to download/start even though it worked before (couple times). I close the APP but particl icon in system tray stays there after quiting. When i click on it it gives me the following error:

![javascerror](https://user-images.githubusercontent.com/37086658/44113274-c507fa30-9fc4-11e8-9dca-61781413c29d.jpg)

EDIT: update, after removing both the chain, and all appdata, redownload and installing the ALPHA on Win10 x64, daemon doesn't download/start at all anymore, even though it worked before. 1.2.2 desktop wallet pre-release works fine on a clean install.

# How to reproduce

Describe the steps needed to recreate the bug/issue:

See above

# More information

- Operating system and version: Windows 10 x64
- Client version: Alpha 1.2.1 (RC1)

**Comment by HenkSwardt** [comment]
Hello @kasprrr 

Thank you for bringing this to our attention. We have been able to reproduce and will investigate the issue.

**Comment by zaSmilingIdiot** [comment]
This issue has since been fixed, along with some additional improvements to the (application and daemon) startup/shutdown process.
