### ISSUE TITLE
Dragging and dropping an image into Particl Desktop replaces UI with image

### ISSUE THREAD

**Issue by kasprrr** [particl/particl-desktop#1119]
# Describe bug/issue
Trying to drag and drop and image when wanting to list an item on the marketplace completely removes the user interface, instead showing the picture i tried to drag and drop. Need to restart app to make it work again. Drag and drop functionality is advised? See example on how to implement on the BitBay app.

edit: dragging and dropping a picture in any of the particle desktop screen replaces the UI with the image (also in latest desktop 1.2.2 pre-release version)

# How to reproduce

1. See above

# More information

- Operating system and version: Win 10 x64
- Client version: Particl Desktop Alpha 1.2.1 RC1

**Comment by HenkSwardt** [comment]
Thank you @kasprrr for reporting this. Task has been logged for this. 

Please see: https://particl.atlassian.net/browse/PD-374
