### ISSUE TITLE
Wallet is syncing pops up in the middle of wallet restore

### ISSUE THREAD

**Issue by ericmnel** [particl/particl-desktop#1127]
# Describe bug/issue

A pop up box saying "Wallet is syncing" gets created in the middle of wallet restore (after pasting in the seed, before typing in the restore password) forcing you to wait before you can finish creating your wallet.  This is potentially a security issue since your seed is just sitting there in plain text underneath the pop up so you have to physically wait there for the syncing to finish.

On the mac you can close the pop-up, but on Linux there is no close icon to click.

# How to reproduce

Describe the steps needed to recreate the bug/issue:

On Ubuntu:
1. start with no wallet (rm -rf ~/.particl)
2. particle-desktop &
3. Encrypt wallet
4. Restore wallet

# More information

- Operating system and version: Ubuntu 17.10
- Client version: 1.1.0

**Comment by ericmnel** [comment]
Actually its even worse than that - once syncing finishes there is no way to close the window.
![screenshot from 2018-08-29 10-56-10](https://user-images.githubusercontent.com/692338/44802921-2fbbd980-ab7a-11e8-8b99-466ff335c48b.png)

**Comment by kewde** [comment]
@ericmnel

https://github.com/particl/particl-desktop/releases

1.2.2 prerelease has an exitable window.

Will be fixed when multiwallet is merged and released.

**Comment by zaSmilingIdiot** [comment]
The modal is now closable. At least as of v1.3.0

In addition, the v2.0.0 releases no longer pop up the modal by defaul... the "pop up" action occurs now only on user action. That is, the user needs to explicitly select the syncing bar to show the syncing progress.
