### ISSUE TITLE
Cannot Publish Proposals

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1135]
Whenever I try to publish a new proposal, this pops up: 

<img width="362" alt="screen shot 2018-09-07 at 5 55 48 pm" src="https://user-images.githubusercontent.com/27031337/45246070-46c2a000-b2cd-11e8-8815-3e7a5d7a26e4.png">

Then, nothing else happens. I can keep clicking on Submit new proposal and the same notification box appears. 

My proposal does not make it into the proposal list. I use MacOS.

**Comment by HenkSwardt** [comment]
Good day @cryptoguard 

Do you maybe have a log for us with details to what happens when you see the "object Object" error?

Thanks

**Comment by HenkSwardt** [comment]
Sorry, I didnt have the screen refreshed with your feedback. 

Did you not receive the prompt to Unlock the wallet?

**Comment by HenkSwardt** [comment]
Shubham wwill investigate this for us.

**Comment by HenkSwardt** [comment]
@cryptoguard 

Can you please confirm that this has been resolved?

Thank you

**Comment by cryptoguard** [comment]
I cannot reproduce the error anymore. Seems fixed 👍

**Comment by zaSmilingIdiot** [comment]
Some work has gone into resolving error messages, to extract the correct error message (instead of displaying the '[object Object]' error.

This issue otherwise seems to have been resolved.
