### ISSUE TITLE
Typo in Proposals Page

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1136]
"depends", not "depands". 

<img width="402" alt="screen shot 2018-09-07 at 5 55 37 pm" src="https://user-images.githubusercontent.com/27031337/45246100-812c3d00-b2cd-11e8-9f12-9901526dfd17.png">

Link here: https://github.com/particl/particl-desktop/pull/1126#issuecomment-418910585

**Comment by HenkSwardt** [comment]
Shubham will have a look at this for us.

**Comment by cis-shubham-t** [comment]
I fixed the typo errors
here is the PR: https://github.com/particl/particl-desktop/pull/1138

**Comment by zaSmilingIdiot** [comment]
The fix has been implemented and merged.
