### ISSUE TITLE
I Seem to be Unable to Publish Listings with Multiple Pictures

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1144]
I can publish listings with 1 picture, but listings with more than 1 seem to stay in a Awaiting state for now at least an hour. All listings are set up for 4 weeks, and text is almost at full capacity on all of them. 

<img width="703" alt="screen shot 2018-09-12 at 4 33 16 pm" src="https://user-images.githubusercontent.com/27031337/45451754-05096f00-b6aa-11e8-8763-8cb6525d402d.png">

In the screenshot above, the Asus monitor listing has 2 pictures. The Louis Vuitton bag has one.

_**Note:** I do possess enough tPART to publish and cover for the escrow's security deposit._

**Comment by cryptoguard** [comment]
Ok so I shut Particl Desktop down, restarted it. In my Sell page, all listings that weren't published when I closed Particl Desktop were able to being published again. So I unlocked the wallet, tried to publish everything, and then it worked. However...

<img width="1155" alt="screen shot 2018-09-12 at 5 09 53 pm" src="https://user-images.githubusercontent.com/27031337/45453493-f3769600-b6ae-11e8-8400-998946d6b302.png">

1) The images uploaded with the listings I was able to publish the first time all uploaded in very bad quality
2) The other listings' images uploaded with good quality
3) Except for one listing which didn't even upload a listing picture (Harman Kardon...)

**Comment by HenkSwardt** [comment]
Hey @cryptoguard 

Can I ask that you please provide us with an Error log around the time of posting the listing. We would like to see what happens on the backend. 

Thank you

**Comment by cryptoguard** [comment]
> Hey @cryptoguard
> 
> Can I ask that you please provide us with an Error log around the time of posting the listing. We would like to see what happens on the backend.
> 
> Thank you

What's the command for it? Thanks!

**Comment by EagleEye25** [comment]
just tested with the above cercumstances, and recieved the same outcome, also created a listing item 20 min after the first, but with one picture and that went through in about 5 min

**Comment by zaSmilingIdiot** [comment]
Image processing has undergoing significant improvements. The quality of images has been significantly improved.

Regarding listings in awaiting status for significant amounts of time - this was largely due the smsgmessage sending service throwing an error when a message was sent, and the error not being caught. This has been corrected, and a failure to actually post the listing will now result in an appropriate error message being displayed to the user.

All of the reported items in this issue should now be resolved.
