### ISSUE TITLE
Community Proposals in the Sidebar

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1145]
<img width="249" alt="screen shot 2018-09-13 at 2 20 08 am" src="https://user-images.githubusercontent.com/27031337/45470401-a4a31d80-b6fb-11e8-8225-f50b5a8bc81a.png">
<img width="235" alt="screen shot 2018-09-13 at 2 20 18 am" src="https://user-images.githubusercontent.com/27031337/45470411-a967d180-b6fb-11e8-9733-f34a71c031c9.png">

Just a thought, not a bug...

But it seems like the Community Proposals tab is a bit out of place. When market and wallet are collapsed, Community Proposals is the only one with an icon and kinda look odd. Would it make sense to make it a collapsible menu like the others, without the icon?

Not sure honestly what the best tweak would be, but just thought I'd point out this observation if it can help.

**Comment by zaSmilingIdiot** [comment]
Makes (visual) sense. Would wrapping this in something like a 'Governance' heading make sense?

**Comment by cryptoguard** [comment]
> Would wrapping this in something like a 'Governance' heading make sense?

I could see that work. Would be even better if this governance heading ends up having more pages in the future (not sure though if you guys want to display listing governance stuff in there or in the Market tab).

**Comment by zaSmilingIdiot** [comment]
Additional menu options are being added to the sidebar, which makes the 'Proposals' option less 'out of place' than what it was/is currently.

**Comment by cryptoguard** [comment]
Cool! Can't wait to see what you guys are cooking up!

**Comment by zaSmilingIdiot** [comment]
We've just added the first of these additional items: 'Help and Support'. I'm closing this for now as we are now have at least one additional menu item added.
