### ISSUE TITLE
No Button to Clear Proposal Notifications

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1153]
As a user, I might not want to vote on every single proposals being submitted and still want to clear the notification count: 

<img width="232" alt="screen shot 2018-09-18 at 4 46 57 pm" src="https://user-images.githubusercontent.com/27031337/45715588-95d8c280-bb62-11e8-92aa-fb4791dbef8b.png">

There should be a button or way to clear the notification count back to 0 without having to vote on every single proposals.

**Comment by zaSmilingIdiot** [comment]
Thanks for the suggestion. This might be achieved by clearing the notification count when the proposals section is opened. The newest proposals are displayed first anyway, so is readily visible to the user when opening the page. 

Side note: we would then additionally need to ensure the notification count is not updated while the proposals page is currently open.

**Comment by HenkSwardt** [comment]
This will be looked at in https://particl.atlassian.net/browse/PD-467

**Comment by zaSmilingIdiot** [comment]
Has been implemented.
