### ISSUE TITLE
Impossible to "Accept terms" if you previously extend the size of the Desktop

### ISSUE THREAD

**Issue by michmish** [particl/particl-desktop#1195]
# Describe bug/issue
"Accept terms" stay in grey - impossible to click
..

# How to reproduce

launch a new Desktop, click on the double window square in top right corner to extend desktop windows. Even if you try to go to bottom it stays grey for "Accept terms"

# More information
- Operating system and version: Windows 10
- Client version: 1.2.2-alpha-RC1

**Comment by HenkSwardt** [comment]
This has been logged for investigation - https://particl.atlassian.net/browse/PD-420

**Comment by zaSmilingIdiot** [comment]
The ordering of the modals has been updated, so that the user is not overwhelmed on initial startup of the app. These changes should also resolve the above issue. The referenced pull request is https://github.com/particl/particl-desktop/pull/1258
