### ISSUE TITLE
Have to press "Back" 2 times instead of 1 to go Back 

### ISSUE THREAD

**Issue by michmish** [particl/particl-desktop#1196]
# Describe bug/issue -- minor issue

After clicking on "Create new Wallet"
If you want to go back you have to press 2 times the button "Back" to successfully go back

# How to reproduce

1/ Click on create a new wallet 
Your cursor is now on "Wallet name" in green
2/ Click on "Back"
You have the message in red "Wallet name is required"

If you want to go back you have to click again on "Back"

# More information

- Operating system and version: Windows 10 
- Client version: 1.2.2-alpha-RC1

**Comment by zaSmilingIdiot** [comment]
Thanks for reporting this: this appears to be related to input validation processing being applied on the first click of the back button: this needs to be removed for the Back button.

**Comment by HenkSwardt** [comment]
This issue has been logged for investigation. - https://particl.atlassian.net/browse/PD-463

**Comment by zaSmilingIdiot** [comment]
Fixed, and should be available in the next release.
