### ISSUE TITLE
UI/UX Improvement Suggestion on Shipping Profiles

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1198]
When buying an item for the first time, the user doesn't have a shipping profile registered (unless that is possible in the future with the Settings page). 

Here's what it looks like: 
<img width="449" alt="screen shot 2018-10-16 at 6 19 24 pm" src="https://user-images.githubusercontent.com/27031337/47051021-77b9ae80-d170-11e8-9558-0fe7f7e0449a.png">

When clicking on the dropdown menu, there is no action, which is kinda going against the user expectation of at least an empty dropdown menu. Perhaps, instead of having the menu being inactive, it could drop down with a single choice that says something like "None" or "Please save a shipping profile first". 

Perhaps there are better ways to do it as well. This is a minor detail but something I noticed as odd/unsatisfying.

**Comment by zaSmilingIdiot** [comment]
Thanks for the suggestion :)

This may be better served if we can disable the shipping profile dropdown if it contains no saved options.

**Comment by HenkSwardt** [comment]
This issue and further related issues will be addressed as part of this issue logged:

https://particl.atlassian.net/browse/PD-469
