### ISSUE TITLE
Overview Icon is Leaking Colors

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1199]
This does not happen everytime, but sometimes, the Overview icon on the sidebar leaks green when navigating in other pages of the wallet. You can see it screenshotted here: 

<img width="151" alt="screen shot 2018-10-16 at 6 20 18 pm" src="https://user-images.githubusercontent.com/27031337/47051107-d54dfb00-d170-11e8-9ba1-e16d2d1655bc.png">

This has been happening since 1.1 for me, so perhaps even before then. I am using MacOS 10.13.6.

**Comment by zaSmilingIdiot** [comment]
The screenshot appears to be missing?

Nevertheless, we can take a look into the behaviour.

**Comment by HenkSwardt** [comment]
Hey @cryptoguard 

Thank you for your input. I had a look at a couple of installs I'm running of the GUI, but not one of them does this strange overflow. Will it be possible for you to test this on another screen and let us know if it does the same?

Thank you

**Comment by cryptoguard** [comment]
Yes, maybe this could be because my screen is Mac's retina (5k vs 4k)?

**Comment by cryptoguard** [comment]
> The screenshot appears to be missing?

It's the small black rectangle in my post

**Comment by AllienWorks** [comment]
Is this issue still present?

**Comment by zaSmilingIdiot** [comment]
I'm closing this... if its still present it can be re-opened.
