### ISSUE TITLE
Buggy Behavior When Checking Out

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1200]
## Bug
When "checking out" and placing an order, a "TypeError" error notification pops up at the bottom of the page as soon as you click the **Place order** button. At this point, it isn't clear whether the order was placed or not because there is no visible confirmation, the page doesn't reload or update, and the item is still in the cart.

<img width="1440" alt="screen shot 2018-10-16 at 7 13 43 pm" src="https://user-images.githubusercontent.com/27031337/47052786-e51d0d80-d177-11e8-94f0-7e45e81a724e.png">

When looking into the **Orders** tab to check if the order was submitted, it says it was by displaying "Bidding".

<img width="852" alt="screen shot 2018-10-16 at 7 13 53 pm" src="https://user-images.githubusercontent.com/27031337/47052832-29101280-d178-11e8-9f47-2ace69a90146.png">

Again, when checking the cart, either by clicking on the cart icon at the top right of the client or by clicking on the **Your cart** top tab, the item is still in it and needs to be deleted from the cart manually because if not, the next order will again have the same order you've just placed. 

<img width="1440" alt="screen shot 2018-10-16 at 7 20 13 pm" src="https://user-images.githubusercontent.com/27031337/47052902-886e2280-d178-11e8-8095-cb6cfeadf5c1.png">

Additionally, when clicking the top **Your cart** tab, the client always redirects you to the latest step of the checkout process you were when left navigating elsewhere. For example, as was mentioned above, directly after placing my order, the "TypeError" notification pops up. The order is placed, but my cart still has the item I just bought in it. When I click the **Your cart** tab to delete the listing of the order I just posted, nothing happens, because I am already in my cart at Step 3 of the check out process (**Confirm and Place order** sub-tab). The only way to delete the listing is in the first step of the check out process, the sub-tab **Your cart** (in opposition to the top tab of the same name). Showed in the screenshot here: 

<img width="1440" alt="screen shot 2018-10-16 at 7 22 09 pm" src="https://user-images.githubusercontent.com/27031337/47053104-8bb5de00-d179-11e8-9cbd-d58a51aff17e.png">

So it goes to say that the notification shouldn't be an error and the listing should automatically be deleted from a user cart when successfully placed (when the bidding step begins). 

## Additional Suggestion:

The default behavior of when clicking on the cart icon at the top right of the client (like shown in the screenshot below) should be to redirect the user to the **Your cart** sub-tab which is in fact Step 1 of the check out process. This would replicate the intuitive UX most marketplaces already use. On eBay, Amazon, etc...when you click that main cart icon, regardless of where you are on the website it will always redirect you to the main cart page. 

<img width="1440" alt="screen shot 2018-10-16 at 7 28 14 pm" src="https://user-images.githubusercontent.com/27031337/47053402-bb191a80-d17a-11e8-9b2d-18942c000419.png">

**Comment by zaSmilingIdiot** [comment]
To address the bug report: this particular error has been encountered before, and may have been related to a corrupt or problematic particl-marketplace DB. The simplest solution was to (ensure that the app is closed) and then remove the particl-marketplace DB, letting it recreate itself correctly when the app relaunches.

Note that currently deleting the particl-marketplace DB will remove all listing items from your market; that is: on opening of the app again the Market > Listings page will no longer display existing items for sale (new listings will however be displayed when they are created).

With regards to the suggestion for returning to the 1st step of thebuy flow process, we can definitely look into adding this behaviour.

**Comment by cryptoguard** [comment]
> and then remove the particl-marketplace DB, letting it recreate itself correctly when the app relaunches.

Could it be done automatically? This seems complicated when thinking about "mainstream" end-users.

**Comment by zaSmilingIdiot** [comment]
Yep, this will most likely be done automatically in the future - DB migrations in the marketplace would modify the DB schema in place and bring everything up to date with the marketplace release in effect.

Did clearing the marketplace DB resolve the issue?

**Comment by cleansanchez** [comment]
I am experiencing the exact same behavior as described which was from a clean install. Even after deleting the marketplace DB as instructed the problem still persists. I am using Win10 Home and Client 1.2.2-alpha-RC1
Market 0.0.45
Core 0.17.0.1

**Comment by zaSmilingIdiot** [comment]
The checkout process returning to first step after navigating away and returning has been fixed in:
https://github.com/particl/particl-desktop/pull/1229

The "TypeError" is most likely a problem with a broken marketplace DB. Clearing that along with everything else particl related, instead of just the marketplace DB, would have likely resulted in the '[object Object]' error, which is a different error (has been fixed as well).

I'm resolving this current logged issue - both of the reported items in this issue should now have been implemented/resolved.
