### ISSUE TITLE
Unable to publish sell listing

### ISSUE THREAD

**Issue by cleansanchez** [particl/particl-desktop#1207]
# Describe bug/issue

Upon trying to create an item for sale and clicking "update and publish", an unidentified [object Object] error appears at the bottom of the screen. The screen remains on the same "create an item" page. The error pops up again if update and publish is clicked again.

![marketsell](https://user-images.githubusercontent.com/44262926/47156851-b481d300-d333-11e8-97d6-bae0268a0034.jpg)

The listing has been created and can be viewed when selecting the "sell" page in left navigation column but remains unpublished. Nothing happens upon clicking publish from this page.

![marketsell2](https://user-images.githubusercontent.com/44262926/47157226-9a94c000-d334-11e8-9694-c1cbdc173588.jpg)

Additionally it seems that when clicking on the edit listing button, it does not remember the original selection for "listing expiration and fees" and always defaults back to 4 days even though 4 weeks was selected. Also multiple instances of the same original image now appear, I assume from multiple clicks on "publish" button. 

![marketsell3](https://user-images.githubusercontent.com/44262926/47157427-05de9200-d335-11e8-9de6-71d34522412f.jpg)

Changing the "listing expiration and fees" to 4 weeks again and selecting update doesn't provide any user feedback that anything happens but then when you exit that page and return back into the item, the value resets back to 4 days. Finally clicking "publish" from within the "edit item" page will cause the page to remain on "we're processing your listing" indefinitely, until you navigate away using the left panel.

![marketsell4](https://user-images.githubusercontent.com/44262926/47158367-3b847a80-d337-11e8-9310-e8a267c6c351.jpg)

Additionally the clone listing link takes you into what appears the edit screen for a cloned listing but upon selecting "publish" it will also cause the page to remain on "we're processing your listing" indefinitely, until you navigate away using the left panel. The clone listing is never created when navigating back to the sell items page.

# More information

- Operating system and version: Win10 Home
- Client version: 
Client 1.2.2-alpha-RC1
Market 0.0.45
Core 0.17.0.1

**Comment by zaSmilingIdiot** [comment]
The "[object Object]" error should now have been resolved.

**Comment by zaSmilingIdiot** [comment]
The resetting of the listing expiration field has also been resolved: the field is only relevant when posting/publishing the item onto the marketplace. The field has been removed from the _Add Listing_ window, and a value is prompted for now after the seller has selected the _Publish Listing_ button.

A couple of issues existed previously around saving a work-in-progress listing item for later editing and subsequent publishing. Work has gone into fixing these issues up, and so this should now be working correctly as well. This should apply to the clone listing as well.
