### ISSUE TITLE
Unable to checkout multiple items in shopping cart

### ISSUE THREAD

**Issue by cleansanchez** [particl/particl-desktop#1208]
# Describe bug/issue

In addition to experiencing the exact same behavior as logged in "Buggy Behavior When Checking Out #1200" by cryptoguard, I am also unable to checkout multiple items from the shopping cart. I have selected three items from the listings page and added them to the cart. I then go through the checkout process, receiving the same "TypeError" as mentioned above. 

![marketbuy2](https://user-images.githubusercontent.com/44262926/47160625-16ded180-d33c-11e8-9beb-a66ab9fe0b6f.jpg)

After not receiving any user feedback I click on the "orders" tab and only the first item appears in the list as bidding. The remaining two items do not appear. 

![marketbuy3](https://user-images.githubusercontent.com/44262926/47160856-8785ee00-d33c-11e8-8116-f934b42cae05.jpg)

All three items still exist in the "your cart" tab upon navigating back there. Continuing through the checkout process again will continue to only add the first item in the shopping cart list since it is not removed after checking out. 

![marketbuy4](https://user-images.githubusercontent.com/44262926/47161319-8d300380-d33d-11e8-8415-59450dde1d56.jpg)

# More information

- Operating system and version: Win10 Home
- Client version:

Client 1.2.2-alpha-RC1
Market 0.0.45
Core 0.17.0.1

**Comment by EagleEye25** [comment]
i have just tested this, while trying to checkout 3 items after unlocking the wallet, and proceding to checkout, it checked out 2 of the 3 items, then gave a message indicating not enough funds (total for items was around 25part, wallet had 60 part), while proceeding back to my cart i then checked out the item that didnt go through in the previous procedure and successfully checked it out

**Comment by EagleEye25** [comment]
tired to checkout more than 3 items, but didnt recieve a typeerror message, the gui just stopped responding, non of the listings went through

**Comment by EagleEye25** [comment]
just tried to checkout 3 items again.

I noticed that when you get prompted to enter your password to unlock your wallet, once you have entered your password and hit "enter"
that sometimes the dialog doesnt dissaper but the wallet becoms unlocked (windows 10 x64).

after trying to complete the order (with 3 / more items) the gui breaks and requires a restart for it to become functional again.

**Comment by zaSmilingIdiot** [comment]
The checkout process underwent significant testing and updates in early 2019. A large number of issues were fixed, including the underlying cause for the mentioned symptoms.

I am closing this issue due to age, and because the reported problem should now be resolved. However, if the problem persists with the latest releases, please don't hesitate to re-open the issue or log a new one.
