### ISSUE TITLE
Unable to pay for accepted bid

### ISSUE THREAD

**Issue by LiteBit** [particl/particl-desktop#1215]
# I get an object_Object error when trying to pay for an item in "Awaiting" 
I'm in the 3rd step of buying items. It's my turn with seller now "awaiting" the payment. When I go to pay I get an [object_Object] error.

# How to reproduce

![object_object](https://user-images.githubusercontent.com/6236019/47311104-dff01080-d606-11e8-88b0-90664b10e1eb.gif)

- Operating system and version:
-- Windows 10 x64
- Client version:
-- Community Build #1193

**Comment by zaSmilingIdiot** [comment]
This should now be resolved with a fix applied to the marketplace codebase.
