### ISSUE TITLE
Low Listing Image Resolution

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1236]
Some listing pictures appear low resolution while other images seem fine.

<img width="473" alt="screen shot 2018-11-09 at 1 29 53 pm" src="https://user-images.githubusercontent.com/27031337/48281106-9df70500-e423-11e8-8528-4fecae5fd4e3.png">

**Comment by HenkSwardt** [comment]
Adjustments made in the following PR should resolve this.

https://github.com/particl/particl-market/pull/341

**Comment by zaSmilingIdiot** [comment]
Just to clarify, not "resolve" the issue, but help to alleviate it.

The bigger problem of moving the images out of the messages still needs to be properly resolved before this issue can be resolved in its entirety.

**Comment by zaSmilingIdiot** [comment]
Has been resolved via changes in the Particl Marketplace repo, along with some changes in the desktop client.
