### ISSUE TITLE
Confirmations Not Updating in Real-Time (Overview Page)

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1237]
The confirmation count in Overview is not updating in real-time on MacOS 10.14

<img width="503" alt="screen shot 2018-11-09 at 1 31 30 pm" src="https://user-images.githubusercontent.com/27031337/48281317-34c3c180-e424-11e8-895e-6b153ab0d6b7.png">

Need to change tab to see the count go up.

**Comment by zaSmilingIdiot** [comment]
This has been checked and verified on multiple platforms, and is confirmed to be working.
