### ISSUE TITLE
[Suggestion] Allow Users to Cancel the Publishing of a Listing or Proposal Before 1 Confirmation

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1238]
Could be useful to have an option to cancel the publishing of a listing or proposal if there hasn't been a staked block between the moment you've submitted it and the moment you try to cancel it. 

Would be useful to quickly correct small mistakes or stuff like that. Not sure if feasible, but would be useful if possible.

**Comment by zaSmilingIdiot** [comment]
This is not currently possible.
