### ISSUE TITLE
Listing Flagging Confirmation Box Font

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1241]
I am not sure here, but the confirmation box for when flagging a listing appears to use a different font than the rest of the wallet. Is that the case (might just be of because it is displayed or sized). It does look a bit weird, can't quite put my finger on what if it's the same font. 

<img width="412" alt="screen shot 2018-11-09 at 1 27 38 pm" src="https://user-images.githubusercontent.com/27031337/48281825-d697de00-e425-11e8-83f8-6c55f1123a5e.png">

**Comment by zaSmilingIdiot** [comment]
Font type is the same. The font size is slightly larger than the default font size used in other places in the app. Which could be causing this to look slightly different.

@AllienWorks your thoughts?

**Comment by AllienWorks** [comment]
We're using 3 sizes of text for paragraph:
- `p.lead` - larger paragraphs; that's the one from the screenshot
- `p` - normal paragraph
- `p.widget-help` - smaller, grey help descriptions

Whoever was implementing this chose the largest one. You can just remove the class name, so it becomes the normal paragraph or just wait until I take care of it properly :)

**Comment by zaSmilingIdiot** [comment]
Fixed with a re-design of the modal.
