### ISSUE TITLE
Label When an Item is Shipped

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1242]
Currently, from the buyer's perspective, when an escrowed item ships, the Buy/Orders displays the order as "Shipping". 

<img width="702" alt="screen shot 2018-11-09 at 1 49 30 pm" src="https://user-images.githubusercontent.com/27031337/48281999-6fc6f480-e426-11e8-9e00-62ebce890dbb.png">

It might be better imo to display this as "Shipped" instead of "Shipping", because "Shipping" might imply the vendor is still packaging/processing the order and that it is in the "process of" shipping, whereas it is much clearer with "Shipped" that the item has actually left the vendor's location and is en route to the buyer.

**Comment by zaSmilingIdiot** [comment]
We now have an additional step in the CT "blinded" buyflow, which should clear any confusion up around this. This will making an appearance in the next testnet builds, as well as the v2.0.0-alpha mainnet release.
