### ISSUE TITLE
Displaying Completed Orders

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1244]
Currently, the UI seems to default to hiding completed orders in the Buy/Orders section. 

<img width="1440" alt="screen shot 2018-11-09 at 1 59 41 pm" src="https://user-images.githubusercontent.com/27031337/48282462-bec15980-e427-11e8-90a3-0653cd46f3e8.png">

Perhaps it would be a better behavior to uncheck "Hide completed" by default, and instead put completed orders at the bottom, under active orders (and in order of completion date). This would probably be a more intuitive behavior as I had to check for a few seconds until I found "Hide completed" was checked by default.

**Comment by zaSmilingIdiot** [comment]
We are currently in the process of updating the filters and sorting on the _Orders_ page(s). This can be discussed and added in as part of those changes.

Reference: https://particl.atlassian.net/browse/PD-367

**Comment by zaSmilingIdiot** [comment]
Included in https://github.com/particl/particl-desktop/pull/1272, the "Hide Completed" checkbox is now unchecked by default.

Filters and sorting of listings has also been included.
