### ISSUE TITLE
Add a Countdown to Display Amount of Time Before a Listing Expires

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1250]
This was proposed by @LiteBit on Telegram. 

Could be a cool idea to have a countdown or type of display that shows the amount of time left before a listing expires. This would probably have to be in Sell/Listings. For example, if you publish a listing for 14 days, would be cool to have maybe something like a percentage bar underneath the listing (in the Sell/Listings page) after it's published that would be halfway completed when the listing has been published for 7 days (on 14) already. This would only show up to the vendor that posted the listing itself and no one else.

**Comment by zaSmilingIdiot** [comment]
An expiry date has been added to the sellers page showing the date and time at which the published listings would expire.This was implemented in https://github.com/particl/particl-desktop/pull/1282

While its just a date representation, we could later include a progress bar of sorts as well. The date representation however, conveys the correct information immediately without the user needing to determine first what the bar represents (100% meaning that the listing is new or has expired?) or by making use of popup or hover text.

For interest, we've now included a warning regarding the expiry of listing items for the buyer as well: if the listing has less than a configured time period (currently 24 hours), then a warning indicator is displayed in the listing details view, as well as in the checkout process (cart view page) if the item has been added to the cart. This was implemented as part of both https://github.com/particl/particl-desktop/pull/1333 and https://github.com/particl/particl-desktop/pull/1318
