### ISSUE TITLE
Client doesn't update listings unless both DB and Chain are deleted (win10)

### ISSUE THREAD

**Issue by kasprrr** [particl/particl-desktop#1255]
# Describe bug/issue
Whenever i'm not testing a build for a week or two, it stops updating the listings and won't delete old listings that expired. When i install a new build and chain is synced again, nothing changes. The only way to fix the issue is to delete both the database AND the chain in order to make the new build work and show the current listings available. Deleting one or the other won't resolve the issue. Deleting the database will just give me an empty listing page, deleting the chain will make Particl Desktop keep the old (expired) listings even after syncing of chain is completed.

P.S. Network time synchronization is installed, however, i feel its not reliable enough for the Particl Desktop client to depend on as it sometimes fails to sync the time. I have seen this happen at least once.

# More information

- Operating system and version: Windows 10
- Client version: All testnet builds as well as the latest one sent to me by Cryptoguard: 0.0.45, 0.17.0.1, 1.2.2 alpha RC1

**Comment by zaSmilingIdiot** [comment]
This issue should now be resolved, as per the latest testnet release (v2.0.0-alpha1-testnet using particl-marketplace v0.0.69 and core v0.18.0.11).

If this persists, please don't hesitate to re-open this issue or log a new one.
