### ISSUE TITLE
Add the Possibility to Leave a Note to the Vendor 

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1260]
When ordering a product, would be useful to be able to leave a note to the vendor when you enter your address.

<img width="958" alt="screen shot 2018-11-14 at 11 56 20 pm" src="https://user-images.githubusercontent.com/27031337/48531135-f174b300-e868-11e8-89e3-327f013a1eab.png">

Could be used to give any information that might be useful to the vendor (i.e. specify a color, image, certain ID or username, etc)

**Comment by HenkSwardt** [comment]
Good day 

We had this discussion internally a couple of times, and came the the decision to not allow any messaging between buyer and seller as this could lead to a number of unwanted situations. 

As soon as we start adding QTY, Size, Color etc as part of Inventory management, it should allow the seller to define his listing in such a manner that there wont be need for any free form text areas. 

Hope this helps

**Comment by zaSmilingIdiot** [comment]
It should also be noted that a cart may contain items from a number of different sellers, and so this would mean allowing for a message per seller. I don't see this as being practical at this point in time.
