### ISSUE TITLE
Provide Both the Vendor and Buyer With a Transaction Number

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1261]
Transaction numbers are very important for both types of user. I would say it is an absolute requirement. 

<img width="697" alt="screen shot 2018-11-15 at 12 31 50 am" src="https://user-images.githubusercontent.com/27031337/48532348-0a339780-e86e-11e8-8b41-8fe85a640a33.png">

In the completed order above, there is no way to expand more details or even get some kind of link to the explorer. Because it is also impossible to highlight and copy-paste content, it can quickly become confusing or cumbersome to report an issue to a vendor or buyer.

**Comment by HenkSwardt** [comment]
Good day, 

We have an item in the backlog to add this feature. Please see : 

https://particl.atlassian.net/browse/PD-283

**Comment by zaSmilingIdiot** [comment]
The transaction link with the item order is something we can address as part of the previous ticket. 

Its just helpful to note that at this point in time, we have no means for the reporting of issues for recourse between buyer and seller (nothing related to this has been implemented as yet). Discussion around this is currently ongoing but no definitive plans have been decided on as yet.

**Comment by zaSmilingIdiot** [comment]
The escrow transaction ID has been added from v2.0.0 and should be available.

Closing this as the request is complete.
