### ISSUE TITLE
I can manipulate a public to public and blind to blind conversion in Send tab

### ISSUE THREAD

**Issue by kasprrr** [particl/particl-desktop#1274]
By clicking in the field slightly above or below the public/blind area, i can manipulate the UX to do a blind to blind or public to public conversion. See red dots in picture for public to public example, and click.. (just outside hyperlink area)

![tttttt](https://user-images.githubusercontent.com/37086658/48892317-2c9c5680-ee14-11e8-86b4-7e2b1c1c1400.jpg)

![f0bb0b71600dacfc6f608793ff51387d](https://user-images.githubusercontent.com/37086658/48892363-463d9e00-ee14-11e8-9207-2bacdabc21cd.png)

- Operating system and version: Win10
- Client version: 1.2.2 alpha RC1, 0.0.45, 0.17.0.1

**Comment by kasprrr** [comment]
i also can't do an anon to blind or visa versa conversion but i am not sure if this is intended.

**Comment by zaSmilingIdiot** [comment]
We do have a check in place that should prevent the actual conversion from taking place (an error is displayed if such a conversion from a particular type to the same type is attempted). However, this shouldn't be selectable, as you've demonstrated, in the application. We can definitely look at cleaning this up.

The anon to blind (and vice versa) type of conversions is known and a fix is currently in progress.

**Comment by zaSmilingIdiot** [comment]
This should now be fixed as per previous referenced merge.
