### ISSUE TITLE
Unable to checkout Particl Lapel Pin

### ISSUE THREAD

**Issue by cleansanchez** [particl/particl-desktop#1298]
# Describe bug/issue

I've gone through the process of selecting a lapel pin from the listings, ading it to cart and trying to check out but I get a typerror cannot readproperty 'id' of undefined and nothing happens.

![marketerror](https://user-images.githubusercontent.com/44262926/49497318-387c2400-f8bc-11e8-8313-f58ea5b1219e.jpg)

- Operating system and version: 

Windows 10 x64

- Client version: 

Client 1.2.2-20181128-alpha-RC1
Market 0.0.49
Core 0.17.0.1

**Comment by zaSmilingIdiot** [comment]
Can you perhaps include your marketplace log file?
It can be found in `AppData/Roaming/particl-market/testnet/` on Windows.

**Comment by zaSmilingIdiot** [comment]
Closing this due to age (without feedback), particularly given that significant amount of work has gone into related processing that would have changed the logic causing this particular error.
