### ISSUE TITLE
I Propose: Proposal Guidelines, Spam-prevention, Quorum, Lock-time

### ISSUE THREAD

**Issue by ghost** [particl/particl-desktop#1299]
I can think of a couple of expected outcomes from the Particl Desktop proposal system.

### 1. Number one issue: **SPAM:** - Shower-thoughts, unserious proposals, test-proposals.
When people with only 1 PART can "test" the proposals system, and spam it with things like

> "Should particl-community pump PART?"

Serious voters will have to use much more time to screen though the trash if only 1 in 10 proposals are serious or realistic. I think this is a huge problem if BETA is released without preventive measures for spam. I have been following Decred [DCR] who focus entirely on governance with Politeia https://proposals.decred.org and they have given me a couple of ideas which I think is important.

### Preventive measures: - My suggestions

**Proposal Guidelines**

- Follow the S.M.A.R.T principles (Specific, Measurable, Achievable, Realistic, Time-Bound) https://en.wikipedia.org/wiki/SMART_criteria 

- For example: Required Fields in a form: **What, Why, How, Who, When**. When people have to REALLY think before they post, then the spam could be decreased tenfolds.

- **People are dumb & careless:** Some people may use the proposal system like a bug-reporting platform instead of github. This should be specified on the proposals page.

- **"Who"** is very important information in a proposal. I doubt the Particl-team will have funds to hire people on the get-go who is responsible for a proposal that is accepted.

**Higher Requirement to submit proposal**

- I think it would be wise to either:
1. have a bigger fee to post proposals or 
2. require lock-up time of  staked funds to enable submittal of proposals.

**Categorization of proposals**

- It would be easier to see through the proposals you are interested in.

**Report/Downvote Proposals that are SPAM**
- I think this is important.

**Quorum (How much vote-weight needs to be required for a  voting to be valid?)**
- 5 PARTs voted YES, 3 PARTs voted NO is different from 500,000 PART for YES and 300,000 PART for NO. Should there be a requirement?

I fear that if this isn't addressed before BETA, then Particl can be spammed with a lot of bad proposals. Do you have a plan for this? Is it written somewhere? Can I contribute?

**Comment by ghost** [comment]
Governance is a complex thing that needs to be addressed carefully.

**Comment by AllienWorks** [comment]
I agree there with the fee for creating Proposals. We want to give anyone means of making their voice heard, but at the same time get rid of spammers and trolls.

Increasing the fee is something I'd like to see as well. If your Proposal is solid and you as its author believe in it, I think you won't have a problem spending ~10-20 €/$ (maybe even more).

For those who couldn't afford this, there are many other ways of proposing anything (forums, chats) and I believe if someone else finds your Proposal interesting and worth, they won't have a problem sponzoring the fee. I know I would.

---

Btw @real-rouse thanks for the suggestion, but I believe that this topic is better suited for the [forums](https://particl.community) we have online. That's for the future :)

**Comment by ghost** [comment]
> I agree there with the fee for creating Proposals. We want to give anyone means of making their voice heard, but at the same time get rid of spammers and trolls.
> 
> Increasing the fee is something I'd like to see as well. If your Proposal is solid and you as its author believe in it, I think you won't have a problem spending ~10-20 €/$ (maybe even more).
> 
> For those who couldn't afford this, there are many other ways of proposing anything (forums, chats) and I believe if someone else finds your Proposal interesting and worth, they won't have a problem sponzoring the fee. I know I would.
> 
> Btw @real-rouse thanks for the suggestion, but I believe that this topic is better suited for the [forums](https://particl.community) we have online. That's for the future :)

woops, sorry. Should I remove it from here and make a new topic at particl.community?

**Comment by AllienWorks** [comment]
Don't worry. I think we can keep it here for future reference. But yes, copy it over to forums definitely, so the discussion can start.

**Comment by zaSmilingIdiot** [comment]
Proposals are moving out of the application (not included in v3.0 at least initially, for their original purpose and usage) and instead should be available going forward as a part of: https://ccs.particl.io/

See also https://github.com/particl/ccs-proposals
