### ISSUE TITLE
Cannot See the Complete Address from Customers

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1303]
Trying to process lapel pin orders, and cannot see the full addresses of customers in the little display. I can access the full addresses in the debug window with some SMSG command, but not from the GUI itself. This happens when an address line is too long, it just ends with ... 

![2018-12-04 14 54 47](https://user-images.githubusercontent.com/27031337/49563381-b278d100-f8ed-11e8-80e8-f96d09e17a68.jpg)

The address above has been blurred. 

Here how it looks at the end of a line that's too long: 
<img width="184" alt="screen shot 2018-12-04 at 2 57 12 pm" src="https://user-images.githubusercontent.com/27031337/49563404-c02e5680-f8ed-11e8-93b3-41d077fbc260.png">

**Comment by HenkSwardt** [comment]
This issue is being looked at in

https://particl.atlassian.net/browse/PD-497

**Comment by zaSmilingIdiot** [comment]
This fix will be available in the next release build.
