### ISSUE TITLE
particl-desktop-1.2.2-20181128-alpha-RC1-win-x64 unable to click 'Accept terms'

### ISSUE THREAD

**Issue by ezoer** [particl/particl-desktop#1307]
# Describe bug/issue

When starting Particl Desktop, I'm prompted to click Accept or Decline and Close. The Accept button remains greyed out even if I'm scrolling to the end of the terms and conditions. See image:

![49606261-2a4d0700-f993-11e8-95b4-888277c4f966](https://user-images.githubusercontent.com/2060048/49668237-d0654380-fa5d-11e8-9b11-4c21a18ab239.png)

# How to reproduce

1. Extract Particl Desktop to a folder of your choice
2. Start Particl Desktop by double-clicking the executable 'Particl Desktop.exe'

# More information

- Operating system and version: Windows 10 version 1803 (OS Build 17134.407)
- Client version: 1.2.2-20181128-alpha-RC1-win-x64

**Comment by zaSmilingIdiot** [comment]
Thanks for mentioning this. We are busy investigating.

**Comment by HenkSwardt** [comment]
This should be resolved in the following PR and should be available in the next oublic build. 

https://github.com/particl/particl-desktop/pull/1314
