### ISSUE TITLE
Fedora (.rpm) packages

### ISSUE THREAD

**Issue by heyakyra** [particl/particl-desktop#1379]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue
Need rpm to install on fedora 29/30
..

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. ..try to download
2. ..cry

# More information

- Operating system and version:
- Client version:

**Comment by zaSmilingIdiot** [comment]
Although we do not provide a .rpm package, we do typically build a .zip file for linux based environments.
See [here](https://github.com/particl/particl-desktop/releases) for an example of our official builds.

Requires a simple case of:
- extracting the zip file to any location;
- ensuring that the extracted 'Particl Desktop' file is executable;
- executing the 'Particl Desktop' file

Out of interest, I use Fedora for most of my systems (primary workstation included) and so yes, its definitely possible to run the desktop client on Fedora. We can look at providing an rpm package in the future if there is enough interest in doing so.

**Comment by zaSmilingIdiot** [comment]
Just wanting to mention that starting from the v2 releases, an rpm package is now included. See for example: https://github.com/particl/particl-desktop/releases/tag/v2.0.0-alpha
