### ISSUE TITLE
Cross-platform flatpak builds

### ISSUE THREAD

**Issue by heyakyra** [particl/particl-desktop#1380]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue

..To avoid distro-specific or OS specifi builds, flatpak could be focused on instead

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. ..look for build for obscure OS
2. ..keep looking

# More information

- Operating system and version:
- Client version:

**Comment by kewde** [comment]
electron-builder supports the [AppImage](https://appimage.org/) format which would be cross platform.

**Comment by zaSmilingIdiot** [comment]
AppImage builds now provided as from v3.0.0
