### ISSUE TITLE
Vendor flow interrupted because of unlock wallet pop-up

### ISSUE THREAD

**Issue by michmish** [particl/particl-desktop#1408]
# Describe bug/issue

(Picture was deposited on telegram/testing, can't upload it right now)

If i click on unlock wallet. (Blue "wallet unlocked" appear left bottom) but the pop up doesn't disapear after the click. and the "accept bid" action is not automatic right after click on "unlock wallet"

# How to reproduce

Step 1 : click accept bid 
*unlock wallet appear*
Step 2 : password + unlock wallet
*feels like nothing is happenning but if you watch carrefully you see that the wallet is unlocked but pop up is still here*
Step 3 : you have to manually close pop up by clicking "cancel" on pop-up

# More information

Vendor flow (accept bid) has the bug not the buyer flow (bidding)

- Operating system and version: x64 windows
- Client version:  alpha community build

**Comment by HenkSwardt** [comment]
Thank you for logging this. corresponding development task:

https://particl.atlassian.net/browse/PBD-211

**Comment by zaSmilingIdiot** [comment]
This should be resolved by both of the following 2 changes:
https://github.com/particl/particl-desktop/pull/1463
https://github.com/particl/particl-desktop/pull/1464

The fix should then be included in the next release.
