### ISSUE TITLE
Adjust height on display listing popup

### ISSUE THREAD

**Issue by LiteBit** [particl/particl-desktop#1410]
# Improve information displayed on default view of listing popup

here's the default view of a listing popup. 
![image](https://user-images.githubusercontent.com/6236019/52350996-c3ca8080-29f7-11e9-8ca4-3b237fd92cc3.png)

It looks great but could have a larger height parameter so that it displays the header bar of the table below. Something like this:
![image](https://user-images.githubusercontent.com/6236019/52351064-f5dbe280-29f7-11e9-8992-f6c08750dd3b.png)

When you go full screen mode you see the table header and more below, but the default view settings (non-full screen mode) the header bar is cropped and it would be good to see it so viewers are enticed to scroll down for more info. 

It'd also frame it nicely imho.

**Comment by AllienWorks** [comment]
This has been already fixed.
