### ISSUE TITLE
View > Reload causes app to go to a whitescreen

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1411]
Win64 build on Windows 10 machine. I right-clicked on the Particl icon and saw the options "View, Window, Help". I hovered over View and then clicked Reload. When I did that my main Particl Desktop screen went all white and did not seem to actually reload.

Restarting the app put everything back to normal.

**Comment by zaSmilingIdiot** [comment]
Thanks for reporting this. Will try to replicate and determine the cause of the issue.

**Comment by HenkSwardt** [comment]
This has been logged for investigation. https://particl.atlassian.net/browse/PBD-219

**Comment by zaSmilingIdiot** [comment]
For now, we've removed the 'Reload' option from the menu.
