### ISSUE TITLE
Orders indicator

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1412]
I really like the indicator next to Sell on the left-side bar. Can we have this indicator duplicated on the Orders tab as well to more clearly indicate the number of Orders that currently need attention?

![image](https://user-images.githubusercontent.com/38863166/52358268-4f92db80-29fd-11e9-9526-4b7acf00a4c2.png)

**Comment by michmish** [comment]
I had the same user intuition and i think it would be an awesome improvement to help find "order" category

**Comment by AllienWorks** [comment]
We already experimented with this, but there was an issue with "jumping layout" (as it takes some time to load it) + something else. In the end, we decided not to implement it.

We could look into some other elegant way how to solve this in the future.

**Comment by PARTimprovert** [comment]
pls do this.....

**Comment by zaSmilingIdiot** [comment]
Has been implemented in v2.2.0.
