### ISSUE TITLE
Duplicate bids didn't get passed back to Buyer after seller accepted/rejected

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1413]
I bid twice on a single listing. A few hours later the seller accepted one bid and rejected the other (he said). Then the next day, I open the app and both of my bids are still in the "Bidding" state. It seems the accept/reject state changes did not make it back to my instance of the app, or something about 2 bids on the same item caused some confusion. 

Let me know if there is more data/info you need from me regarding this issue.

**Comment by EagleEye25** [comment]
This is related to #1421

**Comment by HenkSwardt** [comment]
Hi @CryptoBeans 

This is a known bug being worked on in https://github.com/particl/particl-desktop/pull/1402

As we dont support multiple sales between single buyer and seller on the same item at the moment (Please see https://github.com/particl/particl-desktop/issues/1421), we will need to disable the add to cart button as soon as the buyer has the item in his cart. This should prevent this from happening. 

Thank you

**Comment by HenkSwardt** [comment]
Relating Jira log. https://particl.atlassian.net/browse/PBD-202

**Comment by michmish** [comment]
I was the seller i can add an info because i think this was the main issue :
I saw that i had 2 bid coming from cryptobeans (same address)
I rejected the first listing.
I then accepted the bid on the 2nd listing

Cryptobeans didn't receive any confirmation of the acceptance of his bid (even if it's the 2nd one).

What you are telling us is that if i tried to do the opposit (fist accept then reject) cryptobeans would have get a success notification ?

**Comment by HenkSwardt** [comment]
No, at the moment we dont cater for multiple bids on the same item(Between the same seller and buyer) at all. As soon as you receive this any further interaction will not be sent. That is the reason we are preventing tit for the time being, but will include the ability to do so in a future release.

**Comment by zaSmilingIdiot** [comment]
The discussion on the ability to bid on multiple items should continue in https://github.com/particl/particl-desktop/issues/1421 In addition the ability to bid on multiple items at the same time has been updated.

I'm closing this as there is nothing further outstanding in this particular issue.
