### ISSUE TITLE
Items listed at less than one Partoshi are converted to 0 cost

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1414]
I listed an item for .000000001 PART (one tenth of the lowest possible decimal) and it appears to have published as costing 0.

I think the UI should limit the cost field to 8 decimal points and block you from posting if you try to put in a number with further decimals.

**Comment by zaSmilingIdiot** [comment]
Thanks for finding this. You are indeed correct, and numeric currency input fields should be restricted to the  maximum number of supported decimal places.

**Comment by HenkSwardt** [comment]
Issue has been logged for investigation.

https://particl.atlassian.net/browse/PBD-217

**Comment by zaSmilingIdiot** [comment]
Has been fixed, and is included in the next development testnet release.
