### ISSUE TITLE
One Partoshi cost item is not displaying correctly

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1415]
I listed an item for .00000001 PART. The first image is from the listings page: I can see the cost is 1e-8 which is technically correct but not pleasant to see. However, upon clicking the item (second image) it displays a cost of 0 rather than the correct amount. 

![image](https://user-images.githubusercontent.com/38863166/52360254-34c26600-2a01-11e9-8440-31248315454e.png)

![image](https://user-images.githubusercontent.com/38863166/52360293-43a91880-2a01-11e9-87c4-824af79eae5c.png)

**Comment by zaSmilingIdiot** [comment]
Thanks for finding this.

**Comment by HenkSwardt** [comment]
This has been logged for investigation. https://particl.atlassian.net/browse/PBD-217

**Comment by zaSmilingIdiot** [comment]
Has been fixed, and is included in the next development testnet release.
