### ISSUE TITLE
Escrow display is showing total amount rather than my amount

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1416]
In the image, you can see that in my history there is a -9 PART shown as a Multisig/Escrow transaction. However, I only put in 3 of the PART whereas the buyer put in 6 (see lower part of image for tx info).

Shouldn't my history display this as -3 rather than -9 because it was 3 that left my wallet and not 9? 

You can see that the escrow-release above the -9 is correctly showing that I received 5.999 PART back from the escrow. So it looks weird/confusing because -9 then +6 implies a final -3 even though I am now +3 PART for doing a sale.

![image](https://user-images.githubusercontent.com/38863166/52361420-d77be400-2a03-11e9-8580-334ba76bf719.png)

**Comment by rynomster** [comment]
We're you by any chance the buyer and the seller?

**Comment by HenkSwardt** [comment]
Hello @CryptoBeans 

We are in the process of seeing if we can better display this in the GUI. At the moment, being a Multisig/Escrow transaction it reflects the total transaction for both parties involved.  This request came through to us yesterday as well. 

Bering looked at in the following task https://particl.atlassian.net/browse/PBD-216

Thank you

**Comment by zaSmilingIdiot** [comment]
All fixed up - the next build will include this update.
