### ISSUE TITLE
Particl not working correctly through the .deb installer

### ISSUE THREAD

**Issue by SativaL** [particl/particl-desktop#1418]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue
when you install particl via the .deb installer and then search and run it, does not work because there is a error message coming up saying particl not found in folder /opt/particl. Something is wrong there.. 
..

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. ..
2. ..

# More information

- Operating system and version: ubuntu 18.04
- Client version: testnet build latest

**Comment by zaSmilingIdiot** [comment]
We've had an internal report of the deb installer not working correctly as well, but for different reasons. Testing of this needs to be finalized. In the interim, you could perhaps use the Linux .zip file if you would like to continue with the testing.

**Comment by HenkSwardt** [comment]
This has been logged for investigation. https://particl.atlassian.net/browse/PBD-218

**Comment by zaSmilingIdiot** [comment]
This has been fixed - the next build will have the deb installer using the correct paths when launched via the GUI.
