### ISSUE TITLE
Flagged items continue to show on my List

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1419]
I flagged an item and it continues to be in my Listings list.

I clicked the button to show only flagged items, I saw the one I flagged as well as one someone else flagged. I clicked that one and added my flag-weight to it.

But when going back to main list of listings, both of those flagged listings are still there.

The ONLY way you should be able to see flagged listings is if you clicked the "Show flagged listings only" button.

**Comment by HenkSwardt** [comment]
Hello @CryptoBeans 

Thank you for the testing effort on the GUI. Really appreciated. 

What you are seeing is the correct behavior, all items will stay listed until the threshold for removal has been reached. The "View Flagged Items" filter is to assist people that would like to moderate with a quick overview of all flagged items. 

Currently the threshold is set at 10% Market weight. Once the item reached this, it will be removed from the MP completely.

**Comment by zaSmilingIdiot** [comment]
Closing as 'working as expected'.

**Comment by CryptoBeans** [comment]
@zaSmilingIdiot I think it would be a good idea to filter out items that the user has themselves voted as inappropriate so at least they do not have to see it. This would make it much easier for people to "clean up" the listings when they are giving a demo of the project for example.

**Comment by zaSmilingIdiot** [comment]
Good suggestion. This can be addressed as a feature request.

**Comment by zaSmilingIdiot** [comment]
Has been included and can be used as per at least the Particl Desktop v2.0.0-alpha1-testnet version. Which will make its way into the first particl-market mainnet release.

**Comment by CryptoBeans** [comment]
@zaSmilingIdiot Are you sure this was included in the alpha1 release? Flagged items are not disappearing for me, and others in the testing chat have reported the same thing.

**Comment by zaSmilingIdiot** [comment]
The functionality has been included, which was the origin nature of this request. The current build does contain a bug that prevents it from working correctly in certain cases. Which is technically deserving of a new issue being logged, which can be labelled appropriately as a bug.
