### ISSUE TITLE
I can't buy the same listing a second time

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1421]
CryptoGuard and I did a full sell flow where I bought one of his listings (escrow completed).

The next day, I went to buy it again. The "Add to cart" link is no longer on that listing. 

Shouldn't I be able to buy it a second time? 

It appears that my listings are able to be bought by multiple other people so then why can't I as the buyer buy the same listing numerous times?

**Comment by EagleEye25** [comment]
Currently particl doesn't support purchasing the same item twice, this would be in a feature release

**Comment by HenkSwardt** [comment]
Hi @CryptoBeans 

As per the comment made by @EagleEye25, unfortunately we don't support this at the moment. This will be added as part of the inventory management where we will have a better idea of how many items are up for sale.

**Comment by CryptoBeans** [comment]
@HenkSwardt I saw that you bid on my Hot Peppers listing and I Accepted it. However, CryptoGuard had already bought it the day before (and completed the full buy flow). Does that mean my Accept message never got passed back to your client?

I think this could be bad for Sellers if they receive lots of buy orders and try to accept more than one. Perhaps the UI could hide/block later bids after a listing has been bought? (for now, until inventory management is built)

**Comment by HenkSwardt** [comment]
Hi @CryptoBeans 

The other orders should not be prevented from going through at all. 

Unfortunately, I will not be able to test this with you as I had to clear my DB for other tests. I will however asks the guys to confirm that this specific scenario does not happen. But from past tests I do recall that it does not

**Comment by zaSmilingIdiot** [comment]
For v3.0.0, its not possible to add the same item to the cart concurrently, but subsequent purchases of the same item are possible.

**Comment by zaSmilingIdiot** [comment]
Implemented in release v3.0.0
