### ISSUE TITLE
Item Description looks off

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1427]
See image, look at how the last 3 words of the description get cut and moved up. 

![image](https://user-images.githubusercontent.com/38863166/52436215-542cc200-2ad9-11e9-8d8d-71a7e2b2c94c.png)

**Comment by zaSmilingIdiot** [comment]
The idea here was to implement the description in a 2 column layout.

This is being changes back to a more regular layout, along with some other design tweaks. These specific updates are being implemented in https://github.com/particl/particl-desktop/pull/1417

**Comment by zaSmilingIdiot** [comment]
Fix has been implemented, and will be included in the next release.
