### ISSUE TITLE
Converting to Blind/Anon error message is not entirely user-friendly

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1429]
See Image, the error message has some programmer-speak mixed in. I think the end user should only see something like "Insufficient Funds, try converting a lesser amount" while the extra stuff could go to a debug log for later analysis if needed.

![image](https://user-images.githubusercontent.com/38863166/52436762-b934e780-2ada-11e9-9396-ade37ad79390.png)

**Comment by zaSmilingIdiot** [comment]
This has been fixed, which should be included in the next build/release.
