### ISSUE TITLE
Proposal word-wrap is splitting words

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1436]
I noticed on someone else's proposal that words are being split in the word-wrap.

If there's a **word-break: break-all;** or similar in the styling, it could be changed to **word-break: break-word;**

![image](https://user-images.githubusercontent.com/38863166/52498702-1e521100-2b9f-11e9-9ef1-e384a5c996b7.png)

**Comment by HenkSwardt** [comment]
Thank you for reporting this, we have logged an issue to investigate and resolve:

https://particl.atlassian.net/browse/PBD-224

**Comment by zaSmilingIdiot** [comment]
Fixed, and should be included in the next release.
