### ISSUE TITLE
Un-favoriting item from Favorites page doesn't remove it initially

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1437]
Extremely minor enhancement:

If I go to my Favorites page and click the Heart icon on a listing, it gives me the Toast message that the item is Removed from my favorites. However, the item stays on the Favorites page until I actually go to a different page and come back. Considering how things work on other pages (where things always update upon change) I think it would be consistent to remove that item from the list immediately upon de-favoriting.

**Comment by HenkSwardt** [comment]
Thank you for logging this, we have logged an issue to investigate and resolve:

https://particl.atlassian.net/browse/PBD-225

**Comment by zaSmilingIdiot** [comment]
This has been resolved, and the fix will be included in the next development testnet release.
