### ISSUE TITLE
Desktop: Make version information copy to clipboard

### ISSUE THREAD

**Issue by DrDBanner** [particl/particl-desktop#1439]
In the bottom left corner information are helpful. They would even be more helpful if they could be taken to the clipboard

[FEATURE REQUEST]

**Comment by zaSmilingIdiot** [comment]
The version information section has been updated, and is thus now selectable. Selecting the text and then hitting `Ctrl(or Cmd if on Mac) + C` should copy the version information to your clipboard. 

This change will be included in all of the future mainnet/testnet releases.

**Comment by DrDBanner** [comment]
I can select it with the new build but CMD + C doesn`t fill the Clipboard.  

MacOS: 10.14.4
Client: 2.0.0-testnet20190411

**Comment by zaSmilingIdiot** [comment]
Re-opening for updated testing on MacOS

**Comment by zaSmilingIdiot** [comment]
@vikas-cis Can you perhaps test the copy-paste action of the version information (as displayed in the sidebar of the desktop app) please?

**Comment by vikas-cis-zz** [comment]
Hye @zaSmilingIdiot sure 

Thanks

**Comment by zaSmilingIdiot** [comment]
Update on this: it looks like Mac builds don't have the default copy/paste shortcuts enabled when building via electron. There are a couple of "workarounds" that we are looking into, so should have this fixed up shortly.

**Comment by zaSmilingIdiot** [comment]
The Mac related shortcuts not working seem to have already been reported in https://github.com/particl/particl-desktop/issues/1251

I'm going to close this issue then as the version information is now selectable, but the Mac specific issue can be tracked further in the above mentioned ticket.
