### ISSUE TITLE
MP: "view cart" and "favourites" in top bar

### ISSUE THREAD

**Issue by DrDBanner** [particl/particl-desktop#1440]
Put "view cart" and "favourites" (to be added) into top bar and make them only visible if "marketplace" module is active. 

Put "Balances" into it as soon "Wallet" module is active.

Put "Own proposal Count" and "Personal Vote stats" into it if "Proposals" module is active

# More information

- Client version: Alpha 2.0.0

**Comment by HenkSwardt** [comment]
Good day, 

Thank you for logging this. We aere actually talking about a similar enhancement earlier today and will add this link to it. 

Logged as part of : https://particl.atlassian.net/browse/PBD-226

**Comment by zaSmilingIdiot** [comment]
No longer applicable as of v3.0.0
