### ISSUE TITLE
MP: Top left logo link

### ISSUE THREAD

**Issue by DrDBanner** [particl/particl-desktop#1441]
Click on top left Particl icon should open "Help & Support" module or "Overview" ... choose yourself 

# More information

- Operating system and version: All
- Client version: Alpha 2.0.0

**Comment by DrDBanner** [comment]
Can be closed I guess due the „holdings peek“ on hover function?

**Comment by zaSmilingIdiot** [comment]
Yep, thanks for mentioning :) I'll close this now
