### ISSUE TITLE
"Setsetting failed" when trying to activate cold staking - and some other errors

### ISSUE THREAD

**Issue by jannesalovaara** [particl/particl-desktop#1445]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue
I'm trying to activate cold staking, specifically to a cold staking pool. 
Whether I first unlock the wallet or let the cold staking process do it, I get a "Setsetting failed" error. The error window seems to freeze to front ground and all I can do is to quit the program. 
Have tried it now several times, with the same error as a result. 
..

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. Start up client. My client, since I think this build, has had the startup problem where the program says Particl is already running. If I click yes, it seems to get stuck on connecting to network and never picks up the signal. If I click "no" at least it connects and I seem to have constant 16 peers connected. 
2. I unlock the wallet. 
3. I click activate cold staking. Paste the pool address. Click activate and get the error message: (something like cold staking couldn't be activated "Setsetting error". After this the error message stays on top and there's nothing I can do but to quit the program. 
4. I think since the connection error started, I've also noticed that if I just click the program shut from top-right corner it actually stay open in the background. I have to search for the icon from taskbar's hidden icons and close it from there. 

# More information

- Operating system and version: Windows 10 Pro, 64-bit, version 1809 on Surface Book (1st gen)
- Client version: 1.3.0

**Comment by jannesalovaara** [comment]
I did the whole "start from scratch" thing. And it seems like the app now starts and closes proper: no already running error and closing the app fully closes it. BUT: 
The SetSetting Failed error remains the same. No cold staking still. I'm baffled.

**Comment by jannesalovaara** [comment]
Somethings that I found from dev mode:
Failed to load resource: the server responded with a status of 500 (Internal server error) 
Object
  code: -4
  message "SetSetting failed" 

Unfortunately, there seems to be nothing about SetSetting Failed in the debug log.

**Comment by jannesalovaara** [comment]
Also this error message keeps repeating in dev mode: 
Failed to load resource: the server responded with a status of 500 (Internal server error) localhost:51735
ERROR Object 
  code: -28
  message: "Rescanning..."
defaultErrorLogger @ vendor.bundle.js:29683

**Comment by jannesalovaara** [comment]
hmmmm... there seems to be something truly odd going on with my wallet: 
i cant seem to delete addresses from my address book. and if i add new ones, it saves them in a very very very weird form. f.ex. this address: pcs1vzuadmp42slqapdm8eevm6g8ntm3hlvgptmyjy when saved, becomes: 3QJmnh

**Comment by jannesalovaara** [comment]
Found this on the db.log:

file wallet.dat has LSN 1/22287, past end of log at 1/476
Commonly caused by moving a database from one database environment
to another without clearing the database LSNs, or by removing all of
the log files from a database environment
DB_ENV->log_flush: LSN of 1/22287 past current end-of-log of 1/476
Database environment corrupt; the wrong log files may have been removed or incompatible database files imported from another environment
PANIC: DB_RUNRECOVERY: Fatal error, run database recovery
wallet.dat: unable to flush page: 5
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery
PANIC: fatal region error detected; run recovery

**Comment by zaSmilingIdiot** [comment]
We have a newer desktop version releasing soon -> v1.3.1 Its in pre-release currently, but should be hitting release soon.

In the meanwhile, it seems that the wallet restoration does not appear to have been completed successfully. Do you have the mnemonic for the wallet? If so, it might be better to backup your wallet.dat file (just in case), then start completely fresh (without copying in your wallet.dat file), and restoring your wallet via the desktop using the mnemonic.

**Comment by jannesalovaara** [comment]
Yeah.. Unfortunately I seem to have mysteriously saved a pass phrase that's linked to a completely different wallet. I have no idea how this has happened. 
Anyhow, I found an older copy of the wallet.dat file which seemed to work with the 1.3.0 desktop. So using that wallet, I got to send my tiny stake to a cold staking pool.

**Comment by zaSmilingIdiot** [comment]
@jannesalovaara Is the problem still occurring? Are you running the latest wallet version?

**Comment by jannesalovaara** [comment]
The problem disappeared as I dug up an old copy of the wallet.dat file. Unfortunately, it reappeared as my computer crashed once with the app on. So it seems like one crash will just mess up the wallet file. But yes, while it was working I got to zap my small bag to a cold stake pool. Thanks!
