### ISSUE TITLE
Blind Balance shows warning but does not show amount

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1446]
I converted 20 PART to Blind, then after a few days I converted them back to public. I now see a warning/info box in the Blind section, but I do not see the actual amount anymore. See second picture for what my Blind balance actually is and should be reflected as such in the UI (even if it is miniscule)

![image](https://user-images.githubusercontent.com/38863166/52589905-9de11980-2e05-11e9-9d8a-50ef85006a96.png)
![image](https://user-images.githubusercontent.com/38863166/52590016-eac4f000-2e05-11e9-9bdb-f91fc9f3c895.png)

**Comment by zaSmilingIdiot** [comment]
This should now be fixed in the next build.
