### ISSUE TITLE
MP: Add extensive escrow explanation 

### ISSUE THREAD

**Issue by DrDBanner** [particl/particl-desktop#1498]
# Describe bug/issue

### UX improvement

If a user is unaware of the Particl Marketplace mechanics he/she will get a hard time to get why the total price for an order is significantly higher than the asking price. 

It is wise to have a short explanation within the "Shipping&Escrow" tab (and all other occurrences of escrow) and add a link to an extensive explanation with some attempts to convince why this approach is safe and cheap even if it does not look like at the first sight and examples of meaning.

That way the user gets the point with education and may not get off turned that hard.

# More information

- Operating system and version: all
- Client version: 2.0.0-alpha-testnet

**Comment by zaSmilingIdiot** [comment]
Thanks for raising this. While we could probably add some explanation as to the reasons for this, I believe that whichever channel that a potential user hears about the marketplace would likely have an explanation of how the marketplace works.

One thing that we do have to consider is that we don't want to provide unnecessary "noise" once someone knows what/how the escrow system works. To that extent, we could perhaps add a "help" link where applicable, that points to a reference of how the escrow implementation works. That way, relevant information is available for those that require it, without cluttering the space once that knowledge has been obtained.

@HenkSwardt thoughts for feature inclusion?

**Comment by HenkSwardt** [comment]
I like the Help Link yes, @AllienWorks is busy working on the Wiki with the Community that will be helpful explaining these.

We have a little bit up on here already : https://particl.wiki/faq#general_questions (https://particl.wiki/faq_marketplace#how_does_the_escrow_system_functions, https://particl.wiki/faq_marketplace#what_is_the_fee_for_using_the_escrow_system)

But I do believe this can be updated to a more extensive document.

**Comment by AllienWorks** [comment]
> It is wise to have a short explanation within the "Shipping&Escrow" tab

Agreed. So far we have just this short explanation, but all of these will be enhanced with "learn more" links to Wiki as Henk wrote:

![Screenshot from 2019-03-21 12-10-56](https://user-images.githubusercontent.com/1965795/54748655-89e1c200-4bd2-11e9-97c7-f050b34b14da.png)

**Comment by zaSmilingIdiot** [comment]
Additional information has been added to v3.0.0
