### ISSUE TITLE
.deb installer doesnt create Desktop Shortcut or start menu entry

### ISSUE THREAD

**Issue by SativaL** [particl/particl-desktop#150]
after installing the ".deb" installer doesnt create Desktop Shortcut or start menu entry on 

NAME="Linux Mint"
VERSION="18.2 (Sonya)"

**Comment by allienworks** [comment]
@SativaL Is this still the issue with the 1.0 release?

**Comment by SativaL** [comment]
yes still doesnt work, i can install it, then it says everything installed okay, but i cant find any shortcut icon in menu entry or on the desktop, cant even find the particl folder (its like its installing nothing). So if it would be possible to add shortcut with particl icon people would just click on it.

**Comment by pciavald** [comment]
@rynomster are the desktop shortcut / menus being correctly created on your side ?

**Comment by kewde** [comment]
Hmm, it should generate a desktop file tho.

https://github.com/electron-userland/electron-builder/blob/master/docs/configuration/linux.md

https://github.com/particl/particl-desktop/blob/54ce6e11f82585224768aa799ef4f8038d988002/package.json#L120-L130

Need to check our keys but it seems to me that they are fine.
```
However, the keys are case sensitive. Type=Application is not the same as type=Application or TYPE=Application. 
```

**Comment by pciavald** [comment]
@HenkSwardt can we assign someone to test this ? See if its still a bug

**Comment by anandsinghparihar** [comment]
I can't see shortcut & if I open wallet using command line App icon is also not display!
![icon also not display](https://user-images.githubusercontent.com/17725557/35970820-c26dbe7e-0cf1-11e8-88a1-87ae3d35ab17.png)

**Comment by SativaL** [comment]
seems to be fixed in latest build

1.4 i have now a shortcut + a smaller one in my favorites 

ubuntu 64 bit
