### ISSUE TITLE
Expired Listing Still Shows on Sell Tab

### ISSUE THREAD

**Issue by joefiorello** [particl/particl-desktop#1502]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue
My listing expired yesterday, but still shows as published and is still in my sell tab.
..

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. ..
2. ..

# More information

- Operating system and version: Windows 10
- Client version: 2.0.0-aplha-testnet

**Comment by zaSmilingIdiot** [comment]
Thanks for mentioning this.
A fix for this has been added already in the primary development branch, as per https://github.com/particl/particl-desktop/pull/1451
This change never made it to the current alpha release build as we have been accepting only bug fixes and changes that improve stability. Hence no additional new features. It will however, definitely be a feature in the beta releases of the application.

**Comment by zaSmilingIdiot** [comment]
The change as mentioned above has now been merged into the current build, and will be available in the next release.
