### ISSUE TITLE
Marketplace listing details/escrow/comments section not conspicuous enough for new users

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1553]
As a new user, when i open an item on your marketplace, the details/comment/escrow/ section seems hidden. Its very difficult to find, rather it should be visible and conspicuous immediately. The scroll bar is very thin, making it extra hard to see/discover when your app is opened in its default size. I think this is a major UX issue that needs attention.

![part issue1](https://user-images.githubusercontent.com/49277632/55556566-8134d400-571a-11e9-95ce-7c94fa31dd9d.jpg)

**Comment by zaSmilingIdiot** [comment]
This has already been reported in https://github.com/particl/particl-desktop/issues/1410
