### ISSUE TITLE
"quote" on startup screen sometimes displayed sometimes not (minor)

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1555]
Very minor, but sometimes the starting screen shows the Particl logo including "to hide the signal, there must be noise" quote. Other times it just displays the logo without quote. 

Latest Alpha, win10.

**Comment by zaSmilingIdiot** [comment]
The startup page has been updated with the introduction of the multi-wallets feature, which will be included as part of the next (testnet) test release build, as well as the first mainnet release.

I'm closing this as this issue should no longer be applicable with the next release versions.
