### ISSUE TITLE
"No transactions yet" not displayed when opening Particl desktop, "recent transactions" loop keeps going..

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1556]
Whenever there are no transactions yet, my particl desktop keeps loading transactions (showed by the loading animation on the home screen). It just keeps looking for them and doesn't stop even when the deamon is loaded and all screens show up in the menu. It will also keep displaying the text "Recent transactions" instead of "No Transactions found"

This changes whenever i navigate somewhere else and go back to the overview page, now it displays "No transactions yet". If there are no transactions found after opening the client, it should immediately display "No transactions yet" instead of showing the animation going in a loop.

Alpha 2.0.0
Win10

**Comment by zaSmilingIdiot** [comment]
Hi. When the menu options have loaded, does clicking on another menu option, and then back to the 'Overview' page resolve the issue? If so, this is known and has already been resolved as of the latest codebase (ie: future releases will include the fix already in it).

**Comment by PARTimprovert** [comment]
correct

**Comment by zaSmilingIdiot** [comment]
I'm closing this issue as it has already been identified and fixed.
