### ISSUE TITLE
"All seller countries" filter icon not very helpful in identifying the type of filter or consistent with "Your country" filter

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1557]
As a new user, the icon displayed on the listings page for "All seller countries" seems randomly selected, not very helpful in identifying this specific filter (or consistent with "Your country" filter"). 

For me, its already confusing that i can filter on my own country AND the sellers country, think about it. Which of the two do i need to use to display what i want?....

If you decide to keep both filters, a little world icon seems better just as for "Your country". However, now there are two of the same icons which is confusing as well. I am sure the team can come up with something more consistent.

![part2 - Copy](https://user-images.githubusercontent.com/49277632/55558736-4b461e80-571f-11e9-8056-f3ddcfe58a38.png)

**Comment by zaSmilingIdiot** [comment]
Filter improvements have been made in release v3.0.0 that caters to this.
