### ISSUE TITLE
H&S: Social Links - Google+ Abandoned

### ISSUE THREAD

**Issue by DrDBanner** [particl/particl-desktop#1567]
# Describe bug/issue

On H&S Page - Social Links - there is Google+ this service is abandoned. Possible substitution can be "Instagram"

- Operating system and version: All
- Client version: 2.0.0-testnet20190411

**Comment by zaSmilingIdiot** [comment]
Ah, so very true... thanks for pointing this out.

@AllienWorks any other links that we can use instead?

**Comment by AllienWorks** [comment]
Yeah, Instagram or Mastodon (if that's not there already) – in the spirit of promoting decentralized/federated open-source stuff ;)

**Comment by zaSmilingIdiot** [comment]
Has been updated to include the Particl Mastodon link
