### ISSUE TITLE
Balance Transfer Failure in Market Wallet

### ISSUE THREAD

**Issue by dgbarton** [particl/particl-desktop#1569]
# Describe bug/issue
Cannot execute "public" -> "anon" or "public" -> "blind" balance transfer in "Market" wallet.  If this is by design, then it represents function that is not intuitive to the user, and the balance transfer buttons should be grayed out or removed if they don't work.
..

# How to reproduce
1. Create a wallet named "Market" to enable marketplace listings to show up
2. Receive testnet funds
3. Click on "Send" and attempt a balance transfer from "public" to "anon" or "public" to "blind".

# More information
![image](https://user-images.githubusercontent.com/18644860/55980786-115aa800-5c4a-11e9-88c2-527a225f2e3a.png)

![image](https://user-images.githubusercontent.com/18644860/55980852-38b17500-5c4a-11e9-9b94-b25604b0ced0.png)

- Operating system and version:
Operating system: Windows 10 64-bit

- Client version:

Client 2.0.0-alpha-testnet20190411
Market 0.0.53
Core 0.18.0.5

**Comment by dgbarton** [comment]
It's good to see that transaction fees weren't taken from the public balance when this error occurred, but I think people will still expect the buttons to work if they're present on the GUI, and this behavior will cause frustration.

**Comment by zaSmilingIdiot** [comment]
The specific error in thid case is due to thr wallet not having created a private (stealth) initial address.

To resolve this specific issue, navigate to Wallet > Recieve > Private tab (the seond tab). Unlock your wallet when prompted (if your wallet is locked). If all goes well, an address should be generated. You can then try the convert options again.

**Comment by zaSmilingIdiot** [comment]
Just to note that the Market wallet is just another regular wallet, and is expected to behave as such... So there is nothing special about it other than its name (which we are using currently to enable the marketplace when the wallet is changed to).

**Comment by dgbarton** [comment]
Thanks for the information.  I generated a stealth address and attempted another balance transfer, but it failed again, this time with a different error message: 
![image](https://user-images.githubusercontent.com/18644860/55981543-c9d51b80-5c4b-11e9-8fb6-0971ea775ad7.png)

**Comment by dgbarton** [comment]
That happens for both "public" -> "blind" and "public" -> "anon"

**Comment by dgbarton** [comment]
Weird...I just tried with an amount of 1.1 PART and the transaction worked, but it failed the times I was testing with 0.1 PART as the amount.  Maybe there is a bug with balance transfers below 1.0 PART?

**Comment by dgbarton** [comment]
It seems like balance transfers with values less than 1 PART get zero transaction fee.  The transaction fee showed up as nonzero for the 1.1 PART transfer that executed properly.
![image](https://user-images.githubusercontent.com/18644860/55981906-9c3ca200-5c4c-11e9-99c6-b8f3864042e6.png)

**Comment by zaSmilingIdiot** [comment]
I'll confirm this in a few hours, but it may just be a case of the fee value being rounded to some decimal place for display purposes. But maybe it really is nothing :)
Let me confirm though as soon as I am able to.

For certainty, you should be able to check the actual fee in the transaction history table for the specific transaction.

**Comment by dgbarton** [comment]
Closed because this is apparently fixed when using 0.18.0.6 core in Desktop
