### ISSUE TITLE
Missing space

### ISSUE THREAD

**Issue by michmish** [particl/particl-desktop#1573]
![IMG_20190412_235420_335](https://user-images.githubusercontent.com/44212051/56068223-51bb4280-5d7e-11e9-928a-2ac05432cbc8.jpg)

**Comment by HenkSwardt** [comment]
Nice catch @michmish , thanks.

@cis-shubham-t , please will you clean this up for us. 

dont'tenter -> don't enter

Thank you

**Comment by zaSmilingIdiot** [comment]
@HenkSwardt @cis-shubham-t I have already included this change as a part of https://github.com/particl/particl-desktop/pull/1571
(Just need to push local changes up)

**Comment by zaSmilingIdiot** [comment]
Fixed as per #1571
