### ISSUE TITLE
Hard to go bottom : scrollbar is too narrow

### ISSUE THREAD

**Issue by michmish** [particl/particl-desktop#1575]
Perfect for tactile users but really hard for computer users (really really hard without mousewheel).

Possible to make the scrollbar width a little bigger ?

**Comment by HenkSwardt** [comment]
@AllienWorks , can we maybe see if there is a way to visibly make this easier for the users?

**Comment by AllienWorks** [comment]
Scrollbar is 6px wide. It might not be super large, but it is enough. Here's my reasons for that:
- users on notebooks can easily scroll via gestures on touchpads
- users on PCs have either mousewheels (IMO standard nowadays)
- ..or you can always click into the page and use your `↑` `↓` keys to move around

Making changes to the app for 0.1% of users doesn't seem reasonable. There are many more users with smaller screens for example and the space in the smallest size of app is quite limited. Making the scrollbars wider would decrease the experience for all of those in effect. Btw in the latest versions with multiwallet, there are possibly 3 scrollbars (on multiwallet, menu and content)..

**Comment by zaSmilingIdiot** [comment]
Closing as its a non-issue for now: 
A change can be contributed by a community member if so desired, or the issue re-opened if there is sufficient interest.
