### ISSUE TITLE
Staking weight is 10x too high in the gui

### ISSUE THREAD

**Issue by ericmnel** [particl/particl-desktop#1594]
# Describe bug/issue

Staking weight is 10x too high in the gui

src/app/wallet/overview/widgets/stakinginfo/stakinginfo.component.ts:    this.ownPercentageOfActiveStakingSupply = new Amount((this.weight / this.netstakeweight) * 1000, 5);

^ I think that is supposed to be 100 instead of 1000

# How to reproduce

Load wallet with non-zero balance and unlock for staking, staking weight is 10x the percentage of total staked coins.

# More information

- Client version: 1.3.1

**Comment by zaSmilingIdiot** [comment]
Thanks for the find :)

Note that the 2.x versions (still in pre-release) have this calculation correct. See for example
https://github.com/particl/particl-desktop/blob/market/src/app/wallet/overview/widgets/stakinginfo/stakinginfo.component.ts#L90

There are a number of improvements in the 2.0.0 release that probably need to be ported back into v1.x
We'll look at addressing this shortly.

**Comment by zaSmilingIdiot** [comment]
This has been resolved in the 1.4.0 release.
See https://github.com/particl/particl-desktop/blob/1.4.0/src/app/wallet/overview/widgets/stakinginfo/stakinginfo.component.ts#L89
