### ISSUE TITLE
Stake rewards stopped being included in total balance

### ISSUE THREAD

**Issue by ericmnel** [particl/particl-desktop#1595]
# Describe bug/issue

Left gui unlocked for staking.  Received six stake rewards, the first two were included in the total balance, the last four were not.

Quit gui and restarted, total balance included all six stake rewards in a higher value.

# How to reproduce

unknown

# More information

- Operating system and version: Mac OS X 10.14.5
- Client version: 1.3.1

**Comment by zaSmilingIdiot** [comment]
Should be resolved now as per the latest v1.4.0 release.
