### ISSUE TITLE
minor (visual) - Send payment /convert switching between trans. type makes "available balance" text bold and box jump for a split sec.

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1597]
Its a visual issue and kind of annoying considering the look and feel of the application overall is pretty slick.

When switching between transactions type (public/blind/anon), the "available balance" text of the one switching from becomes **BOLD** for a split second before turning regular again. It makes the text itself and box surrounding the whole conversion area jump a bit.

Win 10 x64
Blind Alpha 2.0.0

**Comment by AllienWorks** [comment]
Fixed in upcoming `gfx/tweaks` PR. Thanks for reporting!

**Comment by zaSmilingIdiot** [comment]
Closing this as its been resolved in the now released v2.0.0-alpha2-testnet build.

If the problem persists, please don't hesitate to re-open this issue, or open a new one.
