### ISSUE TITLE
"State" shouldn't be a mandatory shipping field when a country is selected that doesn't have states or doesn't use the info for their postal services

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1601]
Most postal services don't use the state for delivery, at least in countries where I've lived. Also, some countries don't actually have states. I can't buy an item if i don't fill in the state field, maybe change to being non mandatory or adapt to which country is specified?

**Comment by zaSmilingIdiot** [comment]
> Most postal services don't use the state for delivery, at least in countries where I've lived

That's anecdotal evidence though, and we need to be able to cater for other countries that possibly do make use of the field, and which requires it.
Keep in mind that also, its not simply the postal services of the various countries, but any shipping/courier service that any seller may particularly require.

And then managing lists of countries where this is a requirement, inside of the application, becomes problematic when the list needs to be updated. Firstly, it requires that we monitor changes in the space, and secondly, when the list updates for whatever reason, a new version needs to be issued. Which might be out band with an existing release cycle, and more relevant requires that affected users update to the latest version immediately.

Thats not to say that we cannot look at removing the requirement on the state field: that is a possibility. The alternative option though is that if a particular field is not relevant to a country that requires it, simply place a space character or even a "N/A" (or something else representing "Not Applicable") in the field.

**Comment by zaSmilingIdiot** [comment]
Should be resolved: the state field is no longer required in the address field. Will be available in the next release version (expected v3.2)
