### ISSUE TITLE
zapping to 100% get stuck

### ISSUE THREAD

**Issue by kangoala** [particl/particl-desktop#1602]
zap to 100% at cold staking does not work and I have to cancel since no further progress is seen (no message, etc.)

Starting up Desktop 1.4
Unlocking Wallet
Cold Staking Node e.g. on 75%
ZAP (fast forward to 100%)
Windows "Cold Stake Zap" appears
Zap to 100% - doesn't seem to respond in any way

Windows 10
particl-desktop-1.4.0-win-x64

**Comment by zaSmilingIdiot** [comment]
Thanks, will investigate this further.

**Comment by zaSmilingIdiot** [comment]
Has been resolved: https://github.com/particl/particl-desktop/commit/ad503ee968a1f0f8eca7d23932f3c0c639a3763d

Particl Desktop v1.4.1 contains the fix.
