### ISSUE TITLE
minor - "wallet has no usable address for voting" error message could be defined more clearly

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1603]
Following error shows up when i don't have coins in my wallet and try to remove an item from the marketplace "wallet has no usable address for voting". I think this could be changed into something that the user would understand more easily, such as "You currently don't have funds in your wallet to vote with" or "Please add Particl coins into your wallet in order to vote". These are just two random examples, you may be able to come up with something more consistent depending on how you approach your error definitions. 

Lest Alpha Blind 2.0.0
Win 10 x64

**Comment by zaSmilingIdiot** [comment]
The error message has been updated to a more user friendly message in Desktop release v2.1.0
