### ISSUE TITLE
Flagging items initiates a publishing fee and error tells me my vote was not weighted correctly

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1604]
When i try to flag an item on the marketplace, i get the following error:

![er - Copy](https://user-images.githubusercontent.com/49277632/61108718-b7ba8180-a4b5-11e9-8f4a-416e90db7532.jpg)

Consecutively, this happens:

![1b8036917569c14ef32b2e7de7b25bbc - Copy](https://user-images.githubusercontent.com/49277632/61108743-c3a64380-a4b5-11e9-80e7-af609f4b5cf7.png)

A publishing fee is generated somehow, i can't remember seeing this before. If this is normal behavior, "Publishing fee for either posting a listing on the market or voting on proposals" message needs to be adjusted accordingly (include flagging items).

blind alpha
win 10 x64

**Comment by PARTimprovert** [comment]
to add: Some items that i try to vote on now all of a sudden turn up multiple times in the listing page. At first there was just one now there are three of the same

**Comment by PARTimprovert** [comment]
These multiple items now disappeared again, i think after refreshing or going back to the listing page from another tab

**Comment by PARTimprovert** [comment]
listunspent gives me:
![l - Copy](https://user-images.githubusercontent.com/49277632/61110808-bb9cd280-a4ba-11e9-975d-b0a5dcd12c03.jpg)

it gave me [ ] just a minute before btw.


This reminds me of the fact that there should be an easier way to copy info from the console (can't select/copy it seems)

**Comment by zaSmilingIdiot** [comment]
There's a couple of things going on here, so to address each one:

- the issue of the flagging of the item showing the message that "your vote was not weighted correctly", and then not removing the item from the listing page, has been resolved.
- the first person(s) to flag an item currently create the proposal to remove the item. This proposal creation incurs a charge. Its not something new and has been around for a while already it seems.
- we can look at updating the transaction table help message for flagged proposal creation.
- having multiple of the same listing items in the Listings page (and then disappearing again on refresh) should now also be resolved. We're also monitoring this in case of further issues.
- copy from the console window has been added back into the next release.
- not having utxo's and then seeing one a couple of minutes later is likely a result of having only 1 utxo, which then gets locked doing a split (for a transaction, or a listing/proposal/flag item proposal creation). This locks the single utxo, spends it and returns the change back to you. But you need to wait for a number of confirmations (depending on the transaction type) before that utxo becomes spendable again.

For all of the issues indicated as being resolved above, they will be included in the next testnet release, and will form a part of the v2 mainnet release.

**Comment by zaSmilingIdiot** [comment]
Closing this for now as the changes indicated are applicable in the now released v2.0.0-alpha2-testnet build.

If this is still an issue going forward, please do not hesitate to re-open this, or create a new issue.
