### ISSUE TITLE
placement of order overview - aditional link in menu bar

### ISSUE THREAD

**Issue by kangoala** [particl/particl-desktop#1607]
Since you often have to wait for seller to accept your bid, it would be nice to have a quick access to your order list. So far I have to search in "Buy" and to select the order tab. 
For example a link in the left menu bar would be helpfull to get a one-click feedback on how the order status is.

**Comment by kangoala** [comment]
After playing around with mp, I've seen that you get hints by numbers behind the buy/sell icon when something in order status has changed. Really great!!! By that a regular and fast feedback on the order status got less important for me. However to get on an easy way an overview on all buy/sell-orders, an icon left of the shopping cart would be nice, which opens a page with the status of all buy- and sell-orders on (e.g. buy-orders on the left side / sell-orders on the right).

**Comment by zaSmilingIdiot** [comment]
v3.0.0 has this request built into the Overview page.

**Comment by zaSmilingIdiot** [comment]
As mentioned above, links to the orders list (amongst other pages) are available in the Overview page (currently the default landing page when opening the market app), in the release v3.0.0
