### ISSUE TITLE
http failure response when trying to create 'market' wallet

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1608]
Just did a fresh re-install, trying to create market wallet now gives me the following error (my internet works just fine):

![mm - Copy](https://user-images.githubusercontent.com/49277632/61128981-ff590180-a4e5-11e9-9145-b9ac8865bdd8.jpg)

After trying to go back and clicking cancel, the loading screen appears but remains stuck (with ido kaiser quote, animation keeps going).

Apart from the occurring error itself, the message is not clear to the user either.

win 10 x64
latest alpha blind

**Comment by zaSmilingIdiot** [comment]
This could be due to testnet "seed nodes" not being available. Will look into it.

**Comment by PARTimprovert** [comment]
What is interesting: i restarted the application, trying to create a wallet named 'market' yet again. Now the application is saying there's already a wallet named 'market' which is surely not the case. Somehow a new wallet is present, named 'TEST'. When i click on it, it goes back to the initial wallet creation screen. There's something buggy going on here, i did not create this wallet in the first place. (edit: i may have actually created this so called 'test' wallet and forgot about it, but the market wallet is not present yet this message is still shown fyi)

**Comment by PARTimprovert** [comment]
The chain doesn't appear to be syncing anymore. Clicking on the syncing screen for the popup (which doesn't appear to be making progress) shows the spinning fidget, but that's stuck as well.

**Comment by PARTimprovert** [comment]
It appears to have to do something with my internet, i switched wifi and it works again, as in the chain is syncing now. I still can't create the market wallet though as it's still saying it already exists when it doesn't.

**Comment by zaSmilingIdiot** [comment]
> I still can't create the market wallet though as it's still saying it already exists when it doesn't.

In the multiwallet sidebar, do you see a wallet with the 'M' icon (hovering over it should display the wallet name ('market') )?

**Comment by PARTimprovert** [comment]
nope, the wallet's not there.
Also: When i create a new wallet now, name it xxx go to the next screen through continue but cancel the process there by going back, the wallet is still created and showing up in the left menu. When i click on it it goes to the initial wallet creation screen. Interesting :D

It appears a wallet is made but its not really as the process was not finished. But maybe that was the point to have it there and to be able to finish the creation process?

An additional note: It appears i am unable to delete or rename wallets through particl desktop, correct? Maybe something you want to add as a feature later on. Sorry offtopic i know i should create a new recommendation issue.

**Comment by zaSmilingIdiot** [comment]
See the comment in this issue on the wallet creation process: https://github.com/particl/particl-desktop/issues/1570#issuecomment-510803255

That should hopefully clarify why the wallet is created after providing a name for it :) The reason clicking on it takes you back to the original screen then is because its still possible to restore a wallet to the named wallet (by providing the 24 words). Or alternatively, its possible to still initialize a new wallet by following that process.

**Comment by zaSmilingIdiot** [comment]
> An additional note: It appears i am unable to delete or rename wallets through particl desktop, correct? Maybe something you want to add as a feature later on. Sorry offtopic i know i should create a new recommendation issue.

Yep, thats something that's been mentioned before, that we are still likely going to be adding in the future. At least the deleting part. Renaming a wallet should technically be possible as well, so I guess we could look into that around the same time.

What is concerning is that you don't have a wallet named market, but its claiming that one exists. Can you check whether the physical wallet file has been created please?

**Comment by PARTimprovert** [comment]
The market folder has been created, no wallet.dat is present in this particular folder

**Comment by zaSmilingIdiot** [comment]
Hmmm, thats weird.. I wonder if something happened with particl-core during the market wallet creation process? 

Anyways, if there's nothing inside the folder, could you perhaps try deleting it (maybe first making certain that the desktop has properly stopped and the daemon is not running), and then start the desktop up again and attempt the market wallet creation process again.

**Comment by PARTimprovert** [comment]
database folder, .walletlock file and db log are present in this folder

**Comment by PARTimprovert** [comment]
after deleting the folder, i now seem to be able to create a market wallet, and succeeded.

**Comment by zaSmilingIdiot** [comment]
Yep, was just about to suggest that deleting it should be fine. Happy its sorted now.

**Comment by PARTimprovert** [comment]
Somehow i got the application to create a market folder without the wallet.dat file though, so there's still a bug there of some sort

**Comment by HenkSwardt** [comment]
Your wallet.dat files will be in the particl folder. the Particl Market folder only holds marketplace related data. 

You should see a testnet folder within your Particl folder and in there a folder specific to your Market wallet

**Comment by PARTimprovert** [comment]
i know henk, there was no wallet present in the market folder inside the particl folder...
to confirm, Roaming/Particl/testnet/wallets/market

**Comment by HenkSwardt** [comment]
Ahh, thank you. Just wanted to make sure we looking at the same folder. That is the correct one indeed.

**Comment by zaSmilingIdiot** [comment]
Error feedback during wallet creation on v3.0.0 should be improved, along with much quicker and reliable wallet creation steps

**Comment by zaSmilingIdiot** [comment]
Closing this as it should be resolved and fixed in v3.0.0
