### ISSUE TITLE
Proposal pages need pagination

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1610]
From the Testing channel chat:

CryptoBeans: @Abansemer I noticed that the Past Proposals page doesn't have pagination or anything, they're all just listed out. (or at least, I haven't hit a pagination threshold yet). Have you tested/prepared that page for handling a massive proposal count?

<abansemer:matrix.org> not yet, to be perfectly honest. The active proposals page doesn't have pagination either for that matter.
In saying that, I've really (personally) wanted to re-do the whole proposals page at some point: its definitely not optimally done in its current form, and there are much better ways to do it given the data (and the requests to access it) we have available. Not sure when that will happen though.

**Comment by zaSmilingIdiot** [comment]
No longer relevant to Particl Desktop v3.0

General proposals are being moved to a more significant location (external to the Particl Desktop application). It may be possible in the future to incorporate into the Particl Desktop application a view over the new external proposals system, but for now it remains as part of the external system.

See https://ccs.particl.io/  and https://github.com/particl/ccs-proposals
