### ISSUE TITLE
Eliminate escrow transaction listing by adding TXID to order pricing info

### ISSUE THREAD

**Issue by kangoala** [particl/particl-desktop#1611]
Showing up escrow-transaction with blinded amounts in the transaction list confuses users since no other information than the TXID is given. There's no easy way to link this TXID to a certain listing (once multiple listings got processed in an short timeframe).

In the orders tab of buy/sell you can provide beside shipping and pricing information also a field underneath the Escrow or Total prize amount, where either is given "to be payed" or (once the transaction already took place) the TXID.

Thus you don't loose the link between listing and corresponding TXID of the escrow transaction. You can also see by the TXID that escrow already has been payed and we don't need to list the escrow transaction on the transactions-list, since in my opinion this is unnecessary and for the unexperienced user rather confusing.
![Inkedbandicam 2019-07-18 09-08-47-349_LI](https://user-images.githubusercontent.com/45103026/61497982-b57a8a80-a9c1-11e9-8fec-92dba446843b.jpg)

**Comment by zaSmilingIdiot** [comment]
The transaction table is a list of transactions as they have occurred in the wallet. I don't think hiding or removing transactions from that list is such a good idea.

However, with regards to providing the escrow transaction ID on the order item once it is available, that has been done and included as part of the alpha3 testnet release, and will be a part of the upcoming mainnet release.

**Comment by zaSmilingIdiot** [comment]
The TXID for orders has been available since v2.0.0 (initial mainnet release).

Closing this as having been implemented.
