### ISSUE TITLE
Make orders-tab the default view in the sell-menu

### ISSUE THREAD

**Issue by btmr** [particl/particl-desktop#1612]
At the moment, the listings-tab is shown first after navigating to the sell menu.

However, active vendors will need to access the orders-tab much more often than the listings-tab because that's where all the action of the sell-flow process is happening. They will be accepting bids and confirming escrows much more often than adding or checking listings.

I therefore suggest to switch the orders- and listings-tab in the sell-menu so that "Orders" is the default view.

**Comment by PARTimprovert** [comment]
Agree!

I'd like to add that "Buy" in the left menu should be changed into "My Orders". "Buy" is so confusing when there is "Listings". It should be: Listings, My Orders, Sell (imo)

**Edit:** I have made a separate issue for this as i feel it's important: https://github.com/particl/particl-desktop/issues/1614

**Comment by zaSmilingIdiot** [comment]
The original has been implemented in v2.2.0: see the change description noting

`The Orders tab on each of the Buy and Sell pages is now set as the first tab that is loaded (except if items are in the cart, in which case navigating to the Buy page will display the Cart tab first).`
