### ISSUE TITLE
Wallet needs to be unlocked to read bids

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1615]
If your wallet is locked then there should be a warning message on the Orders tab of the Sell page that displays. It should read something like "You are not currently able to read/process new bid messages while your wallet is locked." 

There is nothing to let a user know they need to do this so many people are going to think they did not receive a bid when in fact their wallet was just locked.

**Comment by zaSmilingIdiot** [comment]
A note in the page header help has been added and will be included in the next test release (and will be included in the upcoming v2.0.0 mainnet release)

**Comment by zaSmilingIdiot** [comment]
Closing this as its included in the now released v2.0.0-alpha2-testnet build.
