### ISSUE TITLE
Combine all the staking stats into one number

### ISSUE THREAD

**Issue by ericmnel** [particl/particl-desktop#1616]
I propose combining all the staking stats into one number.  Next reward is not useful, and "stake weight + stake percentage" is non-intuitive.  

What I would rather see is something like what is on https://stats.particl.page:

STAKING REWARDS 5.67% p.a.
[hover over the number and you get  "3% distributed to 52.92% of network"]

**Comment by zaSmilingIdiot** [comment]
Additional staking details provided for in v3.0

**Comment by zaSmilingIdiot** [comment]
Implemented in release v3.0.0
