### ISSUE TITLE
Initial creation of market wallet lets particl desktop hang (win10x64), needs a restart

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1622]
# Describe bug/issue
Market wallet creation hangs, spinner keeps going forever, need to force quit the application.

# How to reproduce

Install particl desktop
Create regular wallet
Create market wallet
Spinner would go on forever, i quit application after 10 minutes
After restart, market wallet appeared to be created.

- Operating system and version: win10 x64
- Client version: latest testnet before mainnet launch

**Comment by PARTimprovert** [comment]
Some other users appear to experience the same problem reading through testing channel over at discord, all win 10 users

**Comment by HenkSwardt** [comment]
Issue logged on Jira - https://particl.atlassian.net/browse/PBD-437

**Comment by zaSmilingIdiot** [comment]
Resolved in v3.0

**Comment by zaSmilingIdiot** [comment]
As mentioned in my previous comment, I'm closing this as its been implemented in release v3.0.0
