### ISSUE TITLE
Publishing fee transactions are displayed as "0 PART" in the collapsed view of the transaction history

### ISSUE THREAD

**Issue by btmr** [particl/particl-desktop#1625]
# Describe bug/issue

A non-zero publishing fee, e.g. 0.00123 Part is displayed as "0 PART" in the collapsed view in the "All transactions"-tab in the transaction history menu or in the "Recent transactions"-list in the Overview menu.
In the pull-down view, the fee is then shown as -0.00123 PART, while the net amount is 0 PART.

This is inconsistent with the display of other sent transactions, since a publishing fee is no different to a bookkeeping user: it means that this amount has been deduced from the wallet balance.

# How to reproduce

1. Publish a new listing and then check the transaction history or overview page.

# More information

- Operating system and version: Linux Ubuntu 16.04
- Client version: 2.0.0-alpha2-testnet
- Market: 0.0.78
- Core: 0.18.1.0

![2019-08-01-pub-fee-display](https://user-images.githubusercontent.com/37769547/62328375-49188480-b4b3-11e9-905d-adfbdd4395cd.png)

**Comment by zaSmilingIdiot** [comment]
This occurs because the actual value of the transaction is 0. There was simply a fee that was applied to it.
This typically occurs with sending paid smsg messages. A transaction occurs (for a value of 0), but the fee still exists. Hence, the "Publishing fee" row indicating a 0 amount, with the fee displayed in the expanded details section.

**Comment by btmr** [comment]
Understood. Thanks.

I expected the number in the top right corner to reflect the actual income / expense, like in a bank account statement. It would be more practical, in my opinion, but that's a matter of preference.

Should I close this issue then?
