### ISSUE TITLE
Enhancement: When unlocking by clicking the Lock/Unlock icon, let us choose the timeout

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1626]
I noticed when I unlock it defaults to 5 minutes of unlock. Can we get a selector/dropdown to choose a value for this? I think being able to choose a 1-hour or more timeout would be very useful for sellers that want to actively listen for bids.

**Comment by HenkSwardt** [comment]
Good day, 

Thank yo for logging this. 

These defaults are set to ensure a wallet does not stay unlocked unattended. 

However, making use of the debug console you can unlock your wallet to the any time you choose to by making use of the correct command.

**Comment by zaSmilingIdiot** [comment]
Ability to set a custom unlock duration now exists as of Particl Desktop v2.1.0
Note that the option only exists when manually requesting a wallet unlock using the wallet unlock icon option in the top right of the application.
