### ISSUE TITLE
Too short of a timeout during checkout

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#1627]
When I checked out, it asked me for my decryption password and it unlocked for 30 seconds. I had 3 items in my cart and it only was able to process the first 2 during that 30 seconds and the third did not get purchased.

When I tried to purchase that third item, I was told I didn't have sufficient balance (my Anon coins were a single utxo which was now locked). This forced me to wait for 12 confirmations before being able to try to purchase that third item again.

Possible fix: If a user has more than 1 item in their cart, increase the timeout to 5 minutes instead of 30 seconds.

Update: After I got those 12 confirmations and my Anon utxo unlocked, I went back to my cart to purchase that third item. It went through the checkout process just fine and created a new Anon to Blind transfer, However, that third item was not removed from my cart automatically.

**Comment by CryptoBeans** [comment]
Update 2: I tried to check out with 18 items. It got through the first 2 fine then failed on the third. It gave me the warning about not having enough Anon coins to checkout. So it looks like the issue is actually the fact that each purchase locks an entire utxo and if you only have a couple Anon utxo's, then you can only make that many purchases at once. 

I guess this isn't a fixable bug per se, but just an inconvenience due to the utxo system. 

Update: After the Anon coins became spendable again, I tried to checkout on the 16 items left in my cart. I was greeted with this unhelpful error: 
![image](https://user-images.githubusercontent.com/38863166/62384176-494a6b80-b517-11e9-94a5-fe9498ec1c49.png)

**Comment by HenkSwardt** [comment]
With regard to update 1, the issue seem to have been related to the available amount of UTXO's rather than the length of time the wallet was unlocked. This also seemed to have been the issue in the first part of update 2. As rightly stated by you there. "I guess this isn't a fixable bug per se, but just an inconvenience due to the utxo system."

But we would like to get more information around the error you were greeted with. Do you think you can replicate this and supply us with the logs please?

Thank you

**Comment by HenkSwardt** [comment]
Issue logged on Jira - https://particl.atlassian.net/browse/PBD-442

**Comment by zaSmilingIdiot** [comment]
While there is a bigger change for the wallet lock/unlock mechanism, a change has been added that increases the wallet timeout based on the number of items in the cart. This is currently available in the alpha3 build for testnet, and will be included in the upcoming mainnet release.

**Comment by zaSmilingIdiot** [comment]
Closing this as the reported issue should now be resolved.
