### ISSUE TITLE
Listings help section: mentions "Blind" instead of "Anon"

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1630]
![privateblindbalancemustbeanonintext(lasttestnet) - Copy - Copy](https://user-images.githubusercontent.com/49277632/62412109-5c049380-b630-11e9-8da8-2003704ff634.jpg)

- Operating system and version: win10x64
- Client version: latest testnet before mainnet

**Comment by HenkSwardt** [comment]
Issue logged on Jira - https://particl.atlassian.net/browse/PBD-441

**Comment by zaSmilingIdiot** [comment]
Thanks for mentioning this. The wording has been updated accordingly and the change is currently available in the alpha3 build for testnet, and will be included in the upcoming v2.0.0 mainnet release.
