### ISSUE TITLE
3 Visual annoyances in "?" help section

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1631]
1. Title becomes larger when clicked on "?", why? I would keep it the same font size whether the help section is collapsed or not.
2. Some of the help text is of grey color and some is black, this does not make any sense to me. Just a visual distraction really.  
3. Why does the UI show a "?" mark when hovering over the grey colored text? Makes even less sense to me.

**Comment by AllienWorks** [comment]
1. Title becomes smaller to save space if minimized. Original size is bigger, to introduce newcomers to all the features. When you're familiar with them, you don't need to see them anymore, so we offer the option to minimize it.
2. Black text is explaining the features, grey one is for additional less important information. This is how it goes thoughout the whole app and it's a part of UX, you can call it "visual hierarchy".
3. To indicate that the text is explaining some features etc. but agreed, it's a bit of annoying and it will be removed.
