### ISSUE TITLE
Minor - filling in "amount" in conversion tab, but then changing the conversion type CLEARS amount field

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1633]
Filling in let's say 10 coins public to anon but then change anon to blind clears/resets the amount field. 

- Operating system and version: win10x64
- Client version: Latest testnet before mainnet

**Comment by HenkSwardt** [comment]
Good day, 

Thank you for logging this. 

In this case we have validations on the total available funds for the selected "account" (Public, blind and anon) Changing the selection of account you want to move funds out of will result in clearing the pre-filled value.

**Comment by PARTimprovert** [comment]
I understand, but i think you could still validate the field without the need to clear it first. This is textbook usability stuff really. Agree its minor compared to the overall scope of the project as of now.

**Comment by zaSmilingIdiot** [comment]
Implemented in v3.0 - changing the conversion source (the "pay from") no longer clears/resets the entered amount value.

**Comment by zaSmilingIdiot** [comment]
Closing this due to being resolved in v3.0.0
