### ISSUE TITLE
"Comment" section missing when opening listing from buy section (after it was added to cart)

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1636]
There is an inconsistency, when opening a listing on the listings page, the comment section is present. When opening the listing from the buy page after it has been added to the cart, this comment section is missing.

- Operating system and version: Win10x64
- Client version: Latest testnet before mainnet

**Comment by HenkSwardt** [comment]
Good day, 

Thank you for pointing this out. The comment section however is an upcoming feature as per the screen viewed on the listings page (comments coming soon). Comments visibility during the buy flow will be added once the functionality is available.

**Comment by zaSmilingIdiot** [comment]
The comment section was explicitly left off the listing item details when the listing details is accessed via the cart. Once added to the cart, the modal is meant to provide a summary of the listing item information.

We can look at adding this in once the comments section has been rolled out and further requests for this are made. But at least intuitively, comment interactivity on an item from within the checkout cart doesn't seem to make much sense, at least not at this point.

**Comment by zaSmilingIdiot** [comment]
I'm going to delegate this request to something that would need further support on -> it doesn't appear to make sense to have the comment sections visible in the cart checkout step on a listing.

Hence closing this for now until further support is obtained for this to exist.
