### ISSUE TITLE
UX suggestion - whenever there are new listing available add "new!" or "1" to refresh button (if technically feasible)

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1637]
The whole process of having to click the refresh button is not very intuitive for new users. Especially when running particl desktop for the first time and navigating to the listing section early before any of the listings could sync. Listing page now appears empty.... Giving feedback to the user may help a bit here, by for example showing a "1" or "new!" text along the refresh button itself. Probably not technically feasible at this point i assume? Something to think about

**Comment by PARTimprovert** [comment]
For example, there is a guy now in discord having the listing page open for over an hour and expecting to see listings but nothing is popping up. This is a true UX issue, pretty critical if you ask me

**Comment by zaSmilingIdiot** [comment]
This has already been implemented for the second mainnet release version (or the first update to the first mainnet released version). Hence, it'll be available in a future release.

**Comment by zaSmilingIdiot** [comment]
Included as a part of the `v2.1.0` release.
Its not a badge indicator, but rather that the refresh button pulses (flashes) to indicate that new listings are available. In addition, we've included a new message when no listings are displayed (that includes a refresh button as well), to inform the user of what is expected.
