### ISSUE TITLE
Price overview displays a . (dot) after listing price/shipping/escrow and total price even when they consist of round numbers

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1638]
See screenshot below, price section

![4751eaae183739b4e5db6cc55004b464 - Copy](https://user-images.githubusercontent.com/49277632/62412863-a8ed6780-b63a-11e9-94ad-2a5c6b8327ef.png)

- Operating system and version: win10x64
- Client version: latest testnet before mainnet

**Comment by HenkSwardt** [comment]
Issue logged on Jira - https://particl.atlassian.net/browse/PBD-440

**Comment by zaSmilingIdiot** [comment]
Thanks for mentioning this. The decimal point rendering has been updated accordingly and the change is currently available in the alpha3 build for testnet, and will be included in the upcoming v2.0.0 mainnet release.
