### ISSUE TITLE
"last updated" date doesn't update on item status (order tab), no manner what action is taken before, in or after the escrow process

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1641]
See title.
"updated" date remains equal to "added" date throughout the whole process. Expected behavior is "updated" date to be changed through the escrow process.

- Operating system and version: win10x64
- Client version: Latest testnet before mainnet

**Comment by PARTimprovert** [comment]
note: My wallet's never been locked

**Comment by HenkSwardt** [comment]
Issue logged on Jira - https://particl.atlassian.net/browse/PBD-439

**Comment by zaSmilingIdiot** [comment]
Thanks for mentioning this. The "updated" date value has been modified, and the change is currently available in the alpha3 build for testnet, and will be included in the upcoming v2.0.0 mainnet release.
