### ISSUE TITLE
Missing notifications about new buy/sell orders in the market-menu

### ISSUE THREAD

**Issue by btmr** [particl/particl-desktop#1642]
# Describe bug/issue

When someone makes a bid on one of my listed items, there is no notification in the market-menu on the left-hand side (small number that should appear next to "SELL").
At the same time, when a seller confirms my bid, there is no notification next "BUY".

I am running the Desktop app throughout (...linux-amd64.deb)

I remember getting those notifications in the last version alpha1, now they seem to be missing completely.

# How to reproduce

For sell orders:
1. Open Particl Desktop app and leave it open throughout the buy/sell process.
2. Publish a new listing and have someone make a bid for it.
3. You will see no notification about this new bid in the market-menu

For buy orders:
1. Open Particl Desktop app and leave it open throughout the buy/sell process.
2. Make a bid on a listing and wait for the seller to confirm your bid.
3. You will see no notification about this confirmation in the market-menu.

# More information

    Operating system and version: Linux Ubuntu 16.04
    Client version: 2.0.0-alpha2-testnet **linux-amd64.deb**
    Market: 0.0.78
    Core: 0.18.1.0

**Comment by PARTimprovert** [comment]
already logged here: https://github.com/particl/particl-desktop/issues/1640 
EDIT: seems different issue

**Comment by btmr** [comment]
well that's on a completely different OS and from the title in #1640 I take it that PARTimprovert can eventually get the notifications. I never see them.

**Comment by zaSmilingIdiot** [comment]
It may be a different OS, but the underlying concern/issue is still the same. 

I'm closing with reference to #1640
