### ISSUE TITLE
Two bids were made by two independent users, the same item was then shipped to both users, two different escrows were made for a single listing

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1643]
So..
This happened while on the hangouts session with Ben. My funds got locked up in escrow, however, Ben decided to go forward with another bid which he accepted as well. My funds are now locked in escrow while he finalized the other bid. Escrow can't be retrieved it seems

![399bf10b49b919b44752cf14d7471f04 - Copy](https://user-images.githubusercontent.com/49277632/62416625-b9b8d000-b670-11e9-9ace-32396af63f39.png)

@ben what does this bid look like now in your client after you've gone forward with the other bid?

- Operating system and version: win10x64
- Client version: latest testnet before mainnet

**Comment by PARTimprovert** [comment]
weird, so now i could retrieve my funds by marking as "received", it seems ben has shipped the same item now twice. I will get more specific need to re-play hangout session

**Comment by PARTimprovert** [comment]
So it appeared to be a listing by darkfox_HD (not ben), he apparently was able to sell the item twice (to me and to ben). This shouldn't be possible without inventory management am i right? Ben was apparently able to sell the same item multiple times as well

https://media.discordapp.net/attachments/607305779757842436/607314829232832512/image0.jpg?width=1486&height=1115

**Comment by kangoala** [comment]
Why shouldn't it be possible to sell an item twice (if you have multiple items to sell)?
I think this is rather a feature than a bug. If you only have on item to sell, then you should only accept the first bid and reject the others. It would also be nice to remove your listing then, but I think this is not yet possible. I think only the person which already bought one item can't put the same item again in it's shopping basket.
I've also sold my only listing four times today.

**Comment by PARTimprovert** [comment]
you're right, i guess i can close this issue myself as i am sure devs are aware.
