### ISSUE TITLE
Reporting and then re-approving listing gives JSON value not a string error

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1647]
The following error shows when i flagged an item and then tried to re-approve it:

![df - Copy](https://user-images.githubusercontent.com/49277632/62753908-30eec980-baa0-11e9-99fc-c379643bb077.jpg)

- Operating system and version: win10x64
- Client version: alpha3 testnet

**Comment by zaSmilingIdiot** [comment]
Thanks for reporting this. Will look into getting it resolved.

Just to note that re-approving the item a 2nd time does perform the relevant action correctly.

**Comment by zaSmilingIdiot** [comment]
I noticed this is still using the old 2.0.0-alpha desktop client. 

Are you still experiencing  this problem, when using a client version such as the current latest v2.3.0?
