### ISSUE TITLE
When only part of the cart bids go through when bidding, shipping profile is not saved

### ISSUE THREAD

**Issue by PARTimprovert** [particl/particl-desktop#1648]
Apparently i had insufficient funds to buy all the listings i wanted to bid on. 2 out of 5 bids make it through when i filled in my shipping info and selected to save my profile. However, after navigating back, trying to again make bids on the other three items, it appeared the shipping profile was not saved. I know it doesn't save it when there is an unsuccessful bid but in this case at least some of them got through and you would expect the client to save the shipping information.

Operating system and version: win10x64
Client version: alpha3 testnet

**Comment by zaSmilingIdiot** [comment]
The saving/updating of the profile information is only performed at the end of a successful order placement. As mentioned in https://github.com/particl/particl-desktop/issues/1644, we can look at shipping profile management as a future exercise.

As that issue deals with the same general topic, and the solution to it is the same, I'm closing this issue with updates and resolution to occur in that issue.
