### ISSUE TITLE
No "quit" in particl desktop app on mac

### ISSUE THREAD

**Issue by ericmnel** [particl/particl-desktop#1650]
Can't quit from the mac desktop menu

**Comment by r3n3x** [comment]
> Can't quit from the mac desktop menu

I have the same problem. Can't close Particl Desktop else than via "MacOS Force Quit".

**Comment by zaSmilingIdiot** [comment]
This has been fixed as of v2.1.0 -> a 'Quit' menu option should now exist and function as expected.
