### ISSUE TITLE
Hang on, we are busy processing your vote

### ISSUE THREAD

**Issue by ericmnel** [particl/particl-desktop#1654]
Voting to keep/remove a flagged item sometimes hangs forever with the message "Hang on, we are busy processing your vote". I waited an hour, then quit and restarted the app - once I got back in my flag vote was counted.

**Comment by zaSmilingIdiot** [comment]
A couple of changes have been made around the processing of votes in the desktop, in v2.1.0, which should have resolved this problem. Using this updated version, are you still able to reproduce your error scenario?

**Comment by zaSmilingIdiot** [comment]
This should now be resolved as of v2.2.0
