### ISSUE TITLE
Cannot scroll down to view all aucitons in 2.0.2

### ISSUE THREAD

**Issue by N-o-2** [particl/particl-desktop#1657]
When viewing the item listings in the market v2.0.2 the client will sometimes not load them when it scrolls down. The number of listings it shows seems to be limited to my screen size. I am using windows 10. The bug does not seem to occur on another version of 2.0.2 on windows 10 or 2.0.1 on windows 7.

**Comment by HenkSwardt** [comment]
Good day

Thank you for reporting tthis.

Please note this has been resolved and will be available in the next release. 

Changes made:
Only scrolling down will load more listings, we no longer only keep 3 pages
When loading listings or changing the screen size we now check if the scrollbar is visible, if not we load an additional page until such a time as the scrollbar appears.

**Comment by zaSmilingIdiot** [comment]
Particl Desktop v2.1.0 has added a fix for the scrolling behaviour on the listings page.
