### ISSUE TITLE
Drag Multi-Wallet Icons in the Sidebar

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1664]
Feature request: The ability to drag multi-wallet icons in the left sidebar in order to re-order them.

i.e. I might want my Marketwallet to always stay after my default wallet.dat, no matter how many new wallets I create after.

**Comment by zaSmilingIdiot** [comment]
No longer applicable as per v3.0 as the multiwallet sidebar has been changed to become an "app" (or "module") selector instead.
