### ISSUE TITLE
absurdly-high-fee bug

### ISSUE THREAD

**Issue by N-o-2** [particl/particl-desktop#1667]
I got an error when trying to send myself 10 PART to my ANON balance, the tx failed with the following message:

Transaction commit failed: absurdly-high-fee, 85150702 > 50000000 (code: 256)

The fee was about 0.85 PART to send 10 PART.

Ben in the forums suggested I enter the following into the console which has fixed it for now:

settxfee 0.002

I am using client version 2.1.0 on windows 10, 64 bit

**Comment by zaSmilingIdiot** [comment]
This appears to be less of an issue with the latest iterations of the Particl Desktop client and particl-core versions.

I'm closing this for now as it no longer appears to be an issue, but will re-open if the issue starts cropping up again.
