### ISSUE TITLE
Wallet does not return to unlocked for staking only from the console

### ISSUE THREAD

**Issue by N-o-2** [particl/particl-desktop#1668]
When unlocking the wallet from the GUI for most fictions if it had been preciously unlocked for staking only it returns to this state. However if the wallet is unlocked from the console and has previously been unlocked for staking only it fully locks when the time runs out. Not sure if this is a feature of a bug, but might want to review this for consistent behaviour.

I am using 2.1.0 on windows 10, 64 bit.

**Comment by zaSmilingIdiot** [comment]
I wouldn't say this is inconsistent - I don't believe its a concern. Using the console modal in the application is intended as running rpc commands directly against a running core instance. 

The default behaviour of core currently is that unlocking the wallet via `walletpassphrase` for "non-staking" returns the wallet to a "Locked" encryption status when the unlock timer expires. Regardless of whether the wallet was previously unlocked for staking only or not. The latest unlock request supersedes the earlier request.

When unlocking the wallet via particl-desktop controls, particl-desktop first checks if the wallet is currently unlocked for staking-only. If so, then it attempts to return to that state when the wallet attempts to lock again. Thus by unlocking the wallet directly via particl-core, you bypass this check and state. There is no means for particl-desktop to return to the previous unlock-for-staking-only unlocked state, and the desktop is reflecting the correct core state.

**Comment by zaSmilingIdiot** [comment]
Do you have any feedback for us regarding the comments above?

**Comment by zaSmilingIdiot** [comment]
Closing with age
