### ISSUE TITLE
Invalid From Address When voting on a flagged item

### ISSUE THREAD

**Issue by joefiorello** [particl/particl-desktop#1669]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue

..When I try to vote on a flagged item I get a message saying invalid from address.

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. ..Select a flagged item
2. ..Try to vote to keep

# More information

- Operating system and version: Windows 10
- Client version: 2.1

**Comment by zaSmilingIdiot** [comment]
This should have already been fixed in Particl Desktop client v2.2.0.

Are you still receiving the same error in a later client version? Current latest client is v2.3.0
