### ISSUE TITLE
My selling orders only update when I upload a listing

### ISSUE THREAD

**Issue by N-o-2** [particl/particl-desktop#1679]
My selling orders only update when I upload a listing. It's done it twice now so I'm pretty sure it's not a coincidence.

Using 2.2.0 on win 10.

**Comment by zaSmilingIdiot** [comment]
Could you perhaps provide a little more info on the actions taken please?

For example, if the uploading of the listing included the unlocking of the wallet (unlocking the wallet for spending), then this would have allowed order messages addressed to your wallet to be read and subsequently processed by the marketplace, resulting in order statuses being updated.

Such info helps us in tracking down the problem.

**Comment by N-o-2** [comment]
For my marketplace wallet I leave it unlocked for days on end by typing the following into the console:

walletpassphrase [password] 1000000000

I deliberately checked to see if uploading would trigger an update to my selling status and it did. So this is not just a coincidence I have noticed; I deliberately tested to see if uploading would trigger and update to the selling status and it did.

**Comment by zaSmilingIdiot** [comment]
The mechanics for receiving status updates from the particl-marketplace service has changed in v3.0, and so this should be a resolved issue once v3.0 releases to mainnet.

Is it possible to confirm whether the behaviour mentioned is reproducible using the v3.0 version (which is currently on testnet)?

**Comment by zaSmilingIdiot** [comment]
Closing. Can be re-opened if the problem persists in v3
