### ISSUE TITLE
Implement QT "Coin Controle" into desktop balance overview

### ISSUE THREAD

**Issue by kangoala** [particl/particl-desktop#1683]
**Is your feature request related to a problem? Please describe.**
Having one large anon balance (utxo), the user gets confused when making a small buy, the whole balance is blocked for 12 confirmations and no other buy is possible for a while.

**Describe the solution you'd like**
When clicking in Overview on "Public", "Blind" or "Anon"-balance, a detailed list of utxo's should show up as in particl QT when using the feature "coin controle".

**Comment by zaSmilingIdiot** [comment]
Coin Control implemented in v3.0 as part of the Sending Funds page.

**Comment by zaSmilingIdiot** [comment]
Closing: a basic coin control feature has been added in v3.0.0
