### ISSUE TITLE
Additional anonymity for btc-part-btc conversion by wassabi's coin join

### ISSUE THREAD

**Issue by kangoala** [particl/particl-desktop#1684]
**Is your feature request related to a problem? Please describe.**
After making an order on the marketplace users might want to store their values/coins rather in btc then in part.

**Describe the solution you'd like**
Provide similar to the first integrated SimpleSwap-feature an integrated way to convert it's part into btc and having at the same time those btc anonymized by coin-join. 
Wassabi-Wallet offers already an attractive way to anonymize it's btc's. The marketplace could build on top of a SimpleSwap-feature also the Wassabi-Coinjoin-Functionality.

**Comment by zaSmilingIdiot** [comment]
This appears to be "outsourcing" the transactional process to a 3rd party service. Which means that the entirety of the service is heavily dependent on said 3rd party, which compromises potential future integrity of the marketplace service: when a 3rd party changes policy, or is shutdown, or becomes compromised, etc, then that would have a direct impact on the integrity of the marketplace related transactions. 

I dont generally think this is a good idea at the moment, although in the future its possible that integrations into the marketplace services can exist, with this type of functionality being possible via such an integration. In this type of scenario though, the responsibility for developing and maintaining such an integration doesn't necessarily need to reside with the project developers, and the responsibility or choice to use such an integration or not is fully up to the end user.

I'm closing this as it doesn't appear to be relevant for now. Unless of course I've misunderstood the nature of the request. In which case, further discussion can be had and this issue can always be re-opened.
