### ISSUE TITLE
Put link to MAD description in checkout form

### ISSUE THREAD

**Issue by githubrsys** [particl/particl-desktop#1686]
The checkout process is the last step where a user might step back from putting a bid due to not understanding the MAD escrow -possibly. Putting a link beside the escrow fee takes the user by the hand and gives him confidence.

![CheckoutCart](https://i.imgur.com/mBQf4xq.png)

**Comment by zaSmilingIdiot** [comment]
The checkout confirmation in v3.0 has a section describing the steps to follow as well as what occurs with the escrow amount.

**Comment by zaSmilingIdiot** [comment]
Closing: implemented in v3.0.0
