### ISSUE TITLE
Insufficent funds message: make PART values go to clipboard 

### ISSUE THREAD

**Issue by githubrsys** [particl/particl-desktop#1687]
In the insufficient funds message during checkout process it is not possible to put the values to the clipboard. This should be changed. Even if this was done by intention. Freedom of choice is the keyword.

![foo](https://i.imgur.com/2yiciAU.png)

Client 2.3.1 (beta)
Market 0.2.6
Core 0.18.1.6
MacOS Catalina 10.15.1

**Comment by zaSmilingIdiot** [comment]
This has been resolved in v3.0: such indications of insufficient funds for purchases allow for the values to be selected and copied, if the user so desires.

**Comment by zaSmilingIdiot** [comment]
Closing: implemented in v3.0.0
