### ISSUE TITLE
Cart: Better handling for "Save shipping address" 

### ISSUE THREAD

**Issue by githubrsys** [particl/particl-desktop#1690]
**Is your feature request related to a problem? Please describe.**
When filling out the shipping address it is not possible to store the values (shipping profile) upfront (or at runtime). If you leave the module and come back, any inputs vanish. Though the cart still holds the shipping items. The shipping profile is not stored when hitting "continue to confirmation"

**Describe the solution you'd like**
Cart: Substitute the checkbox to store the shipping profile with a button which stores the profile at button release, then change color as indication of successful command. A shipping profile should then be able to be flagged as standard profile which optionally can auto-fill the form if the flag for this is set.

**Describe alternatives you've considered**
None. Convenience first.

**Additional context**

**Comment by zaSmilingIdiot** [comment]
The request seems to be related to #1644 and #1648 with the former being the current issue being used to track "progression" of this.

In all the reported cases, I suspect we might need to include a separate section for delivery address management. While this should not be problematic, it would likely need to be considered only after the market management changes have been implemented. But better mechanisms may be possible once we start with this.

I'm closing this request as a duplicate as they all relate to the same solution. Updates on this will be provided in #1644
