### ISSUE TITLE
Page Title Remain as "Exchange" When Leaving Exchange Page After a New Exchange is Initiated

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1692]
**Describe the bug**
Sometimes, the Exchange header will remain in place when switching back to the marketplace (see screenshot below). Clicking another tab and coming back to the "Listings" page will fix the problem.

**To Reproduce**
1. Go to 'Exchange'
2. Click on 'Start new exchange'
3. Go to 'Listings' or any other Particl Desktop page
4. See the top banner/header still says Exchange

Note: The problem will NOT arise if NOT clicking on 'Start new exchange'

**Expected behavior**
The top banner/header should not remain as "Exchange" but should change to the page's actual title (i.e. Listings).

**Screenshots**
<img width="1440" alt="Screen Shot 2020-01-03 at 4 31 05 PM" src="https://user-images.githubusercontent.com/27031337/71750673-37af1c00-2e47-11ea-88dd-c58d7913b3d5.png">

_Here, you can see the title of the page is still EXCHANGE instead of LISTINGS (just under the warning banner)._

**Versions (please complete the following information):**
 - OS: MacOS and Linux
 - Particl Desktop: 2.3.2
 - Particl Core: 0.18.1.6
 - Particl Market: 0.2.7

**Additional context**
You guys rock 🤘

**Comment by zaSmilingIdiot** [comment]
Closing this as its no longer applicable from v3.0

A new exchange/swap module would need to be written, which would replace the existing implementation.
