### ISSUE TITLE
Coherent communications language on bidding

### ISSUE THREAD

**Issue by githubrsys** [particl/particl-desktop#1693]
**Describe the bug**
When placing an "order" which is technically a "bid" it is quite unhealthy to mix up the terms. 

**To Reproduce**
1. Go to 'checkout'
2. Click on 'place order'
3. See problem

**Expected behavior**
A clear communication. And for the reason that it is technically a "bid" I would refrain to call it an "order"

**Screenshots**
![image of checkout message](https://i.imgur.com/GdKvzxg.png)

**Comment by zaSmilingIdiot** [comment]
The language around order processing has been cleaned as per v3.0

**Comment by zaSmilingIdiot** [comment]
Closing as this has been updated in v3.0.0
