### ISSUE TITLE
Usability Improvement: Gon't go through "starting marketplace..." each time user navigates away and comes back

### ISSUE THREAD

**Issue by MatrixManAtYrService** [particl/particl-desktop#1696]
I just tried my first purchase (yes, I know it's at my own risk), it was fun!  The ball is in the seller's court now.

It took a bit of fumbling to see that I had to transfer funds from my default wallet into my market wallet so I could use them to bid, and while doing so I switched frequently between the "D" tab and the "shopping cart" tab. 

It was kind of obnoxious that each time I switched I had to view a loading screen, and then when I switched back I'd lose my place and have to re-navigate to where I had been.

I think it would be better if clicking the various icons on the left switched views, but left the old one as is (though not visible) so when you switch back you're still on the same page.  This is especially helpful to somebody who wants to quickly switch between "Market" -> "Receive" and  "Default" -> "Send" in order to make sure they're about to send funds to the right address.

**Comment by zaSmilingIdiot** [comment]
Should be resolved as per v3.0.
The wallet switcher bar has been superseded by an "app"/"module" bar, when each "app" encapsulates the functionality specific to it. In other words, transferring funds between different wallet is all done within the wallet app.

And switching between different wallets (or apps) no longer transitions through the loading screen.

**Comment by zaSmilingIdiot** [comment]
Closing as this has been updated in v3.0.0
