### ISSUE TITLE
"Buy Orders" page should link to product description

### ISSUE THREAD

**Issue by MatrixManAtYrService** [particl/particl-desktop#1697]
There's an item I want to buy, and in its description it says:

> Any questions please email me:
> [the seller's email address]

If I bid on it, it shows up in the "Buy Orders" section.  Suppose that later I want to view the item's description again (either to send the buyer an e-mail based on their note, or to see some other detail).  I would like to be able to navigate to the original product info page from the "Bidding" buy order.  

I could be overlooking such a link, but it seems to me that in order to to find this information I have to go find the item in "Listings" in order to view its details, which seems unnecessarily convoluted.

**Comment by zaSmilingIdiot** [comment]
Resolved in v3.0

Almost everywhere (if not everywhere) a listing is involved (favourites, listings, orders, cart, etc), a link to the source listing is available.

**Comment by zaSmilingIdiot** [comment]
Closing: request has been implemented in v3.0.0
