### ISSUE TITLE
escrow negotiations

### ISSUE THREAD

**Issue by kangoala** [particl/particl-desktop#1699]
The new roadmap does have a feature called "escrow negotiations". I think it would be a great idea to include this buyer option after the shipment status, as a kind of additional status. Often buyer may want to send a received item back when they are not satisfied with the purchase. It also should be possible to cluster multiple items to one sending and then to negotiate only one item that may the buyer want have to send back.

**Comment by zaSmilingIdiot** [comment]
Escrow negotiations are pushed back somewhat... as I'm sure by now is obvious 😄 
I'm closing this issue now though: while there's nothing wrong with your request, I don't believe the implementation would practically work in the method described. But the actual implementation details still need to be finalized. It doesn't help having this issue lying dormant for future possibilities for details are not yet fully known. Might be better providing input to the process when the feature comes up for implementation.
