### ISSUE TITLE
Allowing copy and past of addresses and buyer info.

### ISSUE THREAD

**Issue by N-o-2** [particl/particl-desktop#1704]
There is no way to copy and past the buyer's address, visible under:

Market > Sell > Orders > Once an item is at shipping status, under SHIPPING ADDRESS

This could lead to transcription errors when posting an item.

This is the case on Windows 10, PD v2.3.2 and Mac OS v 2.2

**Comment by zaSmilingIdiot** [comment]
Resolved in v3.0

**Comment by zaSmilingIdiot** [comment]
Closing: implemented in v3.0.0
