### ISSUE TITLE
Tracking info is not visible to the sender.

### ISSUE THREAD

**Issue by N-o-2** [particl/particl-desktop#1705]
Any tracking info the seller enters upon completing shipping, is not viable to them. This means they need to keep a separate database of shipping info with a link to each item.

It would be better if this info was visible to them as well as the sender under the item info under the SELL menu so they can instantly find tracking details without the need for a separate lookup process.

**Comment by zaSmilingIdiot** [comment]
Included in v3.0
All communications passed between the 2 parties involved are visible to both.

**Comment by zaSmilingIdiot** [comment]
All information entered is now visible to both parties (the party that created the input as well as the party receiving it), from v3.0.0

Closing.
