### ISSUE TITLE
Items locked to escrow, show as cancelled when the buyer attempts to release funds and the funds remain locked.

### ISSUE THREAD

**Issue by N-o-2** [particl/particl-desktop#1708]
Seller sees 'Cancelled' for items sent to buyer and the fund remain in escrow. Seems buyer has tempted to release funds but the process failed. Notes from conversation with zaSmilingIdiot who has log files for this:

 - There's clearly the presence of a MPA_CANCEL message that was received for each item. Each  has the status though of PROCESSING_FAILED, which is interesting in that it indicates that there was an attempt to process the message but that processing failed for some other reason. In this case, likely because its out of sequence. Also, the status means that the marketplace is not going to retry process the message.

 - There are 2 tables in the marketplace DB that control the item status. I'm taking an educated assumption here that the one table has been updated incorrectly, while the other has not. Which means that the marketplace DB should still have the order open (its using the one table for certain processing, while the desktop is reading from the other to determine the general status of the order).

 - The funds are still locked in escrow.

Log files shared with zaSmilingIdiot.

**Comment by zaSmilingIdiot** [comment]
This type of issue was resolved in a later particl-market update, and should be fixed and resolved in a later v2.3 patch version.
There's also been significant changes to the v3.0 release, in terms of market and desktop functionality... this issue should also not be occurring in the v3.0 release either.
