### ISSUE TITLE
Give a hint that a user needs coins in public balances to list an item using the Import Listings tool

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1709]
Currently, when you have no coins in your public balance and try to list an item using the Import Listings tool, it just tells you that there was 1 or more errors estimating the fee for the listings. It doesn't tell you what these errors are. 

In my case, it was because I had no coins in my public balance. I suppose there might be other errors. Would be a good idea to say so in the error message that comes. 

Maybe a list of bullet points why it's not working or if it's really just about public coins, then maybe add a sentence that tells the user they need enough coins on their public balances, not just in their blind or anon balances. See screenshot below.

![19-February-2020-16:25:18](https://user-images.githubusercontent.com/27031337/74878000-6ff5b580-5334-11ea-9df8-616b3bdec87f.png)

**Comment by zaSmilingIdiot** [comment]
Will be resolved in v3.0

**Comment by zaSmilingIdiot** [comment]
From v3.0.0, places where fees are involved show the correct balance information on the window, for easier viewing of balance whether sufficient funds are available. Additionally, a choice is available via the market settings to be able to switch which balances fees are derived from (public funds or private/anon funds).

Closing.
