### ISSUE TITLE
linux: rename "Particl Desktop" binary to particl-desktop

### ISSUE THREAD

**Issue by DrDBanner** [particl/particl-desktop#1710]
**Describe the bug**
After a rpm installation on a clean and virgin fedora 29 & 31 VM on Qubes it is not possible to start Particl Desktop from the qemu launcher.  

**To Reproduce**

1. install fedora VM on Qubes
2. download particl-desktop-2.3.2-linux-x86_64.rpm
3. sudo dnf install particl-desktop-2.3.2-linux-x86_64.rpm
4. no error & application starts for the first time
5. stop the vm
6. start the vm from the QEMU launcher
5. which particl-desktop -> fails. Executable is named "Particl Desktop" and located in "/opt/Particl Desktop/"
5.5 which Particl Desktop -> fails
5.5.1 which "Particl Desktop" works

**The problem is the naming in the first place**

Calling an application from the commandline with a space in it and being forced to call it with paranthesis around it is to me very uncommon. The pure renaming cures that. 

**Versions (please complete the following information):**
 - OS: Fedora 29 & 31 x64 on Qubes 

**WORKAROUND**
opening the app from the terminal with 
`/opt/Particl\ Desktop/Particl\ Desktop`

**Comment by zaSmilingIdiot** [comment]
Should be finally resolved as of PD v3.3.0

The Linux build executable now follow standard naming convention and is named `particl-desktop` rather than `Particl Desktop`.
