### ISSUE TITLE
unable to mark as delivered in marketplace sale

### ISSUE THREAD

**Issue by mistersister85** [particl/particl-desktop#1711]
**Describe the bug**
All funds were in escrow. The seller shipped the item. Every time I would try to mark the package as delivered and put in my wallet password it gave an error message "missing inputs" I had several successful transactions before that with the same wallet. I thought my wallet was messed up so i created a new particl and recovered my wallet. I got my part back but the escrow was lost. 

**To Reproduce**
I basically just clicked the Mark as delivered button and put in my wallet password

**Expected behavior**
All of the other times I had completed a transaction it let me mark as delivered and enter my password then it released the funds as expected

**Screenshots**
Unfortunately i was unable to get a screen shot but its a small message that comes up at the bottom middle that says "missing inputs"

**Versions (please complete the following information):**
 - OS:  Windows 10 
 - Particl Desktop: v2.3.2
 - Particl Core: v0.18.1.7

**Additional context**
I worked things out with the seller. However I wanted to address this because it is dissappointing to lost some part after having so many successful transactions.

**Comment by zaSmilingIdiot** [comment]
have you had any occurrences of this issue using the latest Particl Desktop version, v3.0.0 ?

**Comment by zaSmilingIdiot** [comment]
Closing this for now, at least until there is some feedback on whether the issue persists in the v3 releases.
