### ISSUE TITLE
V3 - Filter not working while browsing Open market

### ISSUE THREAD

**Issue by pelssersconsultancy** [particl/particl-desktop#1736]
**Describe the bug**
While browsing open market, I first checked the category of several items and when I tried to filter items on those categories respectively no results were found.

**To Reproduce**
1. Go to 'Market'
2. Click on 'Browse'
3. Click on any item and inspect category of item.
4. Close the popup of item details
5. next select that same category in Filter
6. You see "Sorry, no matching listings found"

**Expected behavior**
I would expect to see at least 1 item with that caterogy

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. OSX BigSur 11.0.1 ]
 - Particl Desktop: [e.g. v3.0.0-RC-test002]
 - Particl Core: [e.g. v0.19.1.1]

**Comment by zaSmilingIdiot** [comment]
Thanks for reporting this. This is a known issue that is currently being addressed in the particl-market service/repo (and thus I'm noting that this is not a particl-desktop specific issue).

You're more than welcome to log this issue in the particl-market repo: https://github.com/particl/particl-market
