### ISSUE TITLE
V3: Accepting bid with too less funds has no qualified error message.

### ISSUE THREAD

**Issue by githubrsys** [particl/particl-desktop#1744]
**Describe the bug**
Accepting a bid, when having too less funds doesn't give a proper error message.

**To Reproduce**
1. Put listing more expensive than funds available
2. Try to accept a bid

**Expected behavior**
Change error message to: Order update failed: Not enough spendable funds available. 
Even better would be to disable the accept option and add a notification in proximity.

**Screenshots**
<img width="1623" alt="Bildschirmfoto 2020-12-29 um 15 55 33" src="https://user-images.githubusercontent.com/716689/103292700-a38e7b00-49ee-11eb-8fcc-a9f7545ce887.png">

**Comment by zaSmilingIdiot** [comment]
Error message will be updated accordingly.

**Comment by zaSmilingIdiot** [comment]
Closing: fixed for mainnet release of v3.0.0
