### ISSUE TITLE
V3 - No response to biddings

### ISSUE THREAD

**Issue by kangoala** [particl/particl-desktop#1745]
**Describe the bug**
I have six orders from which I know at least partially, that either the seller hasn't received my bids or I havn't received the sellers response to it.
I know from one seller who didn't received multiple biddings from different bidders and on different markets, but all have been bidding at around the same time. Later orders then passed through without a problem, and the seller could also accept those biddings. 

**To Reproduce**
Difficult to reproduce, but usually doesn't happen when both trading partners are "online" at the same time.

**Expected behavior**
Order messages are send and received in a more reliable way.

**Screenshots**
![Orders_can_not_further_proceed](https://user-images.githubusercontent.com/45103026/103378740-a4550900-4ae3-11eb-9bc2-7884659aee81.jpg)

**Versions (please complete the following information):**
 - Windows 10
 - Particl Testnet Desktop: 3.0.0-RC
 - Particl Core: 0.19.1.1

**Comment by kangoala** [comment]
I made now some other biddings (on Zombies), and this time the seller accepted all four biddings right away, but the old ones remain still in bidding status.

![Four_accepted_Zombie_biddings](https://user-images.githubusercontent.com/45103026/103380073-0b74bc80-4ae8-11eb-879c-6d6d23ca0ac5.jpg)

**Comment by zaSmilingIdiot** [comment]
Is this still an issue using the newer testnet client (RC005)?

**Comment by kangoala** [comment]
So far everything was fine with RC005. 👍
I guess this issue has been related to the fix with the "Listing Template Hashes" and thus hopefully has been solved. 🤞

I'm pretty optimistic and so I think we can close this issue 😁
