### ISSUE TITLE
V3 testnet - Chain will not start syncing after first launch, need to restart app for it to work (win10)

### ISSUE THREAD

**Issue by garbagiountilitisnt** [particl/particl-desktop#1747]
Windows 10, particl desktop V3 testnet.

Chain won't start syncing after initial fresh install of particl desktop v3.0 testnet (without having core installed, or any other files related to particl), need to restart application for the chain to start syncing.

**Comment by zaSmilingIdiot** [comment]
Syncing of the chain is a direct function of particl-core (ie: is not controlled or impacted in any way by external applications such as particl-desktop). Please log the issue in the particl-core repo: https://github.com/particl/particl-core
