### ISSUE TITLE
V3 testnet (minor UX) - Adjust message shown when closing application

### ISSUE THREAD

**Issue by garbagiountilitisnt** [particl/particl-desktop#1749]
![a2b329e48a0efa3ba8b7f291706239d4 - Copy](https://user-images.githubusercontent.com/76872776/103459184-3a896900-4d48-11eb-9bc8-67952f327163.png)

This message doesn't make sense/isn't clear enough, "Please wait"? For what exactly? I'm sure i can still use my computer while the app is shutting down. A better message while application is shutting down would be "Particl Desktop is now shutting down..." for example or "Particl desktop is shutting down momentarily". I hate nitpicking but the application itself is full of descriptive mistakes such as this one (although minor), more thought could be put into these to make the app feel more professional (more reports to follow). 

Also, i think the font differs from the font used in the application itself, not sure.

**Comment by zaSmilingIdiot** [comment]
This is nitpicking (and I'd argue nonsensical): the word "while" clearly provide the subject for the wait. In fact, the replacement suggestions phrase the statement in exactly the same frame but without the "please wait" wording preceding it. Hence, the claim that its confusing based on the "shutting down" statement is irrelevant as the replacements clearly use the same phrasing.

If the argument is that the "shutting down" phrasing is the source of the confusion then surely a better replacement should not include such words themselves, eg: a better replacement suggestion would be "closing". However, its clearly mentioned **what** 
 is closing/shutting down. Perhaps present a screenshot of this to others and ask them to describe the situation: a few tests conducted already have all successfully returned that an application appears to be closing (I've never had response come back thinking that the computer was shutting down). Now that is clearly anecdotal evidence, but even those barely literate on Windows have seen Windows indicating that "Windows is shutting down".

Unless there is significant support for such wording changes, I'll be leaving this as is. Also, if there are other such descriptive mistakes, please log them (you're welcome to include them together in a single issue)
