### ISSUE TITLE
V3 testnet - Include the blockchain as an optional download from github in mainnet installer

### ISSUE THREAD

**Issue by garbagiountilitisnt** [particl/particl-desktop#1750]
Many other projects provide a feature where the blockchain doesn't need to be synced from scratch but can be downloaded on the side from a source such as github. This can be integrated into the installation proces of particl desktop. I think this would help speed up things significantly and make using the marketplace/wallet for the first time a much more pleasant experience. Team/teammember can update the chain every few weeks and re-upload to github, for example when there is a new version of particl desktop.

**Comment by zaSmilingIdiot** [comment]
There will always been some syncing, even if its just a couple of blocks. But I suspect that this request also includes the requirement of syncing smsg, and I'd heavily oppose that idea as it provide for a possible history of older messages to remain around a lot longer than what they should (assuming its feasible to backup smsg).

Nevertheless, please log this issue at https://github.com/particl/particl-core as that is where any implementation of this request is likely to be maintained.
