### ISSUE TITLE
V3 bug reporting in native browser

### ISSUE THREAD

**Issue by DrDBanner** [particl/particl-desktop#1755]
**Is your feature request related to a problem? Please describe.**
When hitting "report bug" in PD a window without browser navigation gets opened and a user has to enter the credentials once more.

**Describe the solution you'd like**
Open this link in the standard browser of the user.

**Describe alternatives you've considered**
none.

**Additional context**
By applying this proposal experienced users don't get forced to enter their credentials once more and navigation is for inexperienced users more comfortable with the navigation tools from their day to day used browser.

**Comment by DrDBanner** [comment]
After visiting the "Help & Support" section I do tend to say: remove this completely. The user's taken away the browsing experience they are used to. No backwards, no forwards, no printing, no login with stored credentials in the native browser, and finally multiple link targets look like horror.

<img width="1193" alt="Bildschirmfoto 2021-01-05 um 18 18 07" src="https://user-images.githubusercontent.com/25568865/103677269-5e37f380-4f82-11eb-9ada-006094eabc25.png">

**Comment by zaSmilingIdiot** [comment]
The original request for external navigation to open in the user's browser, has been implemented.

**Comment by zaSmilingIdiot** [comment]
Closing: fixed for mainnet release of v3.0.0
