### ISSUE TITLE
V3 - sqlite errors - high cpu load - marketplace startup

### ISSUE THREAD

**Issue by DrDBanner** [particl/particl-desktop#1757]
**Describe the bug**
When the marketplace starts up it has tons of sqlite errors leading to high cpu load.

```
2021-01-05T16:00:59.250Z - error: [api/services/observer/ExpiredListingItemService] Failed to remove expired ListingItem (d16bf47a07eb11cf6b9f7e407a3cd2b15d33dccb96f854c73ea421e17517e490) on Market (pmktyVZshdMAQ6DPbbRXEFNGuzMbTMkqAA):  0=[errno=1, code=SQLITE_ERROR]
```

**To Reproduce**

1. Startup marketplace
2. Watch log & task manager

**Expected behavior**
No sqlite error appearance.

**Screenshots**

https://user-images.githubusercontent.com/25568865/103669181-51160700-4f78-11eb-9402-706c48fb3d2d.mp4

**Versions (please complete the following information):**
 - OS: [OSX 10.15.7]
 - Market 0.3.2
 - Core 0.19.1.1
 - Client 3.0.0-RC-test002

**Note**
This behaviour occours only on this particular machine. On another machine this problem is not present. This installation was from scratch. No additional attempts to fix this have been made.

**Comment by zaSmilingIdiot** [comment]
This is specifically related to particl-market... please log an issue there for resolution: https://github.com/particl/particl-market/issues
