### ISSUE TITLE
The Particl Marketplace failed to start correctly!

### ISSUE THREAD

**Issue by dislorth** [particl/particl-desktop#1772]
Hi guys.
I’m getting this error message once I start a Marketplace with particl-desktop-testnet-3.0.0-RC-test002-win-x64.zip:
**The Particl Marketplace failed to start correctly!
If you changed some settings recently, try reverting them back.**

![part-marketplace-bug-01](https://user-images.githubusercontent.com/560173/118348289-43205600-b517-11eb-9f01-b614a597e9da.png)

I’m just staring my marketplace for the first time. I always try “Restart the marketplace” button but it doesn’t work and still the same issue.

Even I added funds to my wallet from the Testnet Facuet but none of my PART are shown in my wallet but they are shown in the wallet explorer:

![part-marketplace-bug-02](https://user-images.githubusercontent.com/560173/118348282-3865c100-b517-11eb-9f41-e0fb63ae9add.png)

![part-marketplace-bug-03](https://user-images.githubusercontent.com/560173/118348284-3f8ccf00-b517-11eb-9e04-eda2cacee8d9.png)

![part-marketplace-bug-04](https://user-images.githubusercontent.com/560173/118348287-41ef2900-b517-11eb-815a-b1547acd0af0.png)

How can I fix this?
Can you please help me?
Thank you in advance.

**Comment by mahdi-ln** [comment]
Same problem with latest version. The .deb was working on Ubuntu but .appimage in Manjaro above error
Market:0.3.3
Core 0.19.2.16
Client 3.0.0

**Comment by mahdi-ln** [comment]
Tried linux binary, same problem
[terminal output.txt](https://github.com/particl/particl-desktop/files/7448173/terminal.output.txt)
[market.log](https://github.com/particl/particl-desktop/files/7448179/market.log)

**Comment by mahdi-ln** [comment]
deleting `~/.particl/particl-market` solved problem
I had moved files from another installation

**Comment by zaSmilingIdiot** [comment]
Closing as resolved by user...
