### ISSUE TITLE
Undesirable Item Appearing Twice, Can't Flag the Duplicate

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1773]
**Describe the bug**
An undesirable item has appeared twice at the same time on my client. I've flagged one as undesirable, but I can't flag the other. The market seems to think I already flagged the listing even though it's the duplicate. Unsure if the listing is actually duplicated in the market or it's just a display issue.

**To Reproduce**
1. Go to Browse
2. Flag one of the two "Free cocaine booster pack" listing
3. Try flagging the second one

**Expected behavior**
Was expecting PD to let me flag both items, OR, not display duplicates if it's actually just one listing and not really 2 independent ones.

**Screenshots**

![19-May-2021-11-33-53](https://user-images.githubusercontent.com/27031337/118841241-2462ec00-b896-11eb-8530-e95890c5cefc.png)

![19-May-2021-11-33-02](https://user-images.githubusercontent.com/27031337/118841246-25941900-b896-11eb-85ce-2ec2f377b2a2.png)

**Versions (please complete the following information):**
 - OS: Linux Mint (5.11.10-051110-generic)
 - Particl Desktop: 3.0.0-RC-test003
 - Particl Core: 0.19.2.8

**Comment by HenkSwardt** [comment]
Thank you

Task has been logged internally

**Comment by zaSmilingIdiot** [comment]
Closing: fixed for mainnet release of v3.0.0
