### ISSUE TITLE
Path of Items Bought on the Open Market is Marked as "ROOT"

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1774]
**Describe the bug**
When putting an item in one's cart, PD displays the path of the item being purchased (categories and sub-categories). The path, for items bought on the Open Market, is marked as "ROOT" which seems a bit counter-intuitive. Perhaps should be renamed as simply "Open Market".

**To Reproduce**
1. Put an item from the Open Market in your cart
2. Go to check out and check your cart before putting in your shipping address. It should show "ROOT".

**Expected behavior**
Something else showing other than "ROOT".

**Screenshots**

![19-May-2021-11-39-12](https://user-images.githubusercontent.com/27031337/118842382-26797a80-b897-11eb-93b6-5231a7b3fa6f.png)

**Versions (please complete the following information):**
 - OS: Linux Mint (5.11.10-051110-generic)
 - Particl Desktop: 3.0.0-RC-test003
 - Particl Core: 0.19.2.8

**Comment by cryptoguard** [comment]
Upon further investigation, it appears the same behavior is observed when putting items in your cart from other markets other than the Open Market.

In that case, it should probably display the name of the market instead of "ROOT", or then just taking away the "ROOT" part of the path entirely and only starting to show the path after the ROOT part. In the screenshot above, the path could simply start with "Health and Beauty".

**Comment by HenkSwardt** [comment]
Thank you

Issue has been logged internally

**Comment by zaSmilingIdiot** [comment]
Closing: fixed for mainnet release of v3.0.0
