### ISSUE TITLE
New MP listing fails fee estimation on free shipping.

### ISSUE THREAD

**Issue by localparticl-com** [particl/particl-desktop#1775]
**Describe the bug**
Fee estimation fails if both Local and International shipping are set to 0.

**To Reproduce**
1. Create a new product in Inventory & Products.
2. Set **both** local shipping and international shipping to a price of 0 PART.
3. Save and Publish
4. Select publishing period.
5. Error displayed: "There was an error fetching the fee estimate, please check that:"

**Expected behavior**
Publish Listing button should become available after selecting publish duration.

**Screenshots**
![particl desktop fee estimation on free shipping failure](https://user-images.githubusercontent.com/75868014/118907657-c7d2f180-b8d4-11eb-9ace-1a673a4ca923.png)

**Versions (please complete the following information):**
 - OS: MacOS 11.2.3, MacOS 10.13.6 
 - Particl Desktop: v3.0.0-RC-test003
 - Particl Core: v0.19.2.8

**Additional context**
Canceling out of the modal, changing either shipping value from 0, then clicking Update and Publish again will properly generate a fee estimation. After that - it is then possible to cancel out once again, change both shipping fields back to 0, and successfully publish a listing with free shipping.

**Comment by HenkSwardt** [comment]
Thank you, 

Issue has been logged internally for further investigation.

**Comment by zaSmilingIdiot** [comment]
Closing: fixed for mainnet release of v3.0.0
