### ISSUE TITLE
Accepting bid fails but still causes multiple soft-locks of the funds 

### ISSUE THREAD

**Issue by bacoinin** [particl/particl-desktop#1777]
**Describe the bug**
I can not accept the bid on one of my listings. Every time I attempt to do that a message pops up saying "Order update failed - dismiss" with the logs showing always the same thing:
"MPA_LISTING_ADD_03"
"MPA_BID_03"
followed by an error "No such mempool or blockchain transaction. Use gettransaction for wallet transactions."

see the gist that contains the logs from the terminal: 
https://gist.github.com/bacoinin/72c2ba4242602cb7b301e90f07985f9f

In addition, despite the "Order update failed" message, my wallet creates a "Converted -> Blind" transaction(s) everytime and soft locking the funds. In two occasions the soft-locked amount was wrong. 

See the wallet's debug.log:
https://gist.github.com/bacoinin/0abb4e22a1ce150b79cd6f730e8d8611 

**To Reproduce**
No idea how

**Expected behavior**
The bid to be accepted properly and the funds soft-locked only once

**Screenshots**
Can provide if needed

**Versions (please complete the following information):**
 - OS: Linux Debian 10
 - Particl Desktop: v3.0.0-RC-test003]
 - Particl Core: v0.19.2.9

**Additional context**
I have tried restarting the client, did not helped. 
I have used this particular client to successfully sell (BID->ESCROW->FINALIZE) another listing.
I have funds on both Anon and Public balances.

**Comment by HenkSwardt** [comment]
Thank you. 

Issue has been logged internally for investigation.

**Comment by zaSmilingIdiot** [comment]
Is this still a concern with the updated v3.0.0-RC-test004 release?

Possibly related to https://github.com/particl/particl-desktop/issues/1792

**Comment by zaSmilingIdiot** [comment]
Just checking in if this is still an issue?

**Comment by zaSmilingIdiot** [comment]
Closing: resolved
