### ISSUE TITLE
Staking and network stats not correct when not staking at all

### ISSUE THREAD

**Issue by coybigpart** [particl/particl-desktop#1779]
Go to your Wallet Overview:
![WalletOverview](https://user-images.githubusercontent.com/24685058/119811205-1e4cbb00-bee7-11eb-9d21-3c4aca804832.jpg)

When you haven't set up cold staking, the staking and network stats still displays your next reward and Your stake weight.
Stake weight should be 0.0% and Your next reward should be never.

**Comment by zaSmilingIdiot** [comment]
This is by design. It is not only when a wallet is cold staking that it is participating in staking: "hot" staking of a wallet is still possible. The staking statistics reflect this.

**Comment by coybigpart** [comment]
So you are automatically hot staking when you are online? Don't need to set up anything?

**Comment by coybigpart** [comment]
I will close this item. Never used hot staking. Cool that it's done automatically! Was only thinking about cold staking.
