### ISSUE TITLE
Testnet v3. Minor, help and support, textual correction

### ISSUE THREAD

**Issue by particularly7** [particl/particl-desktop#1782]
"As an alternative to Riot, we're also on discord" should be "As an alternative to Element, we're also on discord".
Also, you want element placed before (above) Discord if you describe it this way.

**Comment by particularly7** [comment]
Also at the top of the page:
"Particl is an open source project encouraging community **involvemetment**" 
correct "involvemetment" into "involvement"

**Comment by zaSmilingIdiot** [comment]
Nice catch. Both have been fixed.

**Comment by zaSmilingIdiot** [comment]
Closing: fixed for mainnet release of v3.0.0
