### ISSUE TITLE
Testnet v3. Minor, Particl marketplace disclaimer, textual corrections

### ISSUE THREAD

**Issue by particularly7** [particl/particl-desktop#1783]
Couple of corrections: (Window when clicking "The Particl Marketplace is still in development, use it at your own risk, click here for details".

* "This Pre-release version" I think its not a "Pre-release version" anymore.
* "At your own risks" in bold should be corrected into "At your own risk"
* This window is talking about "The Particl Foundation" at some point which is disbandoned and therefore shouldn't be mentioned

I think you would want to change "The Particl Marketplace is still in development, click for details....." into "The Particl Marketplace is under continuous development....", for example.

**Comment by particularly7** [comment]
The disclaimer window also talks about the, quote, "Open Marketplace" where i think you would want to generalize it to just "Particl Marketplace or Particl Desktop". Its Open + Private marketplaces in one

**Comment by zaSmilingIdiot** [comment]
Thanks for bringing these up.

The marketplace itself is still technically in a pre-release phase: its still technically pre version 1.0 (currently v0.3). While the version numbering itself might be irrelevant, the market release status itself is still considered a beta version, which implies a pre-release version as well.

The "Open Marketplace" term refers to the market system/service/functionality as a whole. The "marketplace" consists of multiple markets, one of which is the default "open market". There does seem to be a closeness between "Marketplace" and "Market", and this could probably be referred to differently in this context to avoid confusion.

Also, the rest of the spelling and grammar changes are noted and will fixed, thanks.

**Comment by zaSmilingIdiot** [comment]
Closing: fixed for mainnet release of v3.0.0
