### ISSUE TITLE
Testnet v3. Minor, Wallet Settings, textual correction

### ISSUE THREAD

**Issue by particularly7** [particl/particl-desktop#1784]
Change "For configuration of global app settings, click the settings icon in the **bottom right corner**" into "**bottom left corner**"

Sorry guys, i'm just going through all of these minor mistakes and keep logging them to clean things up lol

**Comment by zaSmilingIdiot** [comment]
Ah, yes, thank you! :)

And no worries at all about reporting these... you're welcome to continue submitting more as you find something :)
The more the better, as it all helps to clean and tidy up the application, as you pointed out.
Thanks for all the issues already logged! 👍

**Comment by zaSmilingIdiot** [comment]
Closing: fixed for mainnet release of v3.0.0
