### ISSUE TITLE
"Failed to publish the template" when paying from Anon balances and #Anon_outputs < 1 + #listing_images

### ISSUE THREAD

**Issue by bacoinin** [particl/particl-desktop#1786]
**Describe the bug**
When posting a listing with N number of images and paying the fee from Anon balances, if #Anon_outputs < 1 + #listing_images then the Particl Desktop produced "Failed to publish template error". All the visual elements indicate that the listing was not published, 

If one changes the tab and returns back then the status updates and it shows that the listing is being published which is actually true. The listing is published with only the first N images such that N=#Anon_outputs -1 

**To Reproduce**
1. Create N number of Anon outputs and set the listing fees to be paid from Anon balances
2. Create a template with M images such that M > N
3. Publish the template on some market

**Expected behavior**
The listing not to be published and a meaningful error explaining to the user that either they need more Anon outputs or either they need to remove some images.

**Screenshots**
Screenshots available upon request. Also see the "Another listing with multiple images" listing published on the Open Market

**Versions (please complete the following information):**
 - Particl Desktop: [v3.0 RC004]
 - Particl Core: [v0.19.2.12]

**Additional context**

**Comment by bacoinin** [comment]
Forgot to add that the published (on some market) listing is displayed with all the images if the client that published it views the market. In short the publisher will not know that the listing was only partially published (unless they count the number of the related txs or have another client to view the market where the listing was published).

**Comment by zaSmilingIdiot** [comment]
Looking into this

**Comment by zaSmilingIdiot** [comment]
A check has been added to the publish template modal window to help cater for this scenario.

If an insufficient number of utxos is detected to publish all the images as well, a warning is displayed to the seller indicating how to resolve the problem. The seller is still able to ignore the warning, but this requires them confirming their action by checking an additional tickbox (which then enables the publish button to be selected).

**Comment by zaSmilingIdiot** [comment]
Closing: fixed (as noted above) for mainnet release of v3.0.0
