### ISSUE TITLE
Visual notification for listings' Q/A updates

### ISSUE THREAD

**Issue by bacoinin** [particl/particl-desktop#1789]
**Is your feature request related to a problem? Please describe.**
If some one asks a question or replies to one, there is no visual indication for that in the PD. 

**Describe the solution you'd like**
Please add some sort of indicator that one has a question or their question has been answered in the listings Q/A se

**Describe alternatives you've considered**
The alternative is for the user to check all their listings regularly to see if they have questions or their questions have been replied

**Comment by zaSmilingIdiot** [comment]
I think at the moment the Comments and Review section is being treated as a makeshift Q&A section between the seller and one or more (potential) buyers. This is probably derived from how it was implemented in the v2 Particl Desktop, where it was in fact, intended as a Q&A section. 

However, this is not its intended usage in v3.0: the section is more for product reviews found on other popular sites. The ability for the seller to reply is intended as a means to afford the seller the option of replying to a review. 
With that in mind though, it means 2 things:
1. A proper implemented Q&A section is needed and currently missing. This is something discussed and will probably be implemented in some form or another going forward. Proper notifications and alerts on these types of communication messages should then be possible.
2. An alert of sort would be nice to have for the seller to know that a new review or comment on the item has been made. This is something to be looked at as well.

**Comment by zaSmilingIdiot** [comment]
Should now be implemented with the chat functionality added in v3.2
