### ISSUE TITLE
Add a New Order Rejection Reason

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#1794]
When rejecting an order, there is only the ability to provide "Out of stock" or "No reason provided" as reasons for the rejection. 

I propose adding "Does not ship to your location" as an option.

**Comment by HenkSwardt** [comment]
If the seller has set up the locations he ships to, the application wont allow an order to be placed if the location is not allowed. Wont this be a redundant feature then?

**Comment by cryptoguard** [comment]
Ah just realized multiple options could be filled, that's useful. Though, I will just leave a note (although I've already mentioned to Arnold) that the current CSV template does not allow to provide information for countries that a seller ships to. Would be useful for larger sellers to be able to list the country codes in the CSV.

**Comment by zaSmilingIdiot** [comment]
> the current CSV template does not allow to provide information for countries that a seller ships to

That should probably be in its own issue... you're welcome to create another issue to track this specifically :)
On the reported topic, @HenkSwardt 's summary is correct for the UI.
However, if there are additional 'reject" reasons, then these can be provided and added to the list if appropriate.

**Comment by zaSmilingIdiot** [comment]
Adding to this, the csv template import now does support providing a comma separated list of countries that can be shipped to in a `destination_countries` column.

**Comment by zaSmilingIdiot** [comment]
Closing: resolved for mainnet release of v3.0.0
