### ISSUE TITLE
Missing order request

### ISSUE THREAD

**Issue by kangoala** [particl/particl-desktop#1797]
Having put two orders into shopping cart and requested both of them at the same time. Both are showing up as requested on the buyer side, but only one of both do show up on the seller side as requesting.

Windows 10 (64bit)
Core: 0.19.2.12
Client: 3.0.0-RC-test004

![21-07_26-Missing_requested_order](https://user-images.githubusercontent.com/45103026/127015772-0b931122-47d8-45d9-89c8-9bccdcddf993.jpg)

**Comment by kangoala** [comment]
Ordering a second time could reproduce the results. Listing 9 have been requested and is shown up on seller side, while listing 6 again only is showing up on buyer side, and didn't got transfered as request to the seller.
![21-07_27-Missing_requested_order_reproduced](https://user-images.githubusercontent.com/45103026/127133263-eeede71f-c25b-48d9-a1bd-785662fe8538.jpg)

**Comment by zaSmilingIdiot** [comment]
Could be an issue with the sending/receiving of the smsg for that particular marketplace item.
Would you mind possibly sending me (privately, via discord or matrix) the market logs for each node so that it can be investigated?

**Comment by zaSmilingIdiot** [comment]
Marking this as a bug for now: will update based on the outcome of the investigation.

**Comment by kangoala** [comment]
@zaSmilingIdiot - I sent you a message on discord

**Comment by zaSmilingIdiot** [comment]
Were you able to test this using the latest testnet version `3.0.0-RC-test005`? It should be resolved in that release, but just want to confirm that it isn't still occurring?

**Comment by zaSmilingIdiot** [comment]
Were you able to test this using the latest testnet version `3.0.0-RC-test005`? It should be resolved in that release, but just want to confirm that it isn't still occurring?

**Comment by kangoala** [comment]
I just did some very short tests this time, but it seems to be solved and so everything looks really great. 😊
Thanks a lot! 👍👍👍
