### ISSUE TITLE
Entry "proxy=" remains in the particl.conf after disabling proxy via Particl Desktop 

### ISSUE THREAD

**Issue by bacoinin** [particl/particl-desktop#1798]
**Describe the bug**
If one enables proxy via the Particl Desktop e.g. 127.0.0.1:9050 and then disables it, the particl.conf still contains an incomplete line 
```
proxy=
```

**To Reproduce**
1. Enable proxy in Particl Desktop and restart the client. 
2. Disable the proxy and restart the client.
3. Go to Particl Core config dir and open the particl.conf file
4. Confirm that the proxy entry is present and incomplete

**Expected behavior**
The entire entry ```proxy=127.0.0.1:9050``` should have been deleted. 

**Versions (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Particl Desktop: [ v.3.0 RC004]
 - Particl Core: [v0.21.1.2]

**Additional context**
While the Particl Core 0.19.2.12 boots with the incomplete entry ```proxy=``` without complaining the newest v 0.21.1.2 will not boot (thank you @DrDBanner for discovering this)

**Comment by zaSmilingIdiot** [comment]
Thanks for mentioning this.

Keep in mind though that the Desktop (and for that matter Marketplace as well) have not yet been thoroughly tested to work with core v0.21 as yet. Some updates are already known to be needed, and a more formal update and testing process for use with the newer core version will happen once the current v3.0.0 PD has been released.

**Comment by zaSmilingIdiot** [comment]
Should be resolved as of Particl Desktop v3.3.0

v3.3.0 utilizes the CLI args when starting a particl core node, rather than attempting to edit the core node's .conf file, so there should be no further possibility that anything is erroneously left in the .conf file.
