### ISSUE TITLE
Manage Markets: Marketplace description text isn't selectable.

### ISSUE THREAD

**Issue by DrDBanner** [particl/particl-desktop#1802]
**Is your feature request related to a problem? Please describe.**
As a marketplace owner I want to promote an external chat for my marketplace. I add this information into the description field of my community marketplace. Currently, my clients can't select the text, hence they can't copy and paste it somewhere.

**Describe the solution you'd like**
Make description text selectable. 

**Describe alternatives you've considered**
Optionally, identify links and convert them to hyperlinks. Though, this could lead to misuse?

<img width="675" alt="Bildschirmfoto 2021-08-05 um 12 09 27" src="https://user-images.githubusercontent.com/25568865/128333541-66b23ba4-be0a-4a8a-bd8e-f43ac4b7a189.png">

**Comment by zaSmilingIdiot** [comment]
Done. A market's summary should be selectable in the next release.

**Comment by zaSmilingIdiot** [comment]
Closing: fixed for mainnet release of v3.0.0
