### ISSUE TITLE
 "Error while attempting to add the market"

### ISSUE THREAD

**Issue by agoraponic** [particl/particl-desktop#1811]
Creating a new market with an already existing market name returns "Error while attempting to add the market" on "Confirm & Create Market" action.  There is no clear indication of the reason why.

![new_market_error](https://user-images.githubusercontent.com/78703679/132697132-aa8c24e5-9a73-45ad-a56a-c08639f679b6.png)

Suggest:
![suggest_new_market_error](https://user-images.githubusercontent.com/78703679/132698184-57e5bbee-5be8-453c-9c83-b0a435f36b6a.png)

**Comment by zaSmilingIdiot** [comment]
A better error description for the error condition indicated has been implemented.

**Comment by zaSmilingIdiot** [comment]
Closing: fixed for mainnet release of v3.0.0
