### ISSUE TITLE
One-Time Split UTXO for public balance

### ISSUE THREAD

**Issue by kangoala** [particl/particl-desktop#1813]
When you load up your wallet with a single public transaction, you can't publish multiple listings at once, since your single UTXO is blocked for a limited time (waiting for confirmation). 

Maybe having a button which lets a single UTXO being split into several UTXOs like being done with the Private TXs in Wallet Settings would make it easier for newbies to publish multiple listings at once.

**Comment by zaSmilingIdiot** [comment]
An option to split utxos for transactions to public addresses has now been added. It defaults to 1 though (current implementation), and can be changed in the same area as the current stealth address utxo splitting option.

I do realize that this is not exactly intuitive at the moment: there's a better case to be made to use these values found in the Wallet Settings page as defaults, and have an input on the Wallet Send page available to be able to adjust it per transaction (ie: have the ability to change the split count value per transaction in the wallet send page). 
This is what the actual intention is going forward. However, its not available right now, moreso as a means to avoid potential complexity in how its presented to a user that may not really understand what the control's intention/usage is, and provides some time to find a decent way to present this control. I also don't want to be adding controls in right now prior to the release, and for the most part the current change at least provides the means to adjust utxo counts, even if it is clunky for those that want to adjust per transaction. 
But this can definitely be looked into and adjusted for in the next mainnet version.

**Comment by zaSmilingIdiot** [comment]
Closing: implemented (as per my previous comment) for mainnet release of v3.0.0
