### ISSUE TITLE
Creating a wallet first and then loading the marketplace module causes the application to freeze

### ISSUE THREAD

**Issue by bacoinin** [particl/particl-desktop#1815]
**Describe the bug**
If one runs the application for the first time and goes to the Wallet module to create the first wallet (automatically named "default wallet" then switching to the marketplace freezes the application. Freezes here means the GUI is completely unresponsive.

Restarting the application with first going to the Wallet module to unlock the "default wallet" or going directly into the Marketplace module, results in the same behaivior. The application GUI shows the "LAUNCHING THE MARKETPLACE" screen and freezes.

**To Reproduce**
1. Run the Particl Desktop Testnet executable for the first time
2. On the Welcome screen select the Wallet module
3. Create a new wallet, encrypt it and add a recovery password.
4. When done switch to the Marketplace module.

**Expected behavior**
The Marketplace module to load properly instead of the application GUI freezing

**Versions (please complete the following information):**
 - OS: Linux Ubuntu 20.04.2]
 - Particl Desktop: v0.3.0 RC005
 - Particl Core: v0.19.2.13

**Additional context**
Despite the fact that the application GUI is frozen, the Particl Desktop executable still consumes significant resources. I have allowed the application to stay frozen for over than 10 minutes and the resource consumption is not reduced.

**Log files**
[application.log](https://github.com/particl/particl-desktop/files/7179388/application.log)
[debug.log](https://github.com/particl/particl-desktop/files/7179390/debug.log)
[market.log](https://github.com/particl/particl-desktop/files/7179391/market.log)

**Comment by bacoinin** [comment]
I managed to reproduce the error a few times in a row after doing some additional tests and making sure that for each fresh install I was deleted all the PD related files (essentially leaving only the "blocks", "indexes" and "chainstate" folders in the Particl Core config directory /testnet), I have not manage to reproduce it again :man_shrugging:  

I will close this issue.

**Comment by zaSmilingIdiot** [comment]
There is a known case where this can be reproduced, but largely deals with "external" modification of files and folders related to the wallets used by the marketplace and the marketplace specific files/folders.
For this particular known case, it shouldn't be a problem that users should run into. But a fix is nevertheless being worked on to ensure that PD doesn't 'freeze' (which is the incorrect behaviour and should display an appropriate error while leaving the application responsive to the user).

I'm going to re-open this issue, more so for the tracking of the fix. Again, this isn't something considered a blocking issue, but it does need to be resolved regardless.

**Comment by zaSmilingIdiot** [comment]
Should now be fixed, as per this commit: d4c1854ff812eacba5b28a85eb262d1a0dcdd6d3

**Comment by zaSmilingIdiot** [comment]
Closing: fixed for mainnet release of v3.0.0
