### ISSUE TITLE
no listings on marketplace

### ISSUE THREAD

**Issue by mahdi-ln** [particl/particl-desktop#1819]
**Describe the bug**
no listings on the marketplace and there is no sign of progressing anywhere

**Screenshots**
![image](https://user-images.githubusercontent.com/27496531/136935137-38b6ca3e-77ca-4099-b958-e58fcf88d2af.png)

**Versions (please complete the following information):**
 - OS:  Linux Ubuntu 20.04
 - Particl Desktop: v3.0.0
 - Particl Core:  0.19.2.16

**Comment by mahdi-ln** [comment]
Now the problem solved. Definitely it is a connection problem

**Comment by zaSmilingIdiot** [comment]
As mentioned in similar discussions, the system is currently unaware whether there are no messages available or if there are messages but they have not been received yet. The system cannot know what it does not know.

What we can potentially implement here is an indication that displays when the blockchain is not fully synced AND there are no listings, which may address the case that the user may need to wait until the syncing process is complete. This should at least provide some feedback that the system may be waiting for listings to arrive still.

**Comment by zaSmilingIdiot** [comment]
The change to provide an indication that the blockchain is busy syncing, and thus no listings are available, was added in: f1546ffb49eff0ba998a7f0a8f3d2cf48590ef81 and released in v3.1.1
Closing issue due to completion of request.
