### ISSUE TITLE
Filter for search option

### ISSUE THREAD

**Issue by kangoala** [particl/particl-desktop#1822]
In PD v3.0 searching for listings, (for example in Open Market Browser), also show expired own listings. There should be a filter option to exclude expired listings from the search.

**Comment by zaSmilingIdiot** [comment]
The filter should not at all be returning listings that have expired, regardless of whether the listing is your own or not.

However, if a listing is retrieved and displayed in the screen, and subsequently expires, then it is not automatically removed for the results. This behaviour is to prevent various user interaction issues, such as having listings moving around while they are being viewed and potentially interacted with.

Can you confirm whether this is happening on a fresh load of the data? Perhaps also provide an indication of the time that the market page was opened and/or the request was first was made, when the listing was clicked on to view its details, and finally what the expiry time of such an expired listing is shown to be?

**Comment by kangoala** [comment]
I just gave it another trial and the expired listings still show up, despite they have initialy been listed in mid of october. I just sent you a message on discord as well.

**Comment by zaSmilingIdiot** [comment]
Thanks. Has been fixed in this commit:
https://github.com/zaSmilingIdiot/particl-market/commit/4cfdbf85c9aaa1aab91b228fd835b57531453c38

The fix will be in the new particl-market service release, which will be included in the next release of particl-desktop.

**Comment by zaSmilingIdiot** [comment]
added in v3.1
