### ISSUE TITLE
DEB package dpkg installation dependency issue: libappindicator3-1

### ISSUE THREAD

**Issue by johnbaptist-42** [particl/particl-desktop#1824]
**Bug** Many DEB install packages have been running into issues with libappindicator3-1.

**To Reproduce**
1. Go to Terminal
2. cd to Downloads
3. sudo dpkg -i particl-desktop-3.0.0-linux-amd64.deb
4. Error: 
dpkg: dependency problems prevent configuration of particl-desktop:
particl-desktop depends on libappindicator3-1; however:
Package libappindicator3-1 is not installed.

**Expected behavior**
Expected install. However, many DEB packages have been running into issues with libappindicator3-1 dependencies. Unpacking and repacking the DEB package, replacing dependency _libappindicator3-1_ with dependency _libayatana-appindicator_ has worked for me on many other DEB packages. 

**Screenshots**
![image](https://user-images.githubusercontent.com/91354246/143091101-a944a80e-b36b-4d3b-8290-75655a3b2b37.png)

**Versions (please complete the following information):**
 - OS: 5.14.0-kali4-amd64
 - Particl DEB: particl-desktop-3.0.0-linux-amd64

**Additional context**
I keep seeing on forums from a couple of years ago that Debian developers were encouraging this same switch of dependencies. Not sure how many got the word. I fixed IPFS install by using the same unpack, repack method. GH link to overall issue found [HERE](https://github.com/NixOS/nixpkgs/issues/96420)

**Comment by zaSmilingIdiot** [comment]
Will investigate. Thanks for raising this.

**Comment by zaSmilingIdiot** [comment]
Should be resolved as of v3.3.0
