### ISSUE TITLE
error Command "package:linux" not found.

### ISSUE THREAD

**Issue by mahdi-ln** [particl/particl-desktop#1832]
```
[m@m-pc particl-desktop]$ yarn run package:linux
yarn run v1.22.17
error Command "package:linux" not found.
```

**Versions (please complete the following information):**
 - Particl Desktop: [12db119](https://github.com/particl/particl-desktop/commit/12db119b19748a1ed310f23cf049e9c40948efe0)

**Comment by zaSmilingIdiot** [comment]
As mentioned on the releases page, the code for the Particl Desktop is not currently displayed in this repository. Its the reason why it will not build currently.
We are looking to make the code public shortly, but in the meanwhile, you are welcome to contact one of the team members for access to the PD code; see team members at [particl.io website](https://particl.io/about)
