### ISSUE TITLE
hide balance in overview (presentation mode)

### ISSUE THREAD

**Issue by SativaL** [particl/particl-desktop#325]
Could you guys integrate such a function to hide the Main Balances ? like in Blockfolio (maybe necessary if you doing trades in public for example) (option able in the head top right just a small greyish thing that hide balance when clicked)

**Comment by kewde** [comment]
What about the transactions? They also reveal information about the balance etc

**Comment by SativaL** [comment]
yes but currently there are only stake rewards which are fine, maybe we can implement this in the future. Not that necessary, maybe some people like it.

**Comment by allienworks** [comment]
Is that really needed? For presentation purposes, running on testnet might be enough.. Or if you want this for creating e.g. some tutorial videos etc., you can always create a new virtual machine and send some change there. I honestly think that the work needed for this isn't worth the outcome when there are many "workarounds".

**Comment by pciavald** [comment]
I don't think this is needed at the moment.
