### ISSUE TITLE
GUI wallet sometimes automatically locks by itself

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl-desktop#386]
I have found this issue happening about 4 or 5 times since I've been staking on GUI this week waiting for my cold staking node to be 100% completed. I will unlock the wallet for staking only, and then it will randomly lock itself. I have had it happen after 10 minutes of being unlocked, and sometimes have gone for days without locking itself. 

It happened today while I was sleeping, it had been unlocked for staking for about 2 or 3 days of staking. Unsure what is causing this.

**Comment by cryptoguard** [comment]
Just want to add...

When I say "locks itself out", I mean going from a state of "Unlocked for staking" to "locked", meaning staking seizes.

**Comment by pciavald** [comment]
Wow, that is strange. Can you please launch from the command line `./particl -printtoconsole` to keep the logs displayed, and paste it next time it locks itself ? Thank you.

**Comment by cryptoguard** [comment]
I installed with .deb

Can I just do particl -printtoconsole ?

**Comment by cryptoguard** [comment]
It just did it again by the way after I ran "particl -printtoconsole". How can I retrieve the log?

**Comment by pciavald** [comment]
didnt the log appear on console ?

**Comment by cryptoguard** [comment]
It did not

**Comment by cryptoguard** [comment]
[14:35:44.658] [debug] could not find cookie file! path: /root/.particl/.cookie
[14:35:44.837] [debug] Daemon not running. It will be started bt the daemon manager
Initializing...
Resolving path to client binary ...
Platform: linux
Client binary path: /root/.config/Particl Wallet/particld/unpacked/particld
Checking for new client binaries config from: https://raw.githubusercontent.com/particl/partgui/master/modules/clientBinaries/clientBinaries.json
Status: loadConfig - Fetching remote client config
Status: loadConfig - Fetching local config
No "skippedNodeVersion.json" found.
Status: scanning - Scanning for binaries
Initializing Manager...
Resolving platform...
Calculating possible clients...
1 possible clients.
Verifying status of all 1 possible clients...
Verify particld status ...
particld binary name: particld
Exec: "which particld"
Command particld not found in path.
Checking for particld binary in /root/.config/Particl Wallet/particld/unpacked ...
Got optional folder binary for particld: /root/.config/Particl Wallet/particld/unpacked/particld
Running particld sanity check for binary: /root/.config/Particl Wallet/particld/unpacked/particld ...
particld binary path: /root/.config/Particl Wallet/particld/unpacked/particld
Checking for particld sanity check ...
Checking sanity for particld ...
Exec: "/root/.config/Particl Wallet/particld/unpacked/particld -version"
Sanity check output: Particl Core Daemon version v0.15.0.4.0-993ad0c
Copyright (C) 2009-2017 The Particl Core developers
Copyright (C) 2009-2017 The Bitcoin Core developers

Please contribute if you find Particl Core useful. Visit <https://particl.io/>
for further information about the software.
The source code is available from <https://github.com/particl/particl-core>.

This is experimental software.
Distributed under the MIT software license, see the accompanying file COPYING
or <https://opensource.org/licenses/MIT>

This product includes software developed by the OpenSSL Project for use in the
OpenSSL Toolkit <https://www.openssl.org> and cryptographic software written by
Eric Young and UPnP software written by Thomas Bernard.

Sanity check passed for /root/.config/Particl Wallet/particld/unpacked/particld
Status: filtering - Filtering available clients
Status: done - undefined
[14:35:44.987] [debug] could not find cookie file! path: /root/.particl/.cookie
starting daemon /root/.config/Particl Wallet/particld/unpacked/particld

**Comment by cryptoguard** [comment]
But I get this same log when running particl without -printtoconsole so I doubt it's the right output

**Comment by pciavald** [comment]
that is the log. But i need it complete and if possible between 3 `

**Comment by cryptoguard** [comment]
I've pasted everything that is displayed after I entered particl -printtoconsole

**Comment by pciavald** [comment]
mhh, i'm not used to the packaged version, i don't know why the `printtoconsole` flag is not being passed to the daemon. I'll get back to you.

**Comment by cryptoguard** [comment]
Ok thanks! 

Note that the GUI was fine and not locking itself out since my initial issue submission. But somehow my laptop ran out of battery and when I booted back on and started GUI, it did lock itself out less than 5 minutes after I unlocked it for staking. 

I find that it will happen more often when I will boot my VM and start GUI for the first time. It would happen 5 to 10 minutes after unlocking.

Also, just while I was writing this comment my GUI crashed and gave me the following error: 

Uncaught Exception:
Error: Object has been destroyed
    at WebContents.send (/opt/Particl Wallet/resources/electron.asar/browser/api/web-contents.js:95:15)
    at SafeSubscriber.observable.subscribe [as _error] (/opt/Particl Wallet/resources/app.asar/node_modules/rx-ipc-electron/lib/rx-ipc.js:48:25)
    at SafeSubscriber.__tryOrUnsub (/opt/Particl Wallet/resources/app.asar/node_modules/rxjs/Subscriber.js:238:16)
    at SafeSubscriber.error (/opt/Particl Wallet/resources/app.asar/node_modules/rxjs/Subscriber.js:197:26)
    at Subscriber._error (/opt/Particl Wallet/resources/app.asar/node_modules/rxjs/Subscriber.js:128:26)
    at Subscriber.error (/opt/Particl Wallet/resources/app.asar/node_modules/rxjs/Subscriber.js:102:18)
    at rpcCall (/opt/Particl Wallet/resources/app.asar/modules/rpc/rpc.js:120:22)
    at ClientRequest.request.on.error (/opt/Particl Wallet/resources/app.asar/modules/rpc/rpc.js:72:9)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketCloseListener (_http_client.js:334:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at TCP._handle.close [as _onclose] (net.js:510:12)

It may or may not be related, but within the GUI it said cannot connect to daemon just before crashing, but I did not have the time to copy the error message.

**Comment by pciavald** [comment]
Yes, unrelated error. This is already documented in #305. Thank you for the insight.

**Comment by HenkSwardt** [comment]
@vikas-cis has been assigned to this issue

**Comment by vikas-cis** [comment]
@HenkSwardt  I have gone through the issue  and I have tested but couldn't able to reproduce it at windows

OS: Windows7

**Comment by pciavald** [comment]
@cryptoguard is it still true on the latest `dev` branch ?

**Comment by cryptoguard** [comment]
I will test this hopefully tomorrow and let you know!

**Comment by cryptoguard** [comment]
I'm running into some issues compiling the latest dev branch. I've messaged you on Riot.

**Comment by HenkSwardt** [comment]
@pciavald : I have just experienced this issue again now while testing the GUI on TestNet. Unfortunately, I did not launch with "printconsole" Will relaunch and test again.

**Comment by pciavald** [comment]
I had it tonight too but it's not clear from the logs what happened.. I'm a bit lost on this one, I have no clue what could be causing this. @kewde help !

**Comment by pciavald** [comment]
@anandsinghparihar i've just clarified this issue.

- start wallet
- unlock for staking only
- wait 5min
- wallet is locked again
- unlock for staking only
- wallet stays unlocked

Can you check why unlocking for staking only sets a timer on 5min just like the full unlock ?

**Comment by anandsinghparihar** [comment]
@pciavald I'll check it

**Comment by HenkSwardt** [comment]
@pciavald 

I have tested this over the past week and couldn't get my wallet to lock once.Have seen it in the past as well, but no luck over the past week.

Not sure how to trace this one at this stage.

**Comment by anandsinghparihar** [comment]
@pciavald I also tried to reproduce the same issue, but no luck.

**Comment by allienworks** [comment]
I haven't encountered this lately as well. Seems fixed already.

**Comment by pciavald** [comment]
fixed
