### ISSUE TITLE
internal transfer narration not displayed

### ISSUE THREAD

**Issue by pciavald** [particl/particl-desktop#411]
Following #357, PART to BLIND transactions' narration is not displayed because of the Transaction model using listtransactions instead of filtertransaction.

**Comment by pciavald** [comment]
maybe fixed, waiting for #496

**Comment by anandsinghparihar** [comment]
PR: #520

**Comment by anandsinghparihar** [comment]
@pciavald could you please check API endpoints why narration text not returns if we did balance transfer

**Comment by pciavald** [comment]
dupe of #636
