### ISSUE TITLE
Graphs for balances/staking

### ISSUE THREAD

**Issue by AllienWorks** [particl/particl-desktop#414]
Suggestion to implement this library for including graphs - http://krispo.github.io/angular-nvd3/ as we talked about it with @gerlofvanek (based on his initial designs).

Could be used for various widgets:

- voting
- staking info (number of stakes per day/month etc.)
- balance amounts
- sent/received TXs in History tab

Would be surely handy for marketplace in the future as well.

**Comment by rynomster** [comment]
That library looks like it's for angularJS and not angular. The graphs are pretty cool though

**Comment by allienworks** [comment]
@rynomster there's one for Angular2+ as well: https://github.com/krispo/ng2-nvd3

**Comment by EagleEye25** [comment]
will look into this at another time, after 1.1 release

**Comment by pciavald** [comment]
I think it's a bit heavy for 1.2 actually... we should speed up releases.

**Comment by zaSmilingIdiot** [comment]
Closing this due to age and relevance.
For reference, the lib mentioned has been included in the v2.x release for graphing purposes.
