### ISSUE TITLE
smart ZAP

### ISSUE THREAD

**Issue by HenkSwardt** [particl/particl-desktop#513]
ZAP Functionality.

This needs to cover a few different scenarios, so likely needs more planning before jumping into it.

a. User wants to quickly activate Cold Staking
b. User has balance < 1000 PART
c. User is at 90%+ Activation and now the last % are taking a long time.

a.
User wants to quickly activate Cold Staking (does not care so much about privacy loss at this stage)
In this case the wallet should prompt the user to Zap his wallet which will send all the funds back to itself but on a single cold stake output. This will immediately Enable Cold Staking.

b.
User has balance < 1000 PART
In this case we advise the user that the default Cold Staking process may take considerable time and therefore we advise to force the activation. This would follow the same process as above.

c. 
User is at 90%+ Activation and now the last % are taking a long time.
In this case the user gets to a high % of activation but the rest of the outputs are all small .. say <500 PART - the wallet knows this last few % could take months so it prompts the user to ZAP the last few outputs (small loss of privacy).

**Comment by pciavald** [comment]
*note*
consider scenarii in #521

**Comment by pciavald** [comment]
zapping functionality was added in #609. Letting this open to consider a more advanced way of doing it.

**Comment by pciavald** [comment]
@HenkSwardt @dasource are we sure we need that behaviour or are we good with a simple zap / disable ?

**Comment by HenkSwardt** [comment]
We need to discuss this and maybe flesh it out more if we need to. The main requirements of this task has been added.

**Comment by zaSmilingIdiot** [comment]
Closing due to age and relevance.
Primary request has been implemented... further functionality can be discussed in its own separate issue once defined.
