### ISSUE TITLE
Move Daemon client/GUI version to "About" or info symbol in top bar (suggestion)

### ISSUE THREAD

**Issue by kapsr** [particl/particl-desktop#515]
To keep the design of the GUI as clean as possible, maybe its best to move the Daemon client version and GUI version text to some place where its hidden. You could make an info button next to the cold staking/peers buttons for example. 

You could also implement a similar menu with an "About" option as SLACK has where additional info can be accessed, such as a link to Particl WIKI/Github et cetera. 

![v](https://user-images.githubusercontent.com/32437236/34046147-522de8d4-e1ac-11e7-80a7-4775c0f939c7.png)

**Comment by allienworks** [comment]
I don't personally think we should hide it. If it would be hidden, users will not know that they're running outdated version.. Of cource, that will become obsolete when the wallet auto-update is implemented.

**Comment by pciavald** [comment]
closing for now as it's not a priority and there's no consensus about it
