### ISSUE TITLE
Send payment/balance transfer - Icon for deleting recipient address matches close window icon

### ISSUE THREAD

**Issue by kapsr** [particl/particl-desktop#519]
![34070754-d12d6430-e291-11e7-8e3b-40c04cbb628d](https://user-images.githubusercontent.com/32437236/34070896-8bde9e90-e26d-11e7-9544-87222d4e7848.png)

I think you would want to use a different icon here than the icon used now which is also used for closing windows in the GUI. Rather use a black colored bin for example. 

![54758](https://user-images.githubusercontent.com/32437236/34070918-febb2d66-e26d-11e7-803c-29e9cda82862.png)

**Comment by pciavald** [comment]
@allienworks
