### ISSUE TITLE
history search field searches only address

### ISSUE THREAD

**Issue by pciavald** [particl/particl-desktop#592]
In the history tab, text search is only effective on addresses while it should be effective on amount, txid, narration etc.

**Comment by anandsinghparihar** [comment]
@pciavald prams proper send from API, i guess API need to be change ?

**Comment by pciavald** [comment]
@anandsinghparihar can you please comment out the text search field, we'll investigate it for 1.2

**Comment by anandsinghparihar** [comment]
@pciavald 
filters pram: 
`{
      category: 'all',
      type:     'all',
      sort:     'time',
      search:   ''
    }`

if we pass any string in `search`  pram, then it should be checked with all tx record.

**Comment by anandsinghparihar** [comment]
@pciavald waiting for API change !!

**Comment by zaSmilingIdiot** [comment]
Closing: this no longer seems to be applicable, at least since later v2.x releases, and v3, don't cater to text search in the History tab.
