### ISSUE TITLE
unable to launch after changing datadir

### ISSUE THREAD

**Issue by bb2k16** [particl/particl-desktop#603]
# Describe bug/issue

Changing datadir result in crash

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. create shortcut to Particl Wallet.exe
2. add **-datadir=**_folderpath_
3. launch Wallet from shortcut

![image](https://user-images.githubusercontent.com/22429074/34638296-81ca26a0-f2c0-11e7-8d39-867bece8d51b.png)

# More information

- Operating system and version: Win10 x64
- Client version: 1.0.0

**Comment by vikas-cis** [comment]
@HenkSwardt  I have tested Particl Desktop v1.1.0-RC4 latest release and try the following steps and couldn't able to reproduce the issue 

1)After installation I ran the shortcut directly from desktop its working.
2) I also tested via terminal as well

**Comment by anandsinghparihar** [comment]
fixed in new release : https://github.com/particl/particl-desktop/releases
