### ISSUE TITLE
automatically zap incoming transactions

### ISSUE THREAD

**Issue by pciavald** [particl/particl-desktop#621]
We should provide a way to automagically zap incoming transactions to cold staking.

Example :

- receive 10 PART
- it's not going to stake anytime soon
- zap to cold staking

**Comment by zaSmilingIdiot** [comment]
This may not make for a good experience. 

The user should be able to determine whether to zap incoming funds automatically and such functionality would need to be configurable (via settings), and would only apply when the user started the particular wallet (and unlocked it if it was encrypted). This latter requirement makes it needlessly complicated, and so until the wallet is redesigned to separate the cold staking functionality out of the main wallet, and there is a decent means for performing/delegating this functionality to occur automatically, this may not be a good experience.
