### ISSUE TITLE
Daemon seems to "die" on create/restore wallet

### ISSUE THREAD

**Issue by EagleEye25** [particl/particl-desktop#623]
# Describe bug/issue
When creating or restoring a wallet the daemon appears to "die" in the backend resulting in:
![ss 2018-01-09 at 11 03 50](https://user-images.githubusercontent.com/28861857/34713021-93d86bc6-f52d-11e7-8964-6808f1e2c1c3.png)
after pressing next again results in:
![ss 2018-01-09 at 11 05 39](https://user-images.githubusercontent.com/28861857/34713040-a1256996-f52d-11e7-812e-c1fee03e2fd7.png)
with the wallet being loaded without confirmation

# How to reproduce
1. .. go through procedure to create or restore wallet
# More information
- Operating system and version: windows 7 (x64)
- Client version:1.1.0

**Comment by kewde** [comment]
Can you post a log of the output generated by the npm run:electron..?
I think the same happens when encrypting the wallet.
Also when a reindex needs to happens, it seems to kill the daemon.

**Comment by HenkSwardt** [comment]
Closed in favor of duplicate #739
