### ISSUE TITLE
GUI Console window Error: JSON value is not an integer as expected

### ISSUE THREAD

**Issue by HenkSwardt** [particl/particl-desktop#628]
When trying to run the "scanchain 0" command using the GUI console window I aam presented with the following error:

JSON value is not an integer as expected

Please have a look at what we need to change to allow for full function use of the GUI console. When running "scanchain 0", the "0" needs to be sent as an integer and not as a string.

**Comment by vikas-cis** [comment]
@HenkSwardt  I had a discussion with kewde and I am creating the list of commands that giving issues on the basis of that it can be fixed in particl-core
Thanks

**Comment by vikas-cis** [comment]
@kewde I have gone through all the commands and found below commands which are failing and giving the error "JSON value is not an integer as expected "
getblockhash height
getmempoolancestors txid (verbose)
getmempooldescendants txid (verbose)
getmempoolentry txid
generate nblocks ( maxtries )
generatetoaddress nblocks address (maxtries)
scanchain [fromHeight]

**Comment by pciavald** [comment]
args seem to be converted to strings before being sent to RPC ? for instance sending `deriverangekeys 1 1 pkey` returns that ant integer value was expected

**Comment by HenkSwardt** [comment]
We have tested this in Dev and seems that a change made to the back end has resolved the issue.

![image](https://user-images.githubusercontent.com/28799964/35726814-d8424978-080e-11e8-9549-3cc9a4bafab0.png)

Please can we just add a disable to Keyboard enter as well as the enter button while the request is being handled. This will be to prevent multiple submits on processes that might need some time to return data via the API.

Thank you

**Comment by vikas-cis** [comment]
@HenkSwardt sure :)

**Comment by HenkSwardt** [comment]
Issue has been resolved and merged
