### ISSUE TITLE
some transactions do not have an address

### ISSUE THREAD

**Issue by pciavald** [particl/particl-desktop#629]
After zaping the balance, reopening the wallet gives an infinite loader with no transaction displayed.

After making 1 transaction, only this transaction appears.

Using `filtertransactions` we can see all transactions so there must be some kind of bug in the GUI that breaks logic after zapping.

**Comment by pciavald** [comment]
zaping the balance results in a transaction that doesn't seem to have any outputs.
https://github.com/particl/partgui/blob/dev/src/app/wallet/wallet/shared/transaction.model.ts#L36
check filtertransactions.

**Comment by pciavald** [comment]
temporarily fixed in #609

**Comment by HenkSwardt** [comment]
Look into this after #769 has been merged
