### ISSUE TITLE
decrypt wallet modal sometimes does not auto-close

### ISSUE THREAD

**Issue by pciavald** [particl/particl-desktop#635]
It happened to me several times when unlocking the wallet, that the wallet unlocks but the modal stays open.

**Comment by HenkSwardt** [comment]
@EagleEye25 will investigate this one for us.

**Comment by EagleEye25** [comment]
havent been able to reproduce the issue

**Comment by EagleEye25** [comment]
https://github.com/particl/partgui/pull/675 possible fix? please review and inform me. @pciavald

**Comment by pciavald** [comment]
fixed
