### ISSUE TITLE
Display fees when sending TX

### ISSUE THREAD

**Issue by AllienWorks** [particl/particl-desktop#637]
We're currently displaying quite plain modal:

![](https://i.imgur.com/etN1zqB.png)

It's missing quite a lot:

- display TX fee
- total TX amount (sending + fee)
- _nice to have:_ when address in Address book, display it's label
- _nice to have:_ inform about public/private TX type and its implications
- nice styling ;)

I wanted to style it before, but it's all displayed via `{{ dialogContent }}`, so I can't touch the separate things (like TX amount, address etc.). If you could add to these things separate classes, that would be amazing.

If some would implement these features above, I'll take over then and tweak it all etc.

**Comment by kewde** [comment]
API fully supports estimating fees.
