### ISSUE TITLE
mac dmg background not set

### ISSUE THREAD

**Issue by pciavald** [particl/particl-desktop#684]
<img width="545" alt="capture d ecran 2018-01-16 a 20 11 28" src="https://user-images.githubusercontent.com/3384097/35008176-e652b5fe-fafb-11e7-89ea-6c4b8de8cd18.png">

**Comment by vikas-cis** [comment]
@allienworks @gerlofvanek can you please tell me which image  we can use for background ?

**Comment by gerlofvanek** [comment]
<img alt="" src="https://i.imgur.com/dzJFAq2.png">

**Comment by vikas-cis** [comment]
@gerlofvanek Is the image is added ?

Thanks

**Comment by vikas-cis** [comment]
@pciavald @gerlofvanek  Please have a look the screenshot this how it looks now after adding the background image in mac
![screen shot 2018-01-29 at 4 27 45 pm](https://user-images.githubusercontent.com/20254889/35507051-7ceb2fea-0511-11e8-8366-914fa3431f36.png)
