### ISSUE TITLE
Modal design issue in Linux build 

### ISSUE THREAD

**Issue by anandsinghparihar** [particl/particl-desktop#694]
@allienworks I've created a build using latest code and I found following design issue, I guess Vikas is already reported that issue in Mac but the same issue is in Ubuntu as well. 
![screenshot from 2018-01-17 21-39-58](https://user-images.githubusercontent.com/17725557/35053228-82223260-fbcf-11e7-882a-5a6b3a74a582.png)
![screenshot from 2018-01-17 21-37-35](https://user-images.githubusercontent.com/17725557/35053229-824c291c-fbcf-11e7-801f-b265e2d5d43a.png)
![screenshot from 2018-01-17 21-36-45](https://user-images.githubusercontent.com/17725557/35053230-82739a10-fbcf-11e7-99f1-ad6f0f7c4629.png)

**Comment by allienworks** [comment]
Which "latest code"? I just tried running Particl 1.1.0-RC1 (internal build in releases) and everything is fine.

**Comment by allienworks** [comment]
@anandsinghparihar I've packaged the latest `dev` code as you suggested to test this issue and I still can't reproduce your problems. I'm using the `tar.gz` version (not the `deb` one as I don't have Ubuntu-based distro), so not sure if that's the reason.

Or it all might be related to the missing `package.lock` that has been removed. I can zip and send you my `node_modules` to try it. It's just weird that only you guys are having these issues (and we don't).

**Comment by vikas-cis** [comment]
![screen shot 2018-01-18 at 2 41 41 pm](https://user-images.githubusercontent.com/20254889/35089724-d415321e-fc5d-11e7-9be2-5ab16490f831.png)
Particl 1.1.0-RC1 (testnet) (internal)

**Comment by HenkSwardt** [comment]
Please note, as per #753, this issue also affects the Mac build

**Comment by HenkSwardt** [comment]
Relating Development task: #758

**Comment by anandsinghparihar** [comment]
@allienworks  I've test `release/1.1.0` its working fine in Ubuntu (I tested it on 2 different machines) I cant see that modal issue now in Ubuntu. we can close this issue

**Comment by anandsinghparihar** [comment]
this issue is no more in **Ubuntu** so I am going to close it but this may be still in **MAC** which we considered in `modal refactoring task`.
