### ISSUE TITLE
app not quitting when daemon started before

### ISSUE THREAD

**Issue by pciavald** [particl/particl-desktop#704]
- start daemon
- launch app
- right click app in dock, Quit (mac) or close window
- app does not quit until we manually ctrl-C

**Comment by EagleEye25** [comment]
i cant seem to reproduce this issue @pciavald @HenkSwardt : 
![testing](https://user-images.githubusercontent.com/28861857/35264017-bd147c9a-0023-11e8-9fba-afa1a21d01dc.gif)
is there possibly anything else that i can do, to reproduce it?

**Comment by pciavald** [comment]
you need to start the daemon before the GUI to reproduce the issue

**Comment by kewde** [comment]
Is this Mac-only? Dev works fine on Linux..
