### ISSUE TITLE
Ctrl+V is not working on mac

### ISSUE THREAD

**Issue by vikas-cis** [particl/particl-desktop#710]
How to Reproduce

1)Initialize the wallet
2)Create wallet 
3)Copy all the mnemonics
4)Try to fill vacants mnemonics using Ctrl+V
I have tested in Particl 1.1.0-RC1 (testnet) (internal)
I have also created build from dev and tested, Having same issue 

Thanks

**Comment by pciavald** [comment]
on mac it's command-V

**Comment by pciavald** [comment]
I tried to paste a word in the vacant mnemonics on mac using `command+v` and I confirm it does not work.

**Comment by vikas-cis** [comment]
#740
