### ISSUE TITLE
Can't create wallet without Recovery Pass

### ISSUE THREAD

**Issue by allienworks** [particl/particl-desktop#715]
- Branch: `release/1.1.0-RC2`
- Commit: 77d57fc8810a3f4c7eb05713c6b293941d86b6ed
- OS: Linux Manjaro (Arch-based)

When creating new wallet, on "Choose a recovery password" page, it's not possible to advance to next step _without_ specifying optional Recovery Password.

If Pass isn't entered, clicking on _Next_ button outputs this to console:
```
(display.js:43)
createwallet.component   passwordFromEmitter: undefined undefined 
createwallet.component   passwordFromEmitter: undefined true
```

Preview:

![](https://i.imgur.com/WEQF9Ol.gif)

**Comment by anandsinghparihar** [comment]
PR: https://github.com/particl/particl-desktop/pull/716

**Comment by pciavald** [comment]
## this issue is still present

![peek 2018-01-19 14-08](https://user-images.githubusercontent.com/3384097/35152371-77e49e24-fd22-11e7-828f-a95518ba69b8.gif)

**Comment by pciavald** [comment]
@EagleEye25

**Comment by EagleEye25** [comment]
fixed. https://github.com/particl/particl-desktop/pull/726 
![fix](https://user-images.githubusercontent.com/28861857/35153364-ef778d28-fd2e-11e7-841c-1302b4def940.gif)

**Comment by vikas-cis** [comment]
#716 It was already fixed here I guess ?
