### ISSUE TITLE
Daemon not able to figure out if wallet exists or not

### ISSUE THREAD

**Issue by anandsinghparihar** [particl/particl-desktop#722]
# Issue with fresh wallet

- Created new wallet
- Enabled encryption
- Create New wallet modal again open. 

# Issue with existing wallet 

-  Add new wallet modal display 
-  Add new wallet button display

**Comment by pciavald** [comment]
it seems #691 broke it, but it was a fix for another issue.
We need to use `getwalletinfo` instead of `extkey list`, lets find out what is wrong with it currently

**Comment by pciavald** [comment]
#724
