### ISSUE TITLE
addStandardInputs : signing transaction failed when sending PART

### ISSUE THREAD

**Issue by vikas-cis** [particl/particl-desktop#728]
I am trying to send payment to @pciavald  and doing testing and found this strange thing
![screen shot 2018-01-19 at 10 02 37 pm](https://user-images.githubusercontent.com/20254889/35161055-06f2c144-fd65-11e7-998b-a4a2cf068eaa.png)

**Comment by vikas-cis** [comment]
@HenkSwardt I did not got this again.

**Comment by HenkSwardt** [comment]
@kewde and @pciavald we are not able to reproduce this issue at all, Please confirm if this can be closed for now?

**Comment by kewde** [comment]
Not reproducible, closing for now.

**Comment by infernotower** [comment]
reproducing this issue.
![image](https://user-images.githubusercontent.com/26768749/50851882-05e0b200-13b9-11e9-813e-b94ac7f489ae.png)
happening under my address PvaHz7BSEwFcrGs4aunscaiC5bPGbatW7o

**Comment by infernotower** [comment]
I have a feeling this is connected to my existing error 
![image](https://user-images.githubusercontent.com/26768749/50852100-9cad6e80-13b9-11e9-9290-2a4c908f90b3.png)

**Comment by kewde** [comment]
The error in your first comment is due to it being an address on the Ledger
(or Trezor if you ran experimental code).
Connect your hardware wallet.
