### ISSUE TITLE
Wallet unlock modal size inconsistent

### ISSUE THREAD

**Issue by bb2k16** [particl/particl-desktop#730]
![image](https://user-images.githubusercontent.com/22429074/35181873-43b09c16-fdc2-11e7-9b13-3263511fe517.png)

The wallet unlock modal is exceptionally large compare to other modal.

Suggestion:
Make it smaller so it is consistent with others.

**Comment by HenkSwardt** [comment]
Good day @bb2k16 , 

We are planning a complete refactor of modals in the near future that will address this issue as part of it. 

Closing this issue in favor of that.
