### ISSUE TITLE
rename "save address" button

### ISSUE THREAD

**Issue by bb2k16** [particl/particl-desktop#733]
![image](https://user-images.githubusercontent.com/22429074/35185615-8b53ed74-fdff-11e7-80b8-59a1d7428398.png)

Suggestion:

better to rename the button text to "+ NEW ADDRESS"?

**Comment by HenkSwardt** [comment]
Thank you for logging the issue, I would suggest we go with "ADD ADDRESS", as New Address might conflict with you creating a new address.

**Comment by vikas-cis** [comment]
#747

**Comment by anandsinghparihar** [comment]
PR: https://github.com/particl/particl-desktop/pull/747
