### ISSUE TITLE
Cant "Create" / "Restore" wallet

### ISSUE THREAD

**Issue by EagleEye25** [particl/particl-desktop#739]
# Describe bug/issue
unable to create or restore wallet, get "work queue depth exceeded error.
# How to reproduce
run through create or restore wallet steps
# More information
![test](https://user-images.githubusercontent.com/28861857/35223915-d91dcff6-ff8b-11e7-82ad-9dfaeb114519.gif)
console log information:
https://zerobin.net/?26a1f8acbf7b83d2#rFdrkbbcaSektS/CdxWYUMJ9T8xRkAdZhDzhUlTUR0I=
- Operating system and version: windows 10 x64
- Client version: 1.1
- Daemon version: 0.15.1.1

**Comment by kewde** [comment]
>  Work queue depth exceeded

Is an error returned by the daemon, I suspect when there are too many RPC calls going on.
What branch were you on?

**Comment by EagleEye25** [comment]
was on Dev, tested on 1.1.0-RC2 now as well, and it didnt want to create or restore either:
updated console information with spy: https://zerobin.net/?6c7e5f2d8d590327#yngeOoIct4G9jP5q6Hvni6N/k64G8AVNyTFyI9g0FME=

**Comment by EagleEye25** [comment]
new console information with -debug:
https://zerobin.net/?9551753850b2b906#kLO2P6Yj19mrCL3Du2SgUS0Z1+E3tFsyhIXIun85lNg=

**Comment by EagleEye25** [comment]
debug log: 
[debug.zip](https://github.com/particl/particl-desktop/files/1655297/debug.zip)

**Comment by HenkSwardt** [comment]
This issue has been duplicated, also see #623

**Comment by HenkSwardt** [comment]
I have tested this using the RC3 release on 2 Windows 10 (64 bit) systems, and was able to create wallets on both occasions.

**Comment by anandsinghparihar** [comment]
I just install 1.1.0 release on windows 10 and I can see that issue on my machine, which reported by @EagleEye25

**Comment by kewde** [comment]
RPC timeout was increased for calls that involve importing the wallet.
Should be fixed.
