### ISSUE TITLE
create a service for external HTTP calls

### ISSUE THREAD

**Issue by anandsinghparihar** [particl/particl-desktop#741]
- [x] Creates Version update service.

**Comment by pciavald** [comment]
@anandsinghparihar what do you mean `Version update service` ?

**Comment by anandsinghparihar** [comment]
@pciavald 
in current code, I was directly called HTTP from a component which should be called using separate service.
https://github.com/particl/particl-desktop/blob/dev/src/app/core-ui/main/release-notification/release-notification.component.ts#L26-L29

**Comment by HenkSwardt** [comment]
@anandsinghparihar @kewde can we move this specific issue to #743 to ensure we tackle all state related issues as one task?

**Comment by anandsinghparihar** [comment]
@kewde could you please joint this  refactoring task `RPC state refactoring`
