### ISSUE TITLE
Refactor state & rpc-state

### ISSUE THREAD

**Issue by kewde** [particl/particl-desktop#743]
Multiple issues described here.

### turn RpcStateClass into RpcStateService
OnDestroy life cycle hooks only work in angular _services_
https://github.com/particl/particl-desktop/blob/a149e579cf512ba1d0bf50ff8cca3b6e6b406f15/src/app/core/rpc/rpc-state/rpc-state.class.ts#L5

### shareReplay in state
Do we really need to shareReplay? Wouldn't this cause it to cache forever? 
https://github.com/particl/particl-desktop/blob/a149e579cf512ba1d0bf50ff8cca3b6e6b406f15/src/app/core/state/state.service.ts#L64-L74

### move state stuff from rpc.service.ts into its own file (or in rpc-state)
These anything rpc-state related seriously doesn't belong there..
https://github.com/particl/particl-desktop/blob/a149e579cf512ba1d0bf50ff8cca3b6e6b406f15/src/app/core/rpc/rpc.service.ts#L131

**Comment by rynomster** [comment]
We use shareReplay so that it can get the history. Get doesn't use observables so it doesn't need take.
The correct way would be to unsubscribe where it is no longer needed.

**Comment by kewde** [comment]
re: get(), I see now :+1: 

I can't think of any situation in the codebase where we're actively using the history tho?

**Comment by kewde** [comment]
@vikas-cis if you have done any changes on this issue, please push them.
I will do this.

**Comment by pciavald** [comment]
@kewde do you want to integrate #741 here as well ? @HenkSwardt

**Comment by kewde** [comment]
#797
