### ISSUE TITLE
Small refactor notification 

### ISSUE THREAD

**Issue by kewde** [particl/particl-desktop#744]
The runNotification shouldn't really be in ipc.service.ts
https://github.com/particl/particl-desktop/blob/a149e579cf512ba1d0bf50ff8cca3b6e6b406f15/src/app/core/ipc/ipc.service.ts#L74-L81

It should use the **ipc.runCommand** and the channel shouldn't be named something like '**notification**' not 'rx-ipc-..'.

This should be in it's own file, not in main.js
https://github.com/particl/particl-desktop/blob/a149e579cf512ba1d0bf50ff8cca3b6e6b406f15/main.js#L68-L78

**Comment by vikas-cis** [comment]
@kewde why not in ipc.service.ts? and yes we can remain the listener

**Comment by kewde** [comment]
@vikas-cis ipc.service.ts is for _core_ ipc functionality only.
The notifications run _over_ the _core ipc functionality_ and they aren't part of it.

**Comment by vikas-cis** [comment]
@kewde  so you mean it will move down to notification service or something ?

**Comment by kewde** [comment]
@vikas-cis I've done it myself in #764
