### ISSUE TITLE
broken layout

### ISSUE THREAD

**Issue by pciavald** [particl/particl-desktop#753]
observed on mac build

![screen shot 2018-01-23 at 2 19 53 pm](https://user-images.githubusercontent.com/3384097/35288730-cf16e3be-0065-11e8-9f3c-bda93ccf3301.png)
![screen shot 2018-01-23 at 5 47 09 pm](https://user-images.githubusercontent.com/3384097/35288751-d9c84384-0065-11e8-919a-e2a651a30c1d.png)
![screen shot 2018-01-23 at 5 47 58 pm](https://user-images.githubusercontent.com/3384097/35288757-dde6eeac-0065-11e8-8801-b043615c36eb.png)
![screen shot 2018-01-23 at 5 46 58 pm](https://user-images.githubusercontent.com/3384097/35288791-eed0e146-0065-11e8-8abd-48af478b2f91.png)

**Comment by vikas-cis** [comment]
@pciavald at least you have also got this issue 👍

**Comment by HenkSwardt** [comment]
This was reported to be broken on Linux build as well please see #694

**Comment by thecarterzim** [comment]
Was coming to add this bug, but see it already exists! Thanks.

**Comment by HenkSwardt** [comment]
This has been logged as a duplicate. Closing issue in favor of #694

**Comment by allienworks** [comment]
@pciavald what's the current state of this? Are you having still the same problems as with the screens above? As mentioned in https://github.com/particl/particl-desktop/pull/758#issuecomment-360430998 the Electron 1.8.2 should fix this, so all we can do is wait for the release.

**Comment by HenkSwardt** [comment]
The upgrade to 1.8.2 did not resolve this issue as expected. Further investigation has been done and it seems that a change to muon will help with resolving this. 

Please see - https://github.com/particl/particl-desktop/pull/807

This needs to be reviewed and tested.

**Comment by pciavald** [comment]
fixed in #807

**Comment by vomm** [comment]
I´ve got few times a little displacement....like one time in 10-20 clicks on Staking node. Windows 10 - 64bit

![rc4_2](https://user-images.githubusercontent.com/28147511/36157437-1319fac2-10da-11e8-8d12-0aab22390185.jpg)

**Comment by imybb** [comment]
observed on Windows RC4 Sandboxed version 

![windows_rc4_out_of_alignment](https://user-images.githubusercontent.com/30150617/36157527-e3e2e4ec-10d1-11e8-976b-c7b93ec10c80.png)

**Comment by vomm** [comment]
and another one.. :)
![rc4_4](https://user-images.githubusercontent.com/28147511/36166740-c4ca41fa-10f3-11e8-8df0-1ef6f193421e.jpg)

**Comment by pciavald** [comment]
yeah @vomm definitely the electron bug. RC5 will be packaged with muon instead for mac & win. Reopen if RC5 doesn't fix

**Comment by pciavald** [comment]
@imybb your issue is a different one. @allienworks can you open an issue ?

**Comment by allienworks** [comment]
@pciavald yep ^
