### ISSUE TITLE
Balance Transfer :  Can't able to send All Blind Balance to Public (Send All)

### ISSUE THREAD

**Issue by vikas-cis** [particl/particl-desktop#755]
![screen shot 2018-01-24 at 4 56 24 pm](https://user-images.githubusercontent.com/20254889/35329945-a37f381a-0127-11e8-8e87-993d4fd442a9.png)

How to reproduce
1) Go to Send Page
2)Do Blind to Public

I got the error as in the above screenshot

Thanks

**Comment by vikas-cis** [comment]
Tested in RC3- 1.1.0

**Comment by HenkSwardt** [comment]
I also tested this issue on RC3 Release and found the same.

**Comment by HenkSwardt** [comment]
This issue has been resolved in Core and will be fixed in modal with next Core Release. 

Closing issue.
