### ISSUE TITLE
overview transaction order sometimes not right

### ISSUE THREAD

**Issue by pciavald** [particl/particl-desktop#765]
![screenshot_20180127_134009](https://user-images.githubusercontent.com/3384097/35472026-dc630c46-0367-11e8-921e-0755567cf7c3.png)

**Comment by vikas-cis** [comment]
@pciavald I have got this issue only at once when my wallet was unencrypted and I am doing coldstaking. After that I never able to reproduce it.I have tested stuff in release/1.1.0
![screen shot 2018-01-30 at 6 41 44 pm](https://user-images.githubusercontent.com/20254889/35568169-f3b47f1e-05ed-11e8-9144-12c13a2a1e8b.png)

**Comment by anandsinghparihar** [comment]
@pciavald I am unable to reproduce this issue

**Comment by allienworks** [comment]
I also can't reproduce. When did this happen to you @pciavald?

**Comment by EagleEye25** [comment]
^ same here can't reproduce

**Comment by HenkSwardt** [comment]
@pciavald , please assist with the process forward on this matter. 

Thank you

**Comment by kewde** [comment]
Fixed.
