### ISSUE TITLE
Daemon and java failures, cannot create an address or restore an existing wallet

### ISSUE THREAD

**Issue by savagejordan23** [particl/particl-desktop#767]
Trash, needs to be fixed, only Particl Core works somewhat

# Describe bug/issue

..

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. ..
2. ..

# More information

- Operating system and version:
- Client version:

**Comment by kewde** [comment]
A _lot_ of fixes are in our upcoming release, already fixed, just not released.
Run branch `1.1.0`.
