### ISSUE TITLE
Only one wallet allowed to be created?

### ISSUE THREAD

**Issue by abunsen** [particl/particl-desktop#775]
This is the issue template. Everything is optional, but the more you supply, the better.
Please use short decriptive titles for issues.

# Describe bug/issue
There is a 1 wallet per app limit. I'd like to be able to create multiple wallets - is this in the queue at all?

# More information

- Operating system and version: Mac
- Client version: 1.0.1

**Comment by kapsr** [comment]
https://github.com/particl/particl-desktop/pull/441

**Comment by HenkSwardt** [comment]
Hi @abunsen 

Thank you for the inquiry, yes we indeed have a multi wallet setup in the pipeline and the aim is to deliver this with the next "Feature" release. As per @kapsr please see #441 (Multiwallet - 441).

Closing Issue.
