### ISSUE TITLE
coldstaking widget issues

### ISSUE THREAD

**Issue by pciavald** [particl/particl-desktop#781]
## 100% shows 'activating' instead of 'activated'
- [x] ![screenshot_20180201_170146](https://user-images.githubusercontent.com/3384097/35688614-da0c5944-0771-11e8-89f0-3de1c336ba4d.png)

## <100% shows activated
- [x] ![screenshot_20180201_170612](https://user-images.githubusercontent.com/3384097/35688793-425a2328-0772-11e8-82ac-bd5b5aacf2fa.png)

## disable button is shown even though there is no transaction to disable
after uncofirmed zap, disable is shown, leading to a disable of no transaction
- [ ] ![screenshot_20180201_170710](https://user-images.githubusercontent.com/3384097/35688842-67cc03f6-0772-11e8-97ec-c2e1c76fe9ae.png)

## zap button is shown even though there is no transaction to zap
after uncofirmed disable, zap is shown, leading to a zap of no transaction
- [ ] ![screenshot_20180201_171737](https://user-images.githubusercontent.com/3384097/35689525-04ccac5e-0774-11e8-9edd-32cc15090f50.png)

**Comment by pciavald** [comment]
#760

**Comment by pciavald** [comment]
![peek 2018-02-03 00-27](https://user-images.githubusercontent.com/3384097/35759294-0eaa98f2-0879-11e8-94ee-5b6b7afd7744.gif)

**Comment by pciavald** [comment]
@claudiocabral

**Comment by pciavald** [comment]
actually `disable` should be shown at any time, so that even if you are at 0% cold staking activation you can still disable it (just removing pkey)

**Comment by pciavald** [comment]
#630

**Comment by kewde** [comment]
Should be fixed in 846
