### ISSUE TITLE
GUI not synced

### ISSUE THREAD

**Issue by pciavald** [particl/particl-desktop#794]
i've made a transaction, closed the wallet, opened it 2 hours later. I seen the daemon sync in the terminal, block height is at the latest block. However the transaction still shows 0 confirmations.
After 5min+ the confirmations count finally updated.
![screenshot_20180203_034416](https://user-images.githubusercontent.com/3384097/35762325-2c8db46e-0895-11e8-9256-d0b411d5215a.png)

**Comment by kewde** [comment]
Block update throttling reduced to 2 seconds instead of 30 (should do the trick).

**Comment by kewde** [comment]
@pciavald keep an eye when doing tx related stuff - so we can check if it's happening.

**Comment by pciavald** [comment]
hey @kewde I doubt that screen was trigger by throttling problem because as you can see there was 57 confirmations so that's almost 2h late. I'll keep an eye anyway

**Comment by vikas-cis** [comment]
@pciavald you are right it seems throttling problem as before I suggested it doesn't work some times due to which confirmation doesn't update even for hours :P

**Comment by kewde** [comment]
The code behind the transaction table that the issue is either: not triggering update or a particl-core issue.

The issue with throttling is that we really need it because a block sync will make an insane amount of calls.
