### ISSUE TITLE
Replace angular2-qrcode

### ISSUE THREAD

**Issue by kewde** [particl/particl-desktop#800]
It uses some native dependencies for some odd reason 'canvas', it's an optional dependency but it fails to build and has caused issue with electron-builder builds in the past, need to get rid of it.
Replace it with something more robust.

**Comment by vikas-cis** [comment]
@kewde 
Can we try the below and use one of them if it make sense ? 

https://www.npmjs.com/package/ng2-qrcode
https://www.npmjs.com/package/angular2-qrcode-generator

Thanks

**Comment by kewde** [comment]
https://www.npmjs.com/package/ng2-qrcode

That one looks fine to me.
Make sure to remove all the existing angular2-qrcode stuff, import the QrCodeModule in the CoreUiModule.

**Comment by vikas-cis** [comment]
@kewde thanks will check and do a pr

**Comment by vikas-cis** [comment]
@kewde I think we cannot use that 
https://github.com/PragmaticClub/ng2-qrcode/issues/12

Thanks

**Comment by kewde** [comment]
Yes.
