### ISSUE TITLE
in OS X, Command + V pastes clipboard contents twice

### ISSUE THREAD

**Issue by claudiocabral** [particl/particl-desktop#817]
Whenever input is pasted in some forms with `command + V` the cliboard contents are pasted twice.
PR #740 fixed the opposite problem, but some widgets still react to the default event causing
the double pasting.

- Operating system and version: OS X 10.11.6 El Capitain Darwin Kernel Version 15.6.0

**Comment by kewde** [comment]
@claudiocabral thanks!
Always great when a bug report comes with a fix.

**Comment by kewde** [comment]
Also ported to 1.1.0
