### ISSUE TITLE
Transaction Fee not added but subtracted from Net total

### ISSUE THREAD

**Issue by HenkSwardt** [particl/particl-desktop#823]
Testing 1.1.0 RC 5 release.

 When sending Part, the transaction fee gets subtracted instead of added to the net total.

![image](https://user-images.githubusercontent.com/28799964/36201004-30e320e4-1187-11e8-821b-2fb7fa9cd2be.png)

- Operating system and version: Windows 10 (64)
- Client version: 1.1.0 Sandbox RC-5 - Muon

**Comment by HenkSwardt** [comment]
Hi @anandsinghparihar 

Please confirm if you have made changes regarding this task and have they been merged? On testing RC 5 release this morning, transactions seem to behave as expected.

**Comment by anandsinghparihar** [comment]
@HenkSwardt  yes transactions work fine. 
![test123](https://user-images.githubusercontent.com/17725557/36257504-2aedebe6-127d-11e8-8873-2ba9c60f80dc.png)
