### ISSUE TITLE
Paste button not working

### ISSUE THREAD

**Issue by HenkSwardt** [particl/particl-desktop#824]
Testing 1.1.0 RC 5 release.

The Paste icon does not allow the user to paste the address at all. This has been tested on Mac as well as windows. With a Mac system CMD+v also does not allow pasting. This however works on windows using Ctrl+v

Operating system and version: Windows 10 (64)
Client version: 1.1.0 Sandbox RC-5 - Muon

**Comment by vikas-cis** [comment]
@HenkSwardt I will check if I debug and found solution afaik `document.execCommand('Paste')` not working in muon build

Thanks

**Comment by HenkSwardt** [comment]
@vikas-cis , @kewde is looking into this for us. 

Thanks

**Comment by kewde** [comment]
Should be fixed on Muon now.

**Comment by pciavald** [comment]
will try, let's package this sweet baby
