### ISSUE TITLE
Windows 10 security error on launch - Unknown Publisher

### ISSUE THREAD

**Issue by LiteBit** [particl/particl-desktop#831]
# Unknown Publisher error, Windows 10

On first launch I get a Windows 10 error advising me not to open Particl Desktop because of "unknown publisher"

![image](https://user-images.githubusercontent.com/6236019/36219162-7e6d8f46-1184-11e8-95ca-e415a5b6eaf0.png)

I thought Particl Foundation signatories and certificates were created for v1.1 release? 
# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. Download Particl Wallet v1.1 rc4 for win64
2. Double-click to **run**

# More information

- Windows 10
- Particl Desktop v1.1 rc4

**Comment by pciavald** [comment]
thanks @LiteBit :) it's actually a duplicate of #687, i'll close this.
