### ISSUE TITLE
Canceling cold staking before ZAP transaction confirmed

### ISSUE THREAD

**Issue by vomm** [particl/particl-desktop#833]
If i have activation progress, lets say, at 75 % and then i ZAP the rest, it is possible to cancel cold staking before confirmation. And if i cancel it before the this ZAP transaction is confirmed, i get back to hot wallet only these 75 %. A status of cold staking shows INACTIVE. But these last 25 % is still cold staking. And the only way u will notice is, if u put the same node public key again, then u immediately see Activation in progress at 25 %. And only after u may cancel rest 25 % to hot wallet
Windows 10 64bit - 1.1.0 sandboxed RC5

**Comment by HenkSwardt** [comment]
Assigning to @pciavald 

Please investigate this for us as this should not be the correct behavior.

Thanks

**Comment by pciavald** [comment]
Good catch, I know what's going on here.
The coldstaking service should keep a state of the last executed command (zap/disable) and wait for it to be confirmed before allowing further action. In this scenario :
- wait for coldstaking activation to progress (or manually zap a fraction of the balance)
- zap the rest
- zap tx is kept in memory, disable is not possible until confirmed
- once confirmed, `disable` button appears

**Comment by pciavald** [comment]
#630
