### ISSUE TITLE
reverse send and receive

### ISSUE THREAD

**Issue by SativaL** [particl/particl-desktop#838]
RC4 Build on linux 64 bit

![arrowspart](https://user-images.githubusercontent.com/16978634/36259841-c842bee4-125f-11e8-92fd-06eb25111624.png)

Can we have the Send page in the first line in the left side bar ? Receive should be second then.

Definitely like the first page at the start, this might be intuitive behaviour, are you also feel like this ?

**Comment by pciavald** [comment]
@allienworks can you check what's up with the arrows and see with @gerlofvanek for the send/receive position swap ?

**Comment by allienworks** [comment]
> @pciavald ..what's up with the arrows..

What do you mean?

If you're talking about the arrows in expansion panels, I did a nice fix over at `market` branch, so I could fast-forward it to `develop` (overall nicer layout, not-expanding effect and some other tweaks)..

We can swap positions of Receive and Send easily, if we agree. I personally think that logically, you first need to Receive something for you to send it.

**Comment by SativaL** [comment]
https://ucarecdn.com/a430d3c3-3a1b-42b7-93ea-b0ad02e79010/

https://steemit-production-imageproxy-upload.s3.amazonaws.com/DQmY4NobLygcrFUQw9Bu66whyyosutdcgfq8fLMHTVZYmXv

https://www.monero.how/images/gui-wallet-main.jpg

cheers

**Comment by pciavald** [comment]
@allienworks "with the arrows" refers to a deleted section of the first comment, i guess nevermind
Seems send before receive is standard :)
