### ISSUE TITLE
Modal out of place

### ISSUE THREAD

**Issue by bb2k16** [particl/particl-desktop#845]
# Describe bug/issue

![image](https://user-images.githubusercontent.com/22429074/36319819-15c3d194-133c-11e8-92d8-954bd15fe094.png)

![image](https://user-images.githubusercontent.com/22429074/36319689-9c24a160-133b-11e8-8161-5cc689ae3902.png)

# More information

- Operating system and version: Linux Mint 18.3 Cinnamon 64-Bit
- Client version: RC5

**Comment by kewde** [comment]
Is this the latest release candidate or did you compile yourself?

**Comment by bb2k16** [comment]
thats the latest RC5 downloaded from Github. Linux Only.

**Comment by pciavald** [comment]
fixed
