### ISSUE TITLE
small design bug on left menu grid icon

### ISSUE THREAD

**Issue by llangg** [particl/particl-desktop#851]
From OVERVIEW 
going to another point on the menu (RECEIVE...), 
the grid icon next to OVERVIEW 
flickers on left / top / right edges 
when moving the mouse
for a while.

client version 1.1.0
on macOS 10.12.6

**Comment by kewde** [comment]
Please check and if it's not the case anymore, close the issue.

**Comment by zaSmilingIdiot** [comment]
Closing for now, as it no longer appears to be applicable.
