### ISSUE TITLE
Confirm & payment tab (@market)

### ISSUE THREAD

**Issue by bb2k16** [particl/particl-desktop#852]
# Describe bug/issue
The number "3" when off focus no longer is the same text

# How to reproduce
https://i.imgur.com/4HduJnT.gif

# More information

- Operating system and version: win 10 x64 build 
- Client version: commit 9be36ee2cba58126695b4fd7383a132919a79eee (i think)

**Comment by HenkSwardt** [comment]
Hi @AllienWorks 

I had a look at the latest Dev version and this issue seem to have been fixed. 

Can you please confirm this for me?

Thank you

**Comment by AllienWorks** [comment]
Yes, this is fixed already.
