### ISSUE TITLE
Public balance is not get updated once you got transaction on Over View Page

### ISSUE THREAD

**Issue by vikas-cis** [particl/particl-desktop#857]
Before Transaction 
![screen shot 2018-02-20 at 7 45 03 pm](https://user-images.githubusercontent.com/20254889/36428861-0e67da9c-1677-11e8-843f-b21117539c80.png)

After I got 10 part
![screen shot 2018-02-20 at 7 47 03 pm](https://user-images.githubusercontent.com/20254889/36428872-14b6d6b4-1677-11e8-9c2d-0d31a5ba42e4.png)

**Comment by vikas-cis** [comment]
@kewde  @pciavald  Is it suppose to work in the same way ?

Thanks

**Comment by kewde** [comment]
It's still unconfirmed, the public balance only updates if the transaction is confirmed.

**Comment by vikas-cis** [comment]
@kewde thanks for the info :)

Thanks
