### ISSUE TITLE
notifications on confirmation

### ISSUE THREAD

**Issue by pciavald** [particl/particl-desktop#861]
I think it would be useful to have
- a notification when a transaction gets its first confirmation
  - your transaction has appeared on the blochchain ?
- a notification when a transaction gets 12+ confirmations
  - your transaction has been confirmed ?

**Comment by HenkSwardt** [comment]
Hi @pciavald , what milestone will this be linked to?

**Comment by zaSmilingIdiot** [comment]
Not particularly useful currently. Closing for now, and can be re-opened if this becomes a sought-after requested feature.An indication on the history table (or in the overview page) as currently indicated should be sufficient to indicate the number of confirmations.
