### ISSUE TITLE
UI Suggestion: Rename label

### ISSUE THREAD

**Issue by bb2k16** [particl/particl-desktop#865]
instead of clicking on the name of the label to change the string (because it is not obvious to the user [UX]) add a pen to indicate to the user that the following text is editable.

![image](https://user-images.githubusercontent.com/22429074/36536326-7b99d856-17c4-11e8-8fca-2d440b45ca01.png)

**Comment by anandsinghparihar** [comment]
PR: https://github.com/particl/particl-desktop/pull/907

**Comment by HenkSwardt** [comment]
This change has been applied. 

![image](https://user-images.githubusercontent.com/28799964/38081822-448d9626-3345-11e8-85bc-60938ac15f19.png)
