### ISSUE TITLE
daemon does not stop after GUI quits

### ISSUE THREAD

**Issue by pciavald** [particl/particl-desktop#868]
since a week or so, when I close the wallet it does not always quit the daemon

**Comment by vikas-cis** [comment]
@kewde @HenkSwardt Initially I thought the daemon doesn't stop only when it starts from elsewhere that is the reason I called `stop` method and done the above PR, but as suggested by @kewde and @tecnovert we don't need to call it so I reverted the code back on the PR. 

After testing a while I did not got any kind of issue related daemon stop on mac and it working fine to me :)

Thanks

**Comment by kewde** [comment]
This was an issue only related to the market branch, not on develop.
d289aa433a26d102ce3ab6c6cd952089ba3db4c9
