### ISSUE TITLE
Favorites: list - delete

### ISSUE THREAD

**Issue by kewde** [particl/particl-desktop#873]
- [x] Store a list of the favorites in the market state service, `favorites 'list'`. Then whenever we load the overview listings, it should check if the listing is already favorited or not. If it is delete the favorite instead of adding it.
- [x] Delete a favorite

**Comment by HenkSwardt** [comment]
https://github.com/particl/particl-desktop/pull/877

**Comment by HenkSwardt** [comment]
Issue resolved and merged
