### ISSUE TITLE
MP Overview Page: Display totals of items dynamically

### ISSUE THREAD

**Issue by HenkSwardt** [particl/particl-desktop#879]
On the overview page we need to show all totals for the below items dynamically.

**- Seller Overview:**

- Total Listings

- [x] Published
- [x] Unpublished
- [x] Expired

- Sell Orders

- [ ] Bidding
- [ ] In Escrow
- [ ] Shipped

**- Your Buy Orders**

- Buy Orders

- [ ] Bidding
- [ ] In Escrow
- [ ] Shipped

**Comment by HenkSwardt** [comment]
As discussed, we will hide the current widgets as we don't have all the backend data available. We will try to show this as soon as Escrow (#896 )and Biding (#897 ) development has been completed.

**Comment by vikas-cis** [comment]
@HenkSwardt I have commented the widget for now.

Thanks

**Comment by HenkSwardt** [comment]
Widget hidden as per request.
