### ISSUE TITLE
MP Listings Page: Categories filter has no data

### ISSUE THREAD

**Issue by HenkSwardt** [particl/particl-desktop#881]
The categories drop-down on the listings page needs to be linked to our categories list on the back-end as used on the “Add new listing” page.

See src/api/services/ItemCategoryService.findAll() for implementation of default category list. We need to keep in mind that new categories can be added and deleted, but users cant delete default list.

**Comment by vikas-cis** [comment]
@HenkSwardt I gone through the latest stuff and seems categories are coming via the backend.

Thanks

**Comment by vikas-cis** [comment]
I have the closed the above PR as it was showing some previous commits of my other PR due to which I am creating a new one 

Thanks

**Comment by HenkSwardt** [comment]
I have tested and confirmed this to be working
