### ISSUE TITLE
MP Listings Page: Reporting a listing

### ISSUE THREAD

**Issue by HenkSwardt** [particl/particl-desktop#882]
Reporting a listing does not seem to work. We will need to get this functional on both the main listing page as well as the detailed listing page.

**Comment by HenkSwardt** [comment]
For now we will use this task to hide the buttons.

**Comment by HenkSwardt** [comment]
Hi @AllienWorks 

Will you please hide these for us. 

Thank you

**Comment by AllienWorks** [comment]
Done.
