### ISSUE TITLE
MP Listings Page: Part/USD pairing - Conversion of price

### ISSUE THREAD

**Issue by HenkSwardt** [particl/particl-desktop#883]
We show a conversion of Part to USD on the listings, this will need to make use of an API to ensure we have the correct trade value if we want to display this.

**Comment by HenkSwardt** [comment]
In order to implement this please refer to https://docs.google.com/spreadsheets/d/18ElD3FQW9mvoSw055Rlo-fFPH206w4CXL8j_jM9FGLw/edit?usp=sharing

On here you can look at the following api's:

currencyprice
priceticker

**Comment by HenkSwardt** [comment]
Skieter will be looking into this for us.

**Comment by Skieter** [comment]
I have added to the API, however I cannot create listings to test?

**Comment by rynomster** [comment]
To show the usd price, do we want to add the USD price to the Template model, or do we want to do it lazily at runtime through each iteration?

**Comment by HenkSwardt** [comment]
@xludx , please will you have a look at the question above from @rynomster . What was the intention with using the API?

Thank you
