### ISSUE TITLE
MP Buy Page: Your cart shows a QTY counter but not working

### ISSUE THREAD

**Issue by HenkSwardt** [particl/particl-desktop#884]
On the "Your Cart Tab" in "Your Cart" (Checkout flow) we provide a user the ability to add quantity of items that based on the input it should automatically calculate the total price. The screen has all of this in place but logic not working. 

- [ ] Do we need to keep this in place or hide for Alpha release?

**Comment by HenkSwardt** [comment]
Adding Low priority label to this issue. We dont think this will be needed for Alpha

**Comment by HenkSwardt** [comment]
Confirmation received that this will not be done for Alpha. We will hide the ability to allow for multiple QTY's.

@vikas-cis ,Please confirm once done. 

Thank you

**Comment by vikas-cis** [comment]
@HenkSwardt we have already comment out the quantity as per now and below is the PR 
#875
