### ISSUE TITLE
MP Buy Page: Confirm and Pay behavior to be finalized - Awaiting Escrow step in Orders tab

### ISSUE THREAD

**Issue by HenkSwardt** [particl/particl-desktop#887]
On the "Your Cart Tab" in "Confirm & Payment" (Checkout flow) step to confirm payment, what needs to happen when the buyer “Confirm & Pay”?

**Comment by AllienWorks** [comment]
This should trigger the payment confirmation modal (#742), which needs to be merged first. It will still need some tweaks, before the current confirmation modal wasn't built for more payments at once (as you can have multiple products in your cart from multiple sellers).

**Comment by HenkSwardt** [comment]
This function will be moved to the Awaiting Escrow status that is being added as part of https://github.com/particl/particl-desktop/pull/915 , once in place the actual payment/sending of funds will happen on that step of the workflow, where the buyer can pay for his order after the seller has accepted the bid.

**Comment by HenkSwardt** [comment]
Changes relating to this has been merged, Additional changes logged on Jira.
