### ISSUE TITLE
MP ESCROW - Finalize escrow development

### ISSUE THREAD

**Issue by HenkSwardt** [particl/particl-desktop#896]
We need to look at what is still outstanding on the Escrow development for the Alpha release and add a TODO list to this issue.

**Comment by rynomster** [comment]
please see particl/dapp-shell/pull/182 for TODO list

**Comment by HenkSwardt** [comment]
Backend development has been finalised in /particl/dapp-shell

**Comment by HenkSwardt** [comment]
Integration development outstanding:

Seller Side:

- [ ] Escrow Release Integration
- [ ] Escrow Refund Integration

Buyer Side

- [ ] Escrow Lock Integration
- [ ] Escrow Release Integration
- [ ] Escrow Refund Integration

**Comment by rynomster** [comment]
Needs to be assigned

**Comment by HenkSwardt** [comment]
This issue has been duplicated and broken down on Jira. I believe we can close the Github log

**Comment by HenkSwardt** [comment]
Closing Issue. 

Alpha has been released with all Escrow features working. Any further development will be logged as new tasks
