### ISSUE TITLE
MP BIDS - Finalize bidding development

### ISSUE THREAD

**Issue by HenkSwardt** [particl/particl-desktop#897]
We need to look at what is still outstanding on the Bidding development for the Alpha release and add a TODO list to this issue.

**Comment by HenkSwardt** [comment]
We are making some changes to the current flow of the marketplace. In the current flow we have to move the payment of the order from the checkout process to part of the Orders workflow. Payment can only happen once a bid has been accepted by the seller. 

Please see https://github.com/particl/particl-desktop/issues/914 for details of changes. This will introduce an new status called awaiting Escrow, where the buyer needs to make the payment once the bid has been accepted by the seller and the bidding status has been completed. On completion of the Awaiting Escrow status the Escrow will be locked in.

**Comment by rynomster** [comment]
The development has been finalised in particl/dapp-shell

**Comment by rynomster** [comment]
- [ ] Integrate Bid Send
- [ ] Integrate Bid Accept
- [ ] Integrate Bid Cancel
- [ ] Integrate Bid Reject

**Comment by HenkSwardt** [comment]
This issue has been duplicated and broken down on Jira. I believe we can close the Github log

**Comment by HenkSwardt** [comment]
Closing Issue. 

Alpha has been released with all Bidding features working. Any further development will be logged as new tasks
