### ISSUE TITLE
Market: add new TX types

### ISSUE THREAD

**Issue by AllienWorks** [particl/particl-desktop#928]
When creating new listings on Market etc., the associated TXs are marked as "Balance Transfer".

We currently have: Received, Send, Staked and Balance Transfer (+ some less frequent ones)

We should add more TX types, I'm thinking (might need better wording):

- Listing fee
- Bought item(s)
- Sold item(s)

![](https://i.imgur.com/LIRzI7s.png)

In TX History page, as we're running out of space for new tabs, I'd probably group all those into one "Market" tab.

---

Apart from that, I'd also replace "Balance Transfer" to show what was converted to what, e.g. "Public → Blind" or "Anon → Public"

**Comment by kewde** [comment]
No API support for this in particl-core nor in the particl-market.
Fixed the listing fee issue tho.
