### ISSUE TITLE
Cold staking widget problem in Windows 10 64bit

### ISSUE THREAD

**Issue by vomm** [particl/particl-desktop#930]
Hi. 
With the new daemon, i have problem with Cold Staking in Particl Desktop for Windows 10 64. 
I´m not able to activate Cold Staking, because i cant see this green plus add button. 
Only i can see is this description. Even after unlocking or whatever. Same problem confirmed at my friends windows PC. On linux its just fine. I think, that with the previous version of daemon it was working great.

Client 1.1.0
Daemon 0.16.0.2
Windows 10 64bit

![screen part](https://user-images.githubusercontent.com/28147511/38195542-36ff21aa-367e-11e8-80e1-60bc15cae197.jpg)

**Comment by selamlevinas** [comment]
I face the same problem both in Windows 10 Education x64 and in OS X 10.11.6, with the same client and core (Client 1.1.0, Daemon 0.16.0.2)

Also in OSX 10.11.6, verifying the Particl Desktop app takes forever, without any progress. So I had to open the app by right clicking / Show Package contents / Contents / MacOS / Particl Desktop. Only then it opened.

I will also try with Ubuntu and report if I face some problems.

**Comment by selamlevinas** [comment]
Looking forward for the next build then!

(I also tried with Linux Mint but the widget was not there either. I am really surprised that this bug is not reported that frequently. Maybe I am doing something extremely wrong? Anyways, just bought a Raspberry Pi 3 B+ for cold staking and waiting impatiently to higher the cold staking percentage of the network:) Regards and cheers to you all!)

**Comment by Jookly** [comment]
I want to share that I experience the same issue using the mac build with OSX 10.12.6 .  Looking forward to trying cold staking when fixed.  thank you.

**Comment by ender46** [comment]
Hello,

I am experiencing the exact same problem.

After restoring the wallet from seed and synching to full, there is no + button to add the staking key, and hovering over the snowflake sign shows a "cold staking disabled" popup. I am using the daemon version v0.16.0.3.0-52a412d and the desktop client version 1.1.0, in two different Ubuntu 14.04.5 LTS machines. I used this exact same setup before and the cold staking feature was working fine before.

Let me know if I can help with more info. Cheers

**Comment by opacey** [comment]
+1
MacOs 10.13.4
Particl Desktop 1.1.0

Context: Clean OS installation, fresh Particl Desktop installation, copied wallet.dat from my particl-qt node. Everything looks fine except for the lack of the green plus button in the cold staking modal (as per screen shot rom OP).

**Comment by jvlugoinv** [comment]
I tried both versions, the .zip uncompress version and the .exe installer version for Windows 10 64bit and the problem persists: No (+) sign in the cold staking widget. Any updates?

**Comment by xnorthside** [comment]
Same issue with MacOS High Sierra 10.13.3.

**Comment by mfts** [comment]
Are there any updates from the team? I mean cold staking is quite integral to Particl's PoS mechanic.

**Comment by kewde** [comment]
Will do a new release when:
#1051 & #1052 are merged

**Comment by zaSmilingIdiot** [comment]
Has been fixed in a newer release.
