### ISSUE TITLE
MP: adding Favs to Cart

### ISSUE THREAD

**Issue by AllienWorks** [particl/particl-desktop#936]
When adding favourited item to Cart, it isn't added to Cart. There's a notification saying item was added, but it isn't there.

**Comment by anandsinghparihar** [comment]
@AllienWorks its work fine for me, could you please check your `dapp-shell` probably its req. update?

**Comment by AllienWorks** [comment]
Vikas's PR ^ solves this. The cart just didn't get refreshed when adding stuff from Favs.

**Comment by anandsinghparihar** [comment]
@AllienWorks yes I agree with that was not working with market branch now Vikas PR is also merge but I removed his code in this pr without manual update its work fine : 
could you please confirm me in this PR its work or not ? https://github.com/particl/particl-desktop/pull/933
