### ISSUE TITLE
MP: Listing statuses

### ISSUE THREAD

**Issue by AllienWorks** [particl/particl-desktop#937]
Listing statuses don't reflect their current state.
Currently all display _Unpublished_ even if they are already active.

![](https://i.imgur.com/JqoYPTL.png)

**Comment by kewde** [comment]
@AllienWorks should be fixed but please take a look at making those buttons pretty.

**Comment by AllienWorks** [comment]
@kewde looks all right to me.. which buttons are you talking about? The `Unpublished` statuses etc.?

**Comment by kewde** [comment]
@AllienWorks 
Seems like it was already fixed, looking good!

We should have a task for adding a cache - once you click the button it will remember that it has been posted.
