### ISSUE TITLE
Market Gui - sidebar tabs wont work anymore after clicking "Buy"

### ISSUE THREAD

**Issue by SativaL** [particl/particl-desktop#952]
# Describe bug/issue

Market gui - sidebar tabs wont work anymore

# How to reproduce
start the gui, click listings then click buy, then click sell.. it will crash

# More information

- Operating system and version: linux mint 18.x
- Client version: Client 1.1.0-RC1-alpha
Daemon 0.16.0.2

Gif: 

![out](https://user-images.githubusercontent.com/16978634/39383596-1d85fa3c-4a6a-11e8-9eea-ff1073681209.gif)

**Comment by HenkSwardt** [comment]
Tested and confirmed that this has been resolved.

Thanks
