### ISSUE TITLE
Feature Request: UI Indicator for when a user is staking

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl-desktop#955]
I think it would be valuable to have a UI indicator (similar to and possibly next to the Lock icon) that indicates if my wallet is currently actively staking.

As a community member that monitors the chats, I often see users show up asking "Am I staking correctly?" because it is not entirely clear in the UI when you are.  

I use the CLI client and know that 'staking:1' from the getstakinginfo command exposes this information. Perhaps the Desktop application can use that to feed data to a UI component.

**Comment by kewde** [comment]
staking: 0 means you might be staking, but you currently don't have any coins locked.
There is a clear indicator already for staking: 1, namely the 'staked' balance.

**Comment by CryptoBeans** [comment]
@kewde 

I think I may have misworded what I was requesting. I'm not referring to having a locked staked balance, this is talking about having your wallet setup in such a way that you are currently able to participate in staking.

I believe the checks would be:
- Is the wallet unlocked or unlocked-for-staking-only
- Are my coins mature
- Do I have internet connection
- Do I have at least X number of peers (like 3 maybe?)

If all of those things pass, then a UI indicator would show to let the user know that they are set up and ready to wait for their stake rewards to start coming.

The reason I request this is that lots of people new to Particl show up in the chats and don't realize that they may have missed one of the above checks to be staking. A simple UI element can let people know one way or another.

@LiteBit and I discussed this briefly in the chats one day and he suggested I open an issue for this as he thought it was a good idea too.

By the way, in CLI staking: 0 means you are setup in such a way that you are not participating in staking and not able to receive rewards. staking: 1 means you have it set up such that you can participate. In both cases, it is not tied at all to your locked staked balance.
