### ISSUE TITLE
MP: add option groups in categories selector

### ISSUE THREAD

**Issue by demyanrogozhin** [particl/particl-desktop#963]
This is the enhancement for selector drop-down with in Categories.

Expected:
As categories is hierarchy and inner categories should be visually different than upper-level categories.

Actual:
Currently categories displayed as flat list.

**Comment by AllienWorks** [comment]
I've merged the B) variant for now. Agreed that the ideal solution would be the other with market-api fixes, but we can leave that for post-alpha.
