### ISSUE TITLE
MP: Payment confirmation modal shows static numbers

### ISSUE THREAD

**Issue by demyanrogozhin** [particl/particl-desktop#966]
Confirmation modal, that pops after clicking make payment, shows static numbers with red borders.

* Things displayed correctly:
- [x] listing name.

* Things that missing:
- [x] Item price (`12 . 001  PART`)
- [x] Address (`[seller's address here]`)
- [ ] TX fee (`11 PART`)
- [x] Shipping cost (`2.455 PART`)
- [x] Escrow (`Escrow:13.455 PART`)
- [x] Total amount (`26.91 PART`)

Screenshot:

![](https://matrix.org/_matrix/media/v1/download/matrix.org/VaYgLFFtmVTknohsyjOUDPZr)

### How to reproduce

1. Bid on some listing that is now your own
2. Wait until seller confirm bid
3. On order page open order that have "AWAITING" state
4. In opened panel click "Make payment"

- Operating system and version: Window 
- Client version: 1.1.0-RC1-alfa

**Comment by HenkSwardt** [comment]
Issue has been resolved

**Comment by HenkSwardt** [comment]
Currently we are hiding the TX fee for alpha.
