### ISSUE TITLE
1.1.0-linux-amd64.deb did not work

### ISSUE THREAD

**Issue by HauRuck** [particl/particl-desktop#980]
# Describe bug/issue
I tried to install the desktop with ubuntu software manager but after installing there was no option to start the application. After rebooting the computer I the application was still not avalible in the start menu so I installed once again. Since the reinstall didn't help I clicked uninstall before closing the software manager.

# How to reproduce

I'm using Ubuntu 16.04 and the default software manager by simply clicking on the deb file in the file  explorer.

# More information

Version 1.1.0 amd64

**Comment by HenkSwardt** [comment]
Good day @HauRuck 

Sorry for the delay on this response. Have you been able to test this with the latest testing build we made available?

 0f94154d772e3a91527f4735071f1007051c7b12c7b11f30bd3215fe838f33b2 particl-desktop-linux-amd64-PR1016-5c5fdce.deb
 https://transfer.sh/15QoF9/particl-desktop-linux-amd64-PR1016-5c5fdce.deb
 http://jxm5d6emw5rknovg.onion/15QoF9/particl-desktop-linux-amd64-PR1016-5c5fdce.deb

 
 8ce23200c92acf3c2ab4b97620b37d81b38c807e2add31c8d3b2a31343807bcc particl-desktop-linux-x64-PR1016-5c5fdce.zip
 https://transfer.sh/146nzL/particl-desktop-linux-x64-PR1016-5c5fdce.zip
 http://jxm5d6emw5rknovg.onion/146nzL/particl-desktop-linux-x64-PR1016-5c5fdce.zip


Regards

**Comment by rynomster** [comment]
The desktop file isn't loaded correctly, but you can run it from the
command line by running particl-desktop.

Thanks for Letting us know.

**Comment by kewde** [comment]
#1023

**Comment by zaSmilingIdiot** [comment]
Resolution does appear to have been provided. Newer releases are now also available.
