### ISSUE TITLE
Grammar update on ordering workflow

### ISSUE THREAD

**Issue by dgbarton** [particl/particl-desktop#981]
This is just a grammatical issue that should be corrected to maintain a professional tone in the marketplace GUI.  On the "Choose Shipping Profile" section of the "Shipping Details" workflow, the following text appears:

"To save time, you can save your frequently used shipping addresses as your personal shipping profiles.  You can create as much profiles as you need (e.g. home address, office address etc.)."

There appear to be two grammatical errors present, and these can be corrected as shown via bold text below.  The "much-->many" is a noticeable one when read by a native English speaker.

"To save time, you can save your frequently used shipping addresses as your personal shipping profiles.  You can create as **many** profiles as you need (e.g. home address, office **address, etc.**)."

•Win 10 64 Bit with 1.1.0-RC1-alpha build

**Comment by HenkSwardt** [comment]
Assigning task to @cis-shubham-t
