### ISSUE TITLE
Crash on startup without error on Mac

### ISSUE THREAD

**Issue by mfts** [particl/particl-desktop#992]
The Particl Desktop version crashes on startup without throwing an error

# Describe bug/issue

Particl Desktop crashes on startup

# How to reproduce

Describe the steps needed to recreate the bug/issue:

1. Download version 1.1.0 hosted on /releases 
2. Unzip
3. Launch Particl Desktop
4. See it crashing after trying to initialize

# More information

- Operating system and version: Macbook Air (around 2013), macOS High Sierra Version 10.13.4 
- Client version: 1.1.0

**Comment by kewde** [comment]
@mfts please run the application from the command line and post the log returned in the command line.

Also try running with the -reindex flag.

**Comment by kewde** [comment]
@sebpalluel 

It seems that you already have a particl instance running, perhaps the Qt wallet?
If that is not the case, please manually delete the .lock file in the particl-core directory.

**Comment by sebpalluel** [comment]
No, i don't have any instance of particl daemon already running, i've checked with 'htop'. I've deleted the file "~/Library/Application Support/Particl/.lock" and it doesn't do the trick.

**Comment by mfts** [comment]
I didn't have two daemons running but I had a previous wallet's library contents with the name "Particl" and not "Particl Desktop" still on my computer and it seems like the new GUI couldn't differentiate. 

I deleted everything (the previous wallet was empty) and now the new GUI works as expected.

**Comment by sebpalluel** [comment]
It worked for me also by renaming Particl for Particl-backup and re-importing my wallet.dat. 
What's weird is that i haven't had this problem before. I'm using the desktop wallet since it came out and i haven't messed with my library. Maybe it's linked to the update i've made recently to mac os High Sierra.

**Comment by kewde** [comment]
@sebpalluel @mfts 
A premature shutdown of the daemon is likely to have caused this.
We've recently changed the shutdown handling and the next release shouldn't have this problem.

**Comment by kotaru77** [comment]
Hi Kewde, I have the same exact issue with the Particl desktop. I just run it as an application. I dont have any other instances running. Where is a wallet.dat for desktop wallet application typically?
Any help will be appreciated.

**Comment by rynomster** [comment]
The wallet.dat is typically in `/Users/username/Library/Application
Support/Particl`
Also check debug.log in the same folder. It might give a clue as to why
it's crashing

**Comment by kotaru77** [comment]
I had my heart in the throat for a few hours after doing exactly what worked for others. I did a backup of Particl folder luckily before renaming it. When I ran the wallet application again, it created a whole new wallet. Reimport of the wallet.dat from the backup helped it to function normally. Particl Desktop folder doesnt seem to have much significance.
