### ISSUE TITLE
Implement Muon (and get Tor for free)

### ISSUE THREAD

**Issue by kewde** [particl/particl-desktop#996]
Muon has recently added support for Tor.

Interesting bits for integrating it are here:
https://github.com/brave/browser-laptop/compare/feature/tor

**Comment by kewde** [comment]
I still need to look at the PID file, datadir and potentially the watch dir.
My own experience with implementing Tor in the past, was that additional parameters are required for concurrent instances of Tor to run side by side nicely.
tor_data_dir: also needed - needs a different datadir to prevent conflicts with Tor Browser or other

**Comment by kewde** [comment]
Ahhh,
Muon takes care of it.
Initially they were going to do in the brave browser but it's been moved over to Muon.
https://github.com/brave/muon/pull/473/files#diff-0a15f9800bfd45587a90bc6863c3a437R66

Still need to fix the userPath.
```
PathService::Get(chrome::DIR_USER_DATA, &user_data_dir);
```

**Comment by zaSmilingIdiot** [comment]
Doesn't look like this is relevant anymore. Muon is now archived, last updated at the end of 2018... this doesn't seem to be relevant anymore.
